### ISSUE TITLE
Java IO exception running Bulk API in jmeter

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#107]
```java
package com.marklogic.jmeter.sampler;
 
import java.io.Serializable;

import org.apache.jmeter.protocol.java.sampler.AbstractJavaSamplerClient;
import org.apache.jmeter.config.Arguments;
import org.apache.jmeter.samplers.SampleResult;
import org.apache.jmeter.protocol.java.sampler.JavaSamplerContext;

import com.marklogic.client.document.*;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.DatabaseClient;


public class BulkReadSampler extends AbstractJavaSamplerClient implements Serializable {

    private static final long serialVersionUID = 1L;
    private DatabaseClient client;
    private XMLDocumentManager DocMgr;
    private int numBatches, batchSize;
 
    @Override
    public void setupTest(JavaSamplerContext context) {
        client = DatabaseClientFactory.newClient(context.getParameter("HOST"),
                                                 context.getIntParameter("PORT"),
                                                 context.getParameter("USER"),
                                                 context.getParameter("PASSWORD"),
                                                 DatabaseClientFactory.Authentication.DIGEST);
       
        numBatches = context.getIntParameter("NUMBATCHES");
        batchSize = context.getIntParameter("BATCHSIZE");
        DocMgr = client.newXMLDocumentManager();
    }
   
    // set up default arguments for the JMeter GUI
    @Override
    public Arguments getDefaultParameters() {
        Arguments defaultParameters = new Arguments();
        defaultParameters.addArgument("HOST", "localhost");
        defaultParameters.addArgument("PORT", "8003");
        defaultParameters.addArgument("USER", "admin");
        defaultParameters.addArgument("PASSWORD", "admin");
        defaultParameters.addArgument("NUMBATCHES", "10000");
        defaultParameters.addArgument("BATCHSIZE", "10");
        return defaultParameters;
    }
 
    @SuppressWarnings("unused")
    @Override
    public SampleResult runTest(JavaSamplerContext context) {
    
        String[] uris = new String[batchSize];
        DocumentPage docs;
        SampleResult result = new SampleResult();
 
        result.sampleStart(); // start stopwatch

        try {
           
            // Read numBatches*batchSize documents from server
            for (int i=0; i<numBatches; i++) {
                for (int j=1; j<=batchSize; j++) {
                    uris[j-1] = "files"+String.format("%04d",i)+"/file"+String.format("%02d",j);
                }
                docs = DocMgr.read(uris);
            }
   

            result.sampleEnd(); // stop stopwatch
            result.setSuccessful( true );
            result.setResponseMessage( String.valueOf(numBatches)+" batches successfully read!" );
           
            //result.setResponseCodeOK(); // 200 code
           
        } catch (Exception e) {
            result.sampleEnd(); // stop stopwatch
            result.setSuccessful( false );
            result.setResponseMessage( "Exception: " + e );
 
            // get stack trace as a String to return as document data
            java.io.StringWriter stringWriter = new java.io.StringWriter();
            e.printStackTrace( new java.io.PrintWriter( stringWriter ) );
            result.setResponseData( stringWriter.toString(), null );
            result.setDataType( org.apache.jmeter.samplers.SampleResult.TEXT );
            result.setResponseCode( "500" );
        }
 
        return result;
    }
   
    public void teardownTest(JavaSamplerContext context) {
       
        client.release();
    }
}
```

Available stack:

```
javax.ws.rs.WebApplicationException: org.jvnet.mimepull.MIMEParsingException: java.io.IOException: Too many open files
    at com.sun.jersey.multipart.impl.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:146)
    at com.sun.jersey.multipart.impl.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:82)
    at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:565)
    at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:517)
    at com.marklogic.client.impl.JerseyServices.makeResults(JerseyServices.java:4121)
    at com.marklogic.client.impl.JerseyServices.getIteratedResourceImpl(JerseyServices.java:3097)
    at com.marklogic.client.impl.JerseyServices.getBulkDocumentsImpl(JerseyServices.java:764)
    at com.marklogic.client.impl.JerseyServices.getBulkDocuments(JerseyServices.java:700)
    at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:342)
    at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:330)
    at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:317)
    at com.marklogic.jmeter.sampler.BulkReadSampler.runTest(BulkReadSampler.java:65)
    at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:191)
    at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:429)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.jvnet.mimepull.MIMEParsingException: java.io.IOException: Too many open files
    at org.jvnet.mimepull.MemoryData.createNext(MemoryData.java:98)
    at org.jvnet.mimepull.Chunk.createNext(Chunk.java:64)
    at org.jvnet.mimepull.DataHead.addBody(DataHead.java:87)
    at org.jvnet.mimepull.MIMEPart.addBody(MIMEPart.java:197)
    at org.jvnet.mimepull.MIMEMessage.makeProgress(MIMEMessage.java:240)
    at org.jvnet.mimepull.MIMEMessage.parseAll(MIMEMessage.java:181)
    at org.jvnet.mimepull.MIMEMessage.getAttachments(MIMEMessage.java:106)
    at com.sun.jersey.multipart.impl.MultiPartReaderClientSide.readMultiPart(MultiPartReaderClientSide.java:187)
    at com.sun.jersey.multipart.impl.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:144)
    ... 15 more
Caused by: java.io.IOException: Too many open files
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:1006)
    at java.io.File.createTempFile(File.java:1989)
    at java.io.File.createTempFile(File.java:2040)
    at org.jvnet.mimepull.MemoryData.createNext(MemoryData.java:92)
    ... 23 more
```

**Comment by chiamarc** [comment]
The issue is fixed, and performance is on par with my previous workaround,however I am seeing messages on console in the form of the following:

`Jan 14, 2015 11:39:59 AM org.jvnet.mimepull.WeakDataFile close`
`INFO: File /tmp/MIME7522789270844789936.tmp was not deleted`
