### ISSUE TITLE
DMSDK does not work with JDK 11 due to threadpool configuration

### ISSUE THREAD

**Issue by tdiepenbrock** [marklogic/java-client-api#1116]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
4.0.4

### Version of MarkLogic Server

9.0-9
### Java version
JDK 11

### OS and version
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G5019

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
Create a QueryBatcher.  Configure it like so:
batcher.withBatchSize(100)
    	.withThreadCount(10)
    	.withConsistentSnapshot();

### Actual output: What did you observe? What errors did you see? Can you attach the logs? 
Exception in thread "main" java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(ThreadPoolExecutor.java:1535)
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl.initialize(QueryBatcherImpl.java:354)
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl.start(QueryBatcherImpl.java:325)
	at com.marklogic.client.datamovement.impl.DataMovementServices.startJob(DataMovementServices.java:100)
	at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.startJob(DataMovementManagerImpl.java:86)
	at com.marklogic.javaclientapitest.MarkLogicJavaClientAPITest.DMSDKUpdatePropertyValue.main(DMSDKUpdatePropertyValue.java:82)

### Expected output: What specifically did you expect to happen?
The issue here is that the QueryBatcherImpl calls ThreadPoolExecutor.setCorePoolSize() before it calls ThreadPoolExecutor.setMaximumPoolSize().  ThreadPoolExecutor.setCorePoolSize() checks to see if the corePoolSize parameter is greater than the maximumPoolSize, and if so it throws the above exception.  ThreadPoolExecutor.setMaximumPoolSize() needs to be called first to prevent this.

**Comment by ehennum** [comment]
Thanks for diagnosing the issue.

**Comment by ehennum** [comment]
The call to setCorePoolSize() was removed as part of the fix #881, which released in 4.1.0

If you upgrade, does the issue go away?
