### ISSUE TITLE
ml-development-tools tests fail due to initialization errors

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1126]
### Version of MarkLogic Java Client API
develop branch

### Version of MarkLogic Server

On 9.0 and 10.0 nightly build

### Java version

Oracle Java 9.0

### OS and version

Happens on both Widows and Linux.

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end

Run gradle command to generate tests for ml-development-tools project's tests.
```./gradlew ml-development-tools:generateTests```

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
Exceptions are thrown.
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.marklogic.client.test.dbfunction.FntestconfKt.setupModules(fntestconf.kt:128)
	at com.marklogic.client.test.dbfunction.FntestconfKt.dbfTestSetup(fntestconf.kt:55)
	at com.marklogic.client.test.dbfunction.FntestconfKt.main(fntestconf.kt:48)
Caused by: java.lang.RuntimeException: 401 Unauthorized
	at com.marklogic.client.test.dbfunction.DBFunctionTestUtil.makeClientImpl(DBFunctionTestUtil.java:65)
	at com.marklogic.client.test.dbfunction.DBFunctionTestUtil.makeTestClientImpl(DBFunctionTestUtil.java:43)
	at com.marklogic.client.test.dbfunction.DBFunctionTestUtil.makeTestClient(DBFunctionTestUtil.java:30)
	at com.marklogic.client.test.dbfunction.DBFunctionTestUtil.<clinit>(DBFunctionTestUtil.java:16)
	... 3 more

> Task :ml-development-tools:setupTestServer FAILED
  ```
8016_AccessLog.txt produced this output:
```
127.0.0.1 - - [03/Sep/2019:14:10:55 -0700] "GET / HTTP/1.1" 401 209 - "okhttp/3.10.0"
127.0.0.1 - rest-reader [03/Sep/2019:14:10:55 -0700] "GET / HTTP/1.1" 401 209 - "okhttp/3.10.0"
```

Looks like ```RuntimeException``` from ```makeClientImpl(....)``` method during static initialization in 
```public final static DatabaseClient db = makeTestClient();``` causes the JVM to throw ```java.lang.NoClassDefFoundError``` during test execution. 

### Expected output: What specifically did you expect to happen?
Tests generated.

**Comment by ehennum** [comment]
The fix to #1121 switched from admin to rest-reader but neglected to create the rest-reader user.

So, it works if you previously setup the Java unit tests (which create the rest-reader user) but not if you setup the tools unit tests in isolation.

Modifying the setup should fix this issue.

**Comment by ehennum** [comment]
Confirmed that this change creates the rest-reader user

**Comment by georgeajit** [comment]
Looks like we need to have a Http/Rest server running on port 8012 in-order for Data Services tests (at least static tests for time being) to be generated and run to completion successfully through ```gradle``` tasks.

Running ```./gradlew ml-development-tools:generateTests``` produces 
```
> Task :ml-development-tools:setupTestServer FAILED
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.marklogic.client.test.dbfunction.FntestconfKt.setupModules(fntestconf.kt:138)
        at com.marklogic.client.test.dbfunction.FntestconfKt.dbfTestSetup(fntestconf.kt:55)
        at com.marklogic.client.test.dbfunction.FntestconfKt.main(fntestconf.kt:48)
Caused by: java.lang.RuntimeException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8012
        at com.marklogic.client.test.dbfunction.DBFunctionTestUtil.makeClientImpl(DBFunctionTestUtil.java:68)
        at com.marklogic.client.test.dbfunction.DBFunctionTestUtil.makeRestClientImpl(DBFunctionTestUtil.java:40)
        at com.marklogic.client.test.dbfunction.DBFunctionTestUtil.makeRestClient(DBFunctionTestUtil.java:25)
        at com.marklogic.client.test.dbfunction.DBFunctionTestUtil.<clinit>(DBFunctionTestUtil.java:19)
        ... 3 more
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8012
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:242)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.marklogic.client.test.dbfunction.DBFunctionTestUtil.makeClientImpl(DBFunctionTestUtil.java:62)
```
As a workaround, tried this workflow to run all of the tool's tests:
Note : ```testServerInit``` task was used so that we have a HTTP or RESTApp Server on poirt 8012.
```./gradlew marklogic-client-api:testServerInit```
```./gradlew ml-development-tools:generateTests```
These above steps produces another failure:
```
> Task :ml-development-tools:setupTestServer FAILED
Exception in thread "main" java.lang.RuntimeException: Could not create rest-reader user: 400
        at com.marklogic.client.test.dbfunction.FntestconfKt.createEntity(fntestconf.kt:116)
        at com.marklogic.client.test.dbfunction.FntestconfKt.setupServer(fntestconf.kt:83)
        at com.marklogic.client.test.dbfunction.FntestconfKt.dbfTestSetup(fntestconf.kt:54)
        at com.marklogic.client.test.dbfunction.FntestconfKt.main(fntestconf.kt:48)
```
The reason for above failure is clear.First and second task, both, creates ```rest-reader``` user.

Finally, had to use Admin GUI to create a Http Server on 8012. Then ran following two gradle tasks to have all static Data Services tests run successfully.
```./gradlew ml-development-tools:generateTests```
```./gradlew ml-development-tools:test```

**Comment by ehennum** [comment]
I'm puzzled why the ConnectException is thrown.  

On the develop branch, the setupModules() function at line 138 of fntestconf.kt doesn't connect to the server:

https://github.com/marklogic/java-client-api/blob/develop/ml-development-tools/src/test/kotlin/com/marklogic/client/test/dbfunction/fntestconf.kt#L138

Just to confirm, is the test is using the develop branch?

**Comment by georgeajit** [comment]
Yes. Tests are run on develop branch.

**Comment by georgeajit** [comment]
Tested with latest pull. Tests are generated and they ran as expected, without any failures.
