### ISSUE TITLE
SSLTest.testSSLAuth assert failure when run with Java 9

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1137]
### Version of MarkLogic Java Client API
develop

### Version of MarkLogic Server

10.0 nightly

### Java version

Java 9 

### OS and version

All platforms.

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
Run ```com.marklogic.client.test.SSLTest.testSSLAuth``` test.

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
```
org.junit.ComparisonFailure: expected:<...ssl.SSLException: Un[recognized SSL message, plaintext connection?]> but was:<...ssl.SSLException: Un[supported or unrecognized SSL message]>
```
```
Stacktrace
org.junit.ComparisonFailure: expected:<...ssl.SSLException: Un[recognized SSL message, plaintext connection?]> but was:<...ssl.SSLException: Un[supported or unrecognized SSL message]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.marklogic.client.test.SSLTest.testSSLAuth(SSLTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
...
...
```
### Expected output: What specifically did you expect to happen?
Test runs fine.
### Alternatives: What else have you tried, actual/expected?
N/A

**Comment by ehennum** [comment]
I modified the failure check to tolerate more variation in wording.

I also cleaned up the test to use a non-deprecated authentication interface.

If that causes issues for an appserver with SSL enabled, please send this bug back to me.

**Comment by georgeajit** [comment]
Fixed.
