### ISSUE TITLE
Rename output caller method name in interface definitions

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1160]
For ```BulkInputOutputCaller IObulkCaller = IOEndpt.bulkCaller();```, 
calling ```input.forEach(IObulkCaller::accept);``` before ```IObulkCaller.forEachOutput(record -> {Consumer...});```
 produces 
``` java.lang.IllegalStateException: Output consumer is null``` when ```IObulkCaller.awaitCompletion();``` is called.

It could be nice, if method name (for Consumer) is changed in their respective caller interface definitions, so that end user is aware of making a call to consumer first, and then passes the input stream(s) to the endpoint module.

This may need to be documented as well.

So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
develop-72

### Version of MarkLogic Server

9.0 / 10 .0 nightly builds

### Java version

9.0

### OS and version

Windows / IDE

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
```
InputOutputEndpoint IOEndpt = InputOutputEndpoint.on(dbclient, jhAPI);
BulkInputOutputCaller IObulkCaller = IOEndpt.bulkCaller();

IObulkCaller.setEndpointState(new ByteArrayInputStream(returnIndex.getBytes()));
IObulkCaller.setWorkUnit(new ByteArrayInputStream(workParams.getBytes()));

File file6 = new File(DataConfigDirPath + "constraint1.json");
InputStream s6 = new FileInputStream(file6);
File file7 = new File(DataConfigDirPath + "constraint2.json");
InputStream s7 = new FileInputStream(file7);
File file8 = new File(DataConfigDirPath + "constraint3.json");
InputStream s8 = new FileInputStream(file8);
File file9 = new File(DataConfigDirPath + "constraint4.json");
InputStream s9 = new FileInputStream(file9);
File file10 = new File(DataConfigDirPath + "constraint5.json");
InputStream s10 = new FileInputStream(file10);

Stream<InputStream> input = Stream.of(s6, s7, s8, s9, s10);
input.forEach(IObulkCaller::accept);

IObulkCaller.forEachOutput(record -> {
				int c;
				try {
					int n = record.available();
					byte[] bytes = new byte[n];
					record.read(bytes, 0, n);
					String s = new String(bytes, StandardCharsets.UTF_8);
					batchResults.append(s);
				} catch (IOException e) {
					err.append(e.getMessage());
					e.printStackTrace();
				}
			}
	);

IObulkCaller.awaitCompletion();
...
```
### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
```
java.lang.IllegalStateException: Output consumer is null
	at com.marklogic.client.dataservices.impl.InputOutputEndpointImpl$BulkInputOutputCallerImpl.accept(InputOutputEndpointImpl.java:101)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:591)
	at com.marklogic.client.functionaltest.DynamicDataServicesFnTest.TestIngestEgressSessionFields(DynamicDataServicesFnTest.java:344)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
### Expected output: What specifically did you expect to happen?
SJS modules get executed.

### Alternatives: What else have you tried, actual/expected?
Reverse the order of calls to input and output works.

**Comment by ehennum** [comment]
As we discussed, the rename settled on:

    `void setOutputListener(Consumer<InputStream> listener);`

Other than changing the name in the functional tests, the rename shouldn't cause any issues.

**Comment by georgeajit** [comment]
Functional tests changed. No regressions seen.
