### ISSUE TITLE
GraphsTest unit tests have assert failures 

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1192]
### Version of MarkLogic Java Client API
develop

### Version of MarkLogic Server
10.0 nightly build ( To be released in April 2020 as 10.0-4)

### Java version

9.0

### OS and version

Linux 

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
N/A
### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)

Some of these tests have failures, which would be related with DeDup fix on ML Server build. Test method # 5 seems to have an user privilege issue. Have Included a sample stack trace for each of test method failure, since the assert differences reported have huge number of lines.

1. com.marklogic.client.test.GraphsTest.testTriples()
```
at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.marklogic.client.test.GraphsTest.testTriples(GraphsTest.java:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
...
```

2. com.marklogic.client.test.GraphsTest.testTransactions()
```
java.lang.AssertionError: reader could read graph outside transaction
	at org.junit.Assert.fail(Assert.java:88)
	at com.marklogic.client.test.GraphsTest.testTransactions(GraphsTest.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
...
```
3. com.marklogic.client.test.GraphsTest.testQuads()
```
at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.marklogic.client.test.GraphsTest.testQuads(GraphsTest.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
...
```
4. com.marklogic.client.test.GraphsTest.testQuadsWithTransaction()
```
at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.marklogic.client.test.GraphsTest.testQuadsWithTransaction(GraphsTest.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```
5.  com.marklogic.client.test.SemanticsPermissionsTest.A_testReadPemission()
```
java.lang.AssertionError: User write-privileged should see ForbiddenUserException when trying to read
	at org.junit.Assert.fail(Assert.java:88)
	at com.marklogic.client.test.SemanticsPermissionsTest.A_testReadPemission(SemanticsPermissionsTest.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```

**Comment by ehennum** [comment]
These may be due to internal error 54436.

**Comment by ehennum** [comment]
I checked an enode fix under 54436 that, in my testing, removes the regression in the GraphsTest and SemanticsPermissionsTest unit tests.

**Comment by georgeajit** [comment]
Test are running fine.
