### ISSUE TITLE
WriteBatcherTest has two test asserts when running on three node cluster env

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1195]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
develop branch

### Version of MarkLogic Server

10.0 nightly build for 10.0-4 release.
### Java version

Java 9

### OS and version

Linux 3 node cluster env.

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
Execute WriteBatcherTest test on develop branch with a nightly ML Server build (in 10.0-4 release period) on 3 node cluster.

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
1) ```com.marklogic.client.test.datamovement.WriteBatcherTest.testBatchesThreads```

```
Error Message
java.lang.AssertionError: The success listener ran wrong number of times expected:<200> but was:<196>
Stacktrace
java.lang.AssertionError: The success listener ran wrong number of times expected:<200> but was:<196>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.marklogic.client.test.datamovement.WriteBatcherTest.runWriteTest(WriteBatcherTest.java:666)
	at com.marklogic.client.test.datamovement.WriteBatcherTest.testBatchesThreads(WriteBatcherTest.java:522)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```
2) ```com.marklogic.client.test.datamovement.WriteBatcherTest.testEverything```

```
Error Message
java.lang.AssertionError: The success listener ran wrong number of times expected:<200> but was:<184>
Stacktrace
java.lang.AssertionError: The success listener ran wrong number of times expected:<200> but was:<184>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.marklogic.client.test.datamovement.WriteBatcherTest.runWriteTest(WriteBatcherTest.java:666)
	at com.marklogic.client.test.datamovement.WriteBatcherTest.testEverything(WriteBatcherTest.java:527)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:
```

### Expected output: What specifically did you expect to happen?
Tests run fine. No assert failures.
### Alternatives: What else have you tried, actual/expected?
N/A

**Comment by georgeajit** [comment]
Just FYI. This test ran fine on single node env.

**Comment by ehennum** [comment]
I'm not able to reproduce the issue on the cluster with 3 nodes and 9 forests that you set up.

**Comment by georgeajit** [comment]
Going to close this issue. Tests on Jenkins env does not fail with 03162020 ML Server build.
