### ISSUE TITLE
Fix RowManagerTest.testJoinDocUri test

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1215]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
develop branch (post (5.2.0)
### Version of MarkLogic Server

10.0 nightly

### Java version

Java 9

### OS and version

Linux

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
Run ```RowManagerTest.testJoinDocUri``` method
### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
```
java.lang.AssertionError: unexpected count of result records expected:<2> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.marklogic.client.test.RowManagerTest.testJoinDocUri(RowManagerTest.java:500)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
...
```
### Expected output: What specifically did you expect to happen?
Test runs without asserts.
### Alternatives: What else have you tried, actual/expected?
None.

**Comment by ehennum** [comment]
Interesting.  For me, that test passes locally.
