### ISSUE TITLE
Fix PlanGeneratedTest tests

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1254]
### Version of MarkLogic Java Client API
develop (post 5.2.0 release)

### Version of MarkLogic Server

10.0 nightly builds (> 10.0-4 release)

### Java version

OpenJDK 9

### OS and version

Linux
### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
PlanGeneratedTest. unit tests

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
Here is the stack trace from one of the tests. We have 19 test failures. 
https://jenkins.marklogic.com/view/Java%20API/job/Java9/job/Java-client-api-develop-10.0-nightly_OPENJDK9/lastCompletedBuild/testReport/

```
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at rows: Bad Request. Server Message: XDMP-ARGTYPE: (err:XPTY0004) sql:day(1) -- arg1 is not of type genericDateTime?
	at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4445)
	at com.marklogic.client.impl.OkHttpServices.postIteratedResourceImpl(OkHttpServices.java:3967)
	at com.marklogic.client.impl.OkHttpServices.postIteratedResource(OkHttpServices.java:3927)
	at com.marklogic.client.impl.RowManagerImpl.makeRequest(RowManagerImpl.java:321)
	at com.marklogic.client.impl.RowManagerImpl.resultRows(RowManagerImpl.java:171)
	at com.marklogic.client.impl.RowManagerImpl.resultRows(RowManagerImpl.java:164)
	at com.marklogic.client.test.PlanGeneratedBase.executeTester(PlanGeneratedBase.java:94)
	at com.marklogic.client.test.PlanGeneratedTest.testSqlDay1Exec(PlanGeneratedTest.java:1103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
...
...
```
### Expected output: What specifically did you expect to happen?
Test passes

### Alternatives: What else have you tried, actual/expected?
N/A

**Comment by ehennum** [comment]
See internal issue 55355

**Comment by ehennum** [comment]
Noting that, with the Friday fix to the server, most expression functions seem to be working now with the exception of xdmp:lshift64() and xdmp:rshift64()

**Comment by georgeajit** [comment]
Tests are running fine.
