### ISSUE TITLE
Pojo range query on Integer value seems to use decimal value

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#222]
In my infinite wisdom, I created a class that had a property of type Integer (not int), then created an INT typed index on it. When I made a range query against the property, I got XDMP-PATHRIDXNOTFOUND. I believe this is because it resulted in a cts query on a decimal value (1.0 rather than 1).

```
Exception in thread "main" com.marklogic.client.FailedRequestException: Local message: search failed: Bad Request. Server Message: XDMP-PATHRIDXNOTFOUND: cts:search(fn:collection(), cts:and-query((cts:path-range-query("sandbox.Edition2/printing", ">", 1.0, (), 1), cts:collection-query("sandbox.Edition2")), ()), ("score-logtfidf", cts:score-order("descending")), xs:double("1"), ()) -- No decimal path range index for sandbox.Edition2/printing 
	at com.marklogic.client.impl.JerseyServices$JerseySearchRequest.getResponse(JerseyServices.java:2204)
	at com.marklogic.client.impl.JerseyServices.getBulkDocumentsImpl(JerseyServices.java:872)
	at com.marklogic.client.impl.JerseyServices.getBulkDocuments(JerseyServices.java:744)
	at com.marklogic.client.impl.DocumentManagerImpl.search(DocumentManagerImpl.java:500)
	at com.marklogic.client.impl.JSONDocumentImpl.search(JSONDocumentImpl.java:26)
	at com.marklogic.client.impl.PojoRepositoryImpl.search(PojoRepositoryImpl.java:328)
	at com.marklogic.client.impl.PojoRepositoryImpl.search(PojoRepositoryImpl.java:305)
	at sandbox.useInteger.main(useInteger.java:31)
```

I'm not entirely convinced this is a bug, but thought I should throw it out there for your contemplation. I think it's one of those things I fell into by accident that real people don't do. Idiot loose on the keyboard, etc. It might also just be plain wrong - maybe INT isn't the right index type for Integer.

I'll post the code in the comments below.

**Comment by georgeajit** [comment]
Changed to ship. Will track Git # 238 for timing issues.
