### ISSUE TITLE
QueryByExampleTest failing on -1 from getTotalSize()

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#232]
It appears a scenario was broken by the changes to the way we populate totalSize.

java.lang.AssertionError: No XML documents should have matched expected:<-1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at com.marklogic.client.test.QueryByExampleTest.xmlQbe(QueryByExampleTest.java:104)

**Comment by sammefford** [comment]
Test succeeds now.  Closing this.
