### ISSUE TITLE
No configured options: filtered

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#240]
com.marklogic.client.FailedRequestException: Local message: search failed: Bad Request. Server Message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: No configured options: filtered
	at com.marklogic.client.impl.JerseyServices$JerseySearchRequest.getResponse(JerseyServices.java:2206)
	at com.marklogic.client.impl.JerseyServices.getBulkDocumentsImpl(JerseyServices.java:869)
	at com.marklogic.client.impl.JerseyServices.getBulkDocuments(JerseyServices.java:744)
	at com.marklogic.client.impl.DocumentManagerImpl.search(DocumentManagerImpl.java:500)
	at com.marklogic.client.impl.JSONDocumentImpl.search(JSONDocumentImpl.java:26)
	at com.marklogic.client.impl.PojoRepositoryImpl.search(PojoRepositoryImpl.java:340)
	at com.marklogic.client.impl.PojoRepositoryImpl.search(PojoRepositoryImpl.java:317)
	at com.marklogic.client.test.PojoFacadeTest.testC_QueryPojos(PojoFacadeTest.java:291)

**Comment by sammefford** [comment]
The persisted options named "filtered" are created in [bootstrap.xqy] (https://github.com/marklogic/java-client-api/blob/dev/src/test/resources/bootstrap.xqy#L1076-L1084).

**Comment by sammefford** [comment]
Charles, this unit test worked, but is now failing.  I'm not sure what to change.  When you have a moment, can you look at this and tell me if there's anything obvious I'm doing wrong?

**Comment by grechaw** [comment]
I would highligh recommend against the method you're using here.  Is the idea that a lot of tests use filtered, so you'd like it to be available at all times?

I think it's important to use the REST API to install options -- what's going on for you here is that you're not setting the permissions for the options, but you should not have to do that,

Can this options installation just be incorporated into the setup/teardown of the invididual unit tests or the test class?  Then you can just use the Java API to store the options.

Something like

```
QueryOptionsManager queryOptionsMgr =
	Common.client.newServerConfigManager().newQueryOptionsManager();
	queryOptionsMgr.writeOptions(optionsName, new StringHandle("{\"options\":{\"search-option\":\"filtered\"}}"));
```

might work.
