### ISSUE TITLE
Three test failing with XDMP-UPDATEFUNCTIONFROMQUERY

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#242]
I’m suddenly getting three unit tests failing.  
```
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/docbatch: Internal Server Error. Server Message: XDMP-UPDATEFUNCTIONFROMQUERY: xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/docbatch","post"), "/marklogic.rest.resource/docbatch/assets/resource.xqy")($context, $service-params, $input) -- Cannot apply an update function from a query . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4423)
	at com.marklogic.client.impl.JerseyServices.postIteratedResourceImpl(JerseyServices.java:3965)
	at com.marklogic.client.impl.JerseyServices.postIteratedResource(JerseyServices.java:3904)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:118)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:114)
	at com.marklogic.client.example.extension.BatchManager.apply(BatchManager.java:403)
	at com.marklogic.client.example.extension.BatchManagerExample.useResource(BatchManagerExample.java:126)
	at com.marklogic.client.example.extension.BatchManagerExample.run(BatchManagerExample.java:59)
	at com.marklogic.client.example.extension.BatchManagerExample.main(BatchManagerExample.java:48)
	at com.marklogic.client.test.example.extension.BatchManagerTest.testMain(BatchManagerTest.java:35)


com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/graph: Internal Server Error. Server Message: XDMP-UPDATEFUNCTIONFROMQUERY: xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/graph","post"), "/marklogic.rest.resource/graph/assets/resource.xqy")($context, $service-params, $input) -- Cannot apply an update function from a query . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4423)
	at com.marklogic.client.impl.JerseyServices.postIteratedResourceImpl(JerseyServices.java:3892)
	at com.marklogic.client.impl.JerseyServices.postIteratedResource(JerseyServices.java:3826)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:100)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:96)
	at com.marklogic.client.example.extension.GraphManager.insert(GraphManager.java:136)
	at com.marklogic.client.example.extension.GraphSPARQLExample.insertGraph(GraphSPARQLExample.java:80)
	at com.marklogic.client.example.extension.GraphSPARQLExample.main(GraphSPARQLExample.java:42)
	at com.marklogic.client.test.example.extension.GraphSPARQLExampleTest.testMain(GraphSPARQLExampleTest.java:20)

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/docsplit: Internal Server Error. Server Message: XDMP-UPDATEFUNCTIONFROMQUERY: xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/docsplit","post"), "/marklogic.rest.resource/docsplit/assets/resource.xqy")($context, $service-params, $input) -- Cannot apply an update function from a query . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4423)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3407)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:91)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:87)
	at com.marklogic.client.example.extension.DocumentSplitter.split(DocumentSplitter.java:46)
	at com.marklogic.client.example.extension.OpenCSVBatcher$BatchSplitter.processAndContinue(OpenCSVBatcher.java:218)
	at com.marklogic.client.example.extension.OpenCSVBatcher.write(OpenCSVBatcher.java:174)
	at com.marklogic.client.example.extension.OpenCSVBatcher.write(OpenCSVBatcher.java:87)
	at com.marklogic.client.example.extension.OpenCSVBatcherExample.useResource(OpenCSVBatcherExample.java:120)
	at com.marklogic.client.example.extension.OpenCSVBatcherExample.run(OpenCSVBatcherExample.java:60)
	at com.marklogic.client.example.extension.OpenCSVBatcherExample.main(OpenCSVBatcherExample.java:49)
	at com.marklogic.client.test.example.extension.OpenCSVBatcherTest.testMain(OpenCSVBatcherTest.java:37)
```

**Comment by sammefford** [comment]
@ehennum pointed out:
That's likely because we intentionally changed it.
Previously, POST resource services started in query mode but evalled into update mode by default.
Now, the eval into update mode is not longer the default.  To make it explicit, you can add the following annotation to the XQuery function:
    declare %rapi:transaction-mode("update")
as in:
```
declare %rapi:transaction-mode("update")
declare function docbatch:post(
    $context as map:map,
    $params  as map:map,
    $input   as document-node()*
) as document-node()*
```
