### ISSUE TITLE
NoRouteToHostException when using 100 threads in stress test

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#250]
When we run stress tests with 25 threads we don't see errors.  But when we tried 100 threads we got the following error:

```
com.sun.jersey.api.client.ClientHandlerException: java.net.NoRouteToHostException: Cannot assign requested address
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:184)
        at com.marklogic.client.impl.DigestChallengeFilter.handle(DigestChallengeFilter.java:34)
        at com.sun.jersey.api.client.filter.HTTPDigestAuthFilter.handle(HTTPDigestAuthFilter.java:493)
        at com.sun.jersey.api.client.Client.handle(Client.java:648)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.put(WebResource.java:537)
        at com.marklogic.client.impl.JerseyServices.doPut(JerseyServices.java:4125)
        at com.marklogic.client.impl.JerseyServices.putResource(JerseyServices.java:3300)
        at com.marklogic.client.impl.ResourceServicesImpl.put(ResourceServicesImpl.java:81)
        at test.stress.JavaAPISession$AddDocResource.putDocument(JavaAPISession.java:342)
        at test.stress.JavaAPISession.putDocumentViaExtenstion(JavaAPISession.java:349)
        at test.stress.ExtensionLoadTester.putDocument(ExtensionLoadTester.java:28)
        at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:185)
        at test.stress.RestLoadTester.runTest(RestLoadTester.java:269)
        at test.stress.StressTest.run(StressTest.java:92)
Caused by: java.net.NoRouteToHostException: Cannot assign requested address
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
        at java.net.Socket.connect(Socket.java:529)
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:123)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:561)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:776)
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170)
        ... 15 more
```

This [stackoverflow thread](http://stackoverflow.com/questions/1572215/how-to-avoid-a-noroutetohostexception) generally recommends changing linux tcp_tw_reuse and tcp_tw_recycle but the last comment resonates with me.  I want to look into configuring Apache HttpClient to perhaps use a connection pool to avoid bumping into OS limitations on Sockets.

**Comment by sammefford** [comment]
At first we saw this error when running the java stress test on the same box as the e-node, but we were able to duplicate this when running java on its own separate box.  We tried with 75 threads and did not encounter this error.
