### ISSUE TITLE
MultiPart ClientHandlerException when under stress

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#251]
Under stress with 75 concurrent threads I encounter the following error within jersey:

com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class com.sun.jersey.multipart.MultiPart, and Java type class com.sun.jersey.multipart.MultiPart, and MIME media type application/xml; charset=utf-8 was not found
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:561)
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:517)
        at com.marklogic.client.impl.JerseyServices.getBulkDocumentsImpl(JerseyServices.java:874)
        at com.marklogic.client.impl.JerseyServices.getBulkDocuments(JerseyServices.java:744)
        at com.marklogic.client.impl.DocumentManagerImpl.search(DocumentManagerImpl.java:500)
        at com.marklogic.client.impl.JSONDocumentImpl.search(JSONDocumentImpl.java:26)
        at com.marklogic.client.impl.PojoRepositoryImpl.search(PojoRepositoryImpl.java:340)
        at com.marklogic.client.impl.PojoRepositoryImpl.search(PojoRepositoryImpl.java:325)
        at test.stress.JavaAPISession.searchPojos(JavaAPISession.java:502)
        at test.stress.PojoLoadTester.verifyIntervalAfterIteration(PojoLoadTester.java:76)
        at test.stress.RestLoadTester.runTest(RestLoadTester.java:278)
        at test.stress.StressTest.run(StressTest.java:89)

**Comment by grechaw** [comment]
moved to 8.0-2 per mr triage.

**Comment by sammefford** [comment]
Based on a lot of investigation I'm thinking we're facing legitimate usage here and we just need to increase the allowed number of open files on linux.  Right now ulimit -a returns 4096 meaning we're limited to 4096 open files for our user.  Yet I'm seeing up to 3058 /tmp/MIME* files in use at once by our stress test with only 20-25 threads running.  Here's my command:
    echo `lsof -p 27699 | grep /tmp/MIME | wc -l` `ls -1 /tmp/MIME* | wc -l`

We sometimes run our stress test with many more threads.  If I watch it, the number of /tmp/MIIME* files frequently drops back down to less than 100 indicating to me that we're appropriately closing the temp files but we sometimes need a lot at once.  (I say "we" loosely, the underlying library which creates the /tmp/MIME* files is mimepull which is used by Jersey 1.17 which we're currently using).  The reason we're using so many temp files is we're doing large bulk operations in parallel in multiple threads.  This is a stress test, after all.

**Comment by sammefford** [comment]
oops, I posted an update on the wrong bug.  I'm deleting it, but I'll leave this message here in case anyone noticed...

**Comment by gvaidees** [comment]
Sam, Should there be a milestone associated with this issue?

**Comment by sammefford** [comment]
Marking this "will not fix" because we plan to replace Jersey in 4.0.3

**Comment by xmlking** [comment]
@sammefford is there an early access to 4.0.3? I have to use this lib with Apache Spark and getting similar error 
https://github.com/marklogic/java-client-api/issues/769 
looking for workaround are  early access fix.
Thanks

**Comment by sammefford** [comment]
If you're ok with something that's not yet released, you could try the 3.0-develop branch.  It has Jersey replaced with OkHttp.  It's not an early access release--rather it's the latest develop branch for 3.x.  Please report any bugs you may encounter.

**Comment by xmlking** [comment]
@sammefford 👍 I will give it a try and share my results
Thanks
