### ISSUE TITLE
NoHttpResponseException when under stress

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#252]
I see the following repeatedly during last night's stress tests:

```
com.sun.jersey.api.client.ClientHandlerException: org.apache.http.NoHttpResponseException: The target server failed to respond
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:184)
        at com.marklogic.client.impl.DigestChallengeFilter.handle(DigestChallengeFilter.java:34)
        at com.sun.jersey.api.client.filter.HTTPDigestAuthFilter.handle(HTTPDigestAuthFilter.java:493)
        at com.sun.jersey.api.client.Client.handle(Client.java:648)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:568)
        at com.marklogic.client.impl.JerseyServices.doPost(JerseyServices.java:4192)
        at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3459)
        at com.marklogic.client.impl.JerseyServices.postBulkDocuments(JerseyServices.java:3571)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:553)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at test.stress.JavaAPISession.putDocuments(JavaAPISession.java:284)
        at test.stress.BulkLoadTester.finishBatch(BulkLoadTester.java:47)
        at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:194)
        at test.stress.RestLoadTester.runTest(RestLoadTester.java:273)
        at test.stress.StressTest.run(StressTest.java:89)
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
        at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:101)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:252)
        at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281)
        at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:247)
        at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:219)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:298)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:633)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:454)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:776)
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170)
        ... 16 more
```

It occurred at
2015-02-02 18:45:29 (Thread=428)
2015-02-02 18:45:29 (Thread=371)
2015-02-02 18:45:29 (Thread=361)
2015-02-02 18:45:29 (Thread=408)
2015-02-02 19:41:32 (Thread=667)
2015-02-02 20:29:29 (Thread=1077)
2015-02-02 20:29:29 (Thread=1008)
2015-02-02 20:29:29 (Thread=1021)
2015-02-02 22:15:40 (Thread=1731)
2015-02-03 00:48:56 (Thread=2683)
2015-02-03 00:48:56 (Thread=2602)
2015-02-03 00:48:56 (Thread=2717)
2015-02-03 01:40:58 (Thread=3066)
2015-02-03 01:40:58 (Thread=3019)
2015-02-03 01:40:58 (Thread=3007)
2015-02-03 02:33:46 (Thread=3301)
2015-02-03 02:33:46 (Thread=3355)
2015-02-03 02:33:46 (Thread=3367)
2015-02-03 04:29:13 (Thread=4010)
2015-02-03 04:29:13 (Thread=4074)
2015-02-03 04:29:13 (Thread=4047)
2015-02-03 05:18:53 (Thread=4363)
2015-02-03 05:18:53 (Thread=4425)
2015-02-03 06:14:10 (Thread=4757)
2015-02-03 07:16:32 (Thread=5041)
2015-02-03 07:16:32 (Thread=5140)
2015-02-03 08:07:10 (Thread=5484)
2015-02-03 08:07:10 (Thread=5496)

**Comment by sammefford** [comment]
I agree.  But I'll have to reproduce this with more system information tracking to know if MarkLogic server was really under stress.  So far we've been bottlenecked on the Java side and not able to significantly stress MarkLogic, as far as I can tell.

**Comment by grechaw** [comment]
moved to 8.0-2 per mr triage.

**Comment by georgeajit** [comment]
This issue happens in Java Client 2.0.5 also. Reproduced the issue under Java API stress tests run on 7.0-5 MarkLogic Build 20150225.

**Comment by grechaw** [comment]
I see I've been putting comments in BT that are not surfaced here.  

If you want to really stress the system, please ensure that MarkLogic's max threads is higher than the number of java threads you're using.  Otherwise, MarkLogic will get up to 32 threads (default) and not take any more.  I'm about 80% confident that's the error you're getting here, which would be expected on a system under a lot of stress.
