### ISSUE TITLE
Unit test ResourceServicesTest fails - failed to write resource at resources/testresource

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#271]
Error Message

Local message: failed to write resource at resources/testresource: Internal Server Error. Server Message: declare option xdmp:transaction-mode "update";  -- Operation not allowed on the currently executing transaction with identifier %1 . See the MarkLogic server error log for further detail.

Stacktrace

com.marklogic.client.FailedRequestException: Local message: failed to write resource at resources/testresource: Internal Server Error. Server Message: declare option xdmp:transaction-mode "update";  -- Operation not allowed on the currently executing transaction with identifier %1 . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4418)
	at com.marklogic.client.impl.JerseyServices.putResource(JerseyServices.java:3247)
	at com.marklogic.client.impl.ResourceServicesImpl.put(ResourceServicesImpl.java:72)
	at com.marklogic.client.impl.ResourceServicesImpl.put(ResourceServicesImpl.java:68)
	at com.marklogic.client.test.ResourceServicesTest.testResourceServices(ResourceServicesTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by sammefford** [comment]
This issue was in the server snapshot version and has gone away
