### ISSUE TITLE
Cookbook Example DocumentMetadataReadTest - read failed: Internal Server Error

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#272]
Error Message

Local message: read failed: Internal Server Error. Server Message: declare option xdmp:transaction-mode "auto";  -- Operation not allowed on the currently executing transaction with identifier %1 . See the MarkLogic server error log for further detail.

Stacktrace

com.marklogic.client.FailedRequestException: Local message: read failed: Internal Server Error. Server Message: declare option xdmp:transaction-mode "auto";  -- Operation not allowed on the currently executing transaction with identifier %1 . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.getDocumentImpl(JerseyServices.java:972)
	at com.marklogic.client.impl.JerseyServices.getDocument(JerseyServices.java:601)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:386)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:270)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:228)
	at com.marklogic.client.example.cookbook.DocumentMetadataRead.run(DocumentMetadataRead.java:68)
	at com.marklogic.client.example.cookbook.DocumentMetadataRead.main(DocumentMetadataRead.java:40)
	at com.marklogic.client.test.example.cookbook.DocumentMetadataReadTest.testMain(DocumentMetadataReadTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)

**Comment by sammefford** [comment]
This issue was in the server snapshot version and has gone away
