### ISSUE TITLE
Cookbook Example MultiStatementTransactionTest - read failed: Internal Server Error

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#273]
Error Message

Local message: read failed: Internal Server Error. Server Message: declare option xdmp:transaction-mode "auto";  -- Operation not allowed on the currently executing transaction with identifier %1 . See the MarkLogic server error log for further detail.

Stacktrace

com.marklogic.client.FailedRequestException: Local message: read failed: Internal Server Error. Server Message: declare option xdmp:transaction-mode "auto";  -- Operation not allowed on the currently executing transaction with identifier %1 . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.getDocumentImpl(JerseyServices.java:689)
	at com.marklogic.client.impl.JerseyServices.getDocument(JerseyServices.java:607)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:386)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:270)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:243)
	at com.marklogic.client.example.cookbook.MultiStatementTransaction.run(MultiStatementTransaction.java:67)
	at com.marklogic.client.example.cookbook.MultiStatementTransaction.main(MultiStatementTransaction.java:35)
	at com.marklogic.client.test.example.cookbook.MultiStatementTransactionTest.testMain(MultiStatementTransactionTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)

**Comment by sammefford** [comment]
This issue was in the server snapshot version and has gone away
