### ISSUE TITLE
Cookbook Example BatchManagerTest - failed to apply resource at resources/docbatch

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#274]
Local message: failed to apply resource at resources/docbatch: Internal Server Error. Server Message: declare option xdmp:transaction-mode "update";  -- Operation not allowed on the currently executing transaction with identifier %1 . See the MarkLogic server error log for further detail.

Stacktrace

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/docbatch: Internal Server Error. Server Message: declare option xdmp:transaction-mode "update";  -- Operation not allowed on the currently executing transaction with identifier %1 . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4418)
	at com.marklogic.client.impl.JerseyServices.postIteratedResourceImpl(JerseyServices.java:3960)
	at com.marklogic.client.impl.JerseyServices.postIteratedResource(JerseyServices.java:3899)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:118)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:114)
	at com.marklogic.client.example.extension.BatchManager.apply(BatchManager.java:403)
	at com.marklogic.client.example.extension.BatchManagerExample.useResource(BatchManagerExample.java:126)
	at com.marklogic.client.example.extension.BatchManagerExample.run(BatchManagerExample.java:59)
	at com.marklogic.client.example.extension.BatchManagerExample.main(BatchManagerExample.java:48)
	at com.marklogic.client.test.example.extension.BatchManagerTest.testMain(BatchManagerTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)

**Comment by sammefford** [comment]
This issue was in the server snapshot version and has gone away
