### ISSUE TITLE
Cookbook Example OpenCSVBatcherTest - failed to apply resource at resources/docsplit

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#276]
Error Message

Local message: failed to apply resource at resources/docsplit: Internal Server Error. Server Message: declare option xdmp:transaction-mode "update";  -- Operation not allowed on the currently executing transaction with identifier %1 . See the MarkLogic server error log for further detail.

Stacktrace

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/docsplit: Internal Server Error. Server Message: declare option xdmp:transaction-mode "update";  -- Operation not allowed on the currently executing transaction with identifier %1 . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4418)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3402)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:91)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:87)
	at com.marklogic.client.example.extension.DocumentSplitter.split(DocumentSplitter.java:46)
	at com.marklogic.client.example.extension.OpenCSVBatcher$BatchSplitter.processAndContinue(OpenCSVBatcher.java:218)
	at com.marklogic.client.example.extension.OpenCSVBatcher.write(OpenCSVBatcher.java:174)
	at com.marklogic.client.example.extension.OpenCSVBatcher.write(OpenCSVBatcher.java:87)
	at com.marklogic.client.example.extension.OpenCSVBatcherExample.useResource(OpenCSVBatcherExample.java:120)
	at com.marklogic.client.example.extension.OpenCSVBatcherExample.run(OpenCSVBatcherExample.java:60)
	at com.marklogic.client.example.extension.OpenCSVBatcherExample.main(OpenCSVBatcherExample.java:49)
	at com.marklogic.client.test.example.extension.OpenCSVBatcherTest.testMain(OpenCSVBatcherTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by sammefford** [comment]
This issue was in the server snapshot version and has gone away
