### ISSUE TITLE
PojoLoadTester throws REST-INVALIDMIMETYPE during failover time period.

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#283]
2015-03-31 20:54:36  (Thread=391) ========
Starting test with uniqueURI = /KSPQKCFLYKKFZPRL/2015231205436623/4/
# 

TestcaseID = pojoLoadTester
ThreadID = 391
BinaryTest = false
JSONTest = false
InsertTime = false
NumberOfLoops = 5
MaxSleepTime = 1
LogOption = debug
WriteToScreen = true 
LogFilename = auto 
OutputFileName = 

2015-03-31 20:54:36 (Thread=391) About to load 2501 documents.
2015-03-31 20:56:32 (Thread=391) About to load 2501 documents.
2015-03-31 20:58:53 (Thread=391) About to load 2501 documents.

21:00:00 <====== One of the D Node goes down.

Here is the stak trace from the thread 391.

2015-03-31 21:06:19 (Thread=391) com.marklogic.client.FailedRequestException: Local message: search failed: Unsupported Media Type. Server Message: REST-INVALIDMIMETYPE: (rest:INVALIDMIMETYPE) Content-Type must be one of:  'text/xml', 'text/json', 'application/xml', 'application/json', Received: text/plain
com.marklogic.client.FailedRequestException: Local message: search failed: Unsupported Media Type. Server Message: REST-INVALIDMIMETYPE: (rest:INVALIDMIMETYPE) Content-Type must be one of:  'text/xml', 'text/json', 'application/xml', 'application/json', Received: text/plain
    at com.marklogic.client.impl.JerseyServices$JerseySearchRequest.getResponse(JerseyServices.java:2206)
    at com.marklogic.client.impl.JerseyServices.getBulkDocumentsImpl(JerseyServices.java:869)
    at com.marklogic.client.impl.JerseyServices.getBulkDocuments(JerseyServices.java:744)
    at com.marklogic.client.impl.DocumentManagerImpl.search(DocumentManagerImpl.java:500)
    at com.marklogic.client.impl.JSONDocumentImpl.search(JSONDocumentImpl.java:26)
    at com.marklogic.client.impl.PojoRepositoryImpl.search(PojoRepositoryImpl.java:340)
    at com.marklogic.client.impl.PojoRepositoryImpl.search(PojoRepositoryImpl.java:325)
    at test.stress.JavaAPISession.searchPojos(JavaAPISession.java:526)
    at test.stress.PojoLoadTester.verifyIntervalAfterIteration(PojoLoadTester.java:75)
    at test.stress.RestLoadTester.runTest(RestLoadTester.java:283)
    at test.stress.StressTest.run(StressTest.java:94)
2015-03-31 21:06:19 (Thread=391) Test took: 702600ms

**Comment by sammefford** [comment]
This is addressed by the fix for #287

**Comment by georgeajit** [comment]
This issue has occurred with the latest Stress Test run. Here is an Java Program's log message snippet that has the exception.

This test with ThreadID = 442 started before one of the D Node goes down (The D Node was set to go down at 12:00)

2015-04-24 11:55:52 (Thread=442) ========
Starting test with uniqueURI = /NCWLGKIOXLRCBKKU/2015324115552164/4/
#
TestcaseID = pojoLoadTester
ThreadID = 442
BinaryTest = false
JSONTest = false
InsertTime = false
NumberOfLoops = 5
MaxSleepTime = 1
LogOption = debug
WriteToScreen = true
LogFilename = auto
OutputFileName =

2015-04-24 11:55:52 (Thread=442) About to load 2501 documents.
2015-04-24 12:04:36 (Thread=442) About to load 2501 documents.



2015-04-24 12:10:28 (Thread=442) com.marklogic.client.FailedRequestException: Local message: search failed: Unsupported Media Type. Server Message: REST-INVALIDMIMETYPE: (rest:INVALIDMIMETYPE) Content-Type must be one of:  'text/xml', 'text/json', 'application/xml', 'application/json', Received: text/plain
com.marklogic.client.FailedRequestException: Local message: search failed: Unsupported Media Type. Server Message: REST-INVALIDMIMETYPE: (rest:INVALIDMIMETYPE) Content-Type must be one of:  'text/xml', 'text/json', 'application/xml', 'application/json', Received: text/plain
    at com.marklogic.client.impl.JerseyServices$JerseySearchRequest.getResponse(JerseyServices.java:2215)
    at com.marklogic.client.impl.JerseyServices.getBulkDocumentsImpl(JerseyServices.java:870)
    at com.marklogic.client.impl.JerseyServices.getBulkDocuments(JerseyServices.java:747)
    at com.marklogic.client.impl.DocumentManagerImpl.search(DocumentManagerImpl.java:499)
    at com.marklogic.client.impl.JSONDocumentImpl.search(JSONDocumentImpl.java:26)
    at com.marklogic.client.impl.PojoRepositoryImpl.search(PojoRepositoryImpl.java:340)
    at com.marklogic.client.impl.PojoRepositoryImpl.search(PojoRepositoryImpl.java:325)
    at test.stress.JavaAPISession.searchPojos(JavaAPISession.java:526)
    at test.stress.PojoLoadTester.verifyIntervalAfterIteration(PojoLoadTester.java:75)
    at test.stress.RestLoadTester.runTest(RestLoadTester.java:283)
    at test.stress.StressTest.run(StressTest.java:94)
2015-04-24 12:10:28 (Thread=442) Test took: 875962ms
