### ISSUE TITLE
Stress Test FailedRequestException: Service unavailable and maximum retry period elapsed 

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#315]
In a stress test it is seen that the Java Program that loads documents report FailedRequestException when a downed D Node has come back up.

This is the exception that is being seen:
FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 60 retries

Below we have the the complete activities of a thread that displays this behaviour. The logs were searched for similar exception conditions and they were found to have the same stack trace (with same java class line number).

2015-06-29 16:07:14 (Thread=1080) ========
Starting test with uniqueURI = /UYQFXPLRYIUVOYSV/20155291671489/1/
#
TestcaseID = bulkLoadTester
ThreadID = 1080
BinaryTest = false
JSONTest = false
InsertTime = false
NumberOfLoops = 5
MaxSleepTime = 1
LogOption = debug
WriteToScreen = true
LogFilename = auto
OutputFileName =

2015-06-29 16:07:14 (Thread=1080) About to load 2501 documents.
2015-06-29 16:07:14 (Thread=1080) TransactionId: 631863748107869562
2015-06-29 16:07:14 (Thread=1080) TransactionId: 3288366832378707121
2015-06-29 16:07:14 (Thread=1080) TransactionId: 7558695811821366148
2015-06-29 16:07:14 (Thread=1080) TransactionId: 680993445147022055
2015-06-29 16:07:15 (Thread=1080) TransactionId: 1133334898571639061
2015-06-29 16:07:15 (Thread=1080) TransactionId: 12038160196899256752
2015-06-29 16:07:15 (Thread=1080) TransactionId: 10498342111496957352
2015-06-29 16:07:16 (Thread=1080) TransactionId: 1758640263038810990
2015-06-29 16:07:16 (Thread=1080) TransactionId: 1737551721088468843
2015-06-29 16:07:16 (Thread=1080) TransactionId: 3936493760789285434
2015-06-29 16:07:17 (Thread=1080) TransactionId: 152793235312806295
2015-06-29 16:07:17 (Thread=1080) TransactionId: 10388608468300168387
2015-06-29 16:07:17 (Thread=1080) TransactionId: 13079242090194523434
2015-06-29 16:07:17 (Thread=1080) TransactionId: 3550624309250093064
2015-06-29 16:07:18 (Thread=1080) TransactionId: 16422476573173302253
2015-06-29 16:07:18 (Thread=1080) TransactionId: 14821843749709018755
2015-06-29 16:07:18 (Thread=1080) TransactionId: 17809290189255027750
2015-06-29 16:07:19 (Thread=1080) TransactionId: 1399236309622905405
2015-06-29 16:07:19 (Thread=1080) TransactionId: 10144804310633502833
2015-06-29 16:07:19 (Thread=1080) TransactionId: 5992152891553551554
2015-06-29 16:07:20 (Thread=1080) TransactionId: 6330323561137115470
2015-06-29 16:07:20 (Thread=1080) TransactionId: 17702145833398942439
2015-06-29 16:07:20 (Thread=1080) TransactionId: 10330224659729951181
2015-06-29 16:07:20 (Thread=1080) TransactionId: 9261774131796246665
2015-06-29 16:07:21 (Thread=1080) TransactionId: 14791112211681752556
2015-06-29 16:07:21 (Thread=1080) TransactionId: 13094695656419682887
2015-06-29 16:07:21 (Thread=1080) TransactionId: 2033669210466127743
2015-06-29 16:07:22 (Thread=1080) TransactionId: 3147767572342905570
2015-06-29 16:07:22 (Thread=1080) TransactionId: 17800461829811373289
2015-06-29 16:07:22 (Thread=1080) TransactionId: 6925892833505959903
2015-06-29 16:07:22 (Thread=1080) TransactionId: 2011606725946931438
2015-06-29 16:07:23 (Thread=1080) TransactionId: 950335427742178855
2015-06-29 16:07:23 (Thread=1080) TransactionId: 18030424653413933222
2015-06-29 16:07:23 (Thread=1080) TransactionId: 16204965663958806544
2015-06-29 16:07:24 (Thread=1080) TransactionId: 16140397993409791296
2015-06-29 16:07:24 (Thread=1080) TransactionId: 1028501027939398022
2015-06-29 16:07:24 (Thread=1080) TransactionId: 511322178834649684
2015-06-29 16:07:25 (Thread=1080) TransactionId: 9034067177829352617
2015-06-29 16:07:25 (Thread=1080) TransactionId: 3823711256237756943
2015-06-29 16:07:26 (Thread=1080) TransactionId: 4166554377839944648
2015-06-29 16:07:26 (Thread=1080) TransactionId: 17461767427908301287
2015-06-29 16:07:26 (Thread=1080) TransactionId: 6114046908127973676
2015-06-29 16:07:27 (Thread=1080) TransactionId: 5147758042052947103
2015-06-29 16:07:27 (Thread=1080) TransactionId: 3580369975392849425
2015-06-29 16:07:27 (Thread=1080) TransactionId: 7790647338549023651
2015-06-29 16:07:27 (Thread=1080) TransactionId: 10516170363301566913
2015-06-29 16:07:28 (Thread=1080) TransactionId: 2547300647113808595
2015-06-29 16:07:28 (Thread=1080) TransactionId: 17558748707871542884
2015-06-29 16:07:28 (Thread=1080) TransactionId: 13177727954915460699
2015-06-29 16:07:29 (Thread=1080) TransactionId: 9580919351453081558
2015-06-29 16:07:29 (Thread=1080) TransactionId: 13735788964861664321
2015-06-29 16:07:29 (Thread=1080) About to load 2501 documents.
2015-06-29 16:07:29 (Thread=1080) TransactionId: 9036387298441365677
2015-06-29 16:07:29 (Thread=1080) TransactionId: 252817600996458785
2015-06-29 16:07:30 (Thread=1080) TransactionId: 11896782379736750512
2015-06-29 16:07:30 (Thread=1080) TransactionId: 10882890522136956547
2015-06-29 16:07:30 (Thread=1080) TransactionId: 564975616182708201
2015-06-29 16:07:30 (Thread=1080) TransactionId: 15661067370383734842
2015-06-29 16:07:31 (Thread=1080) TransactionId: 8379358560044518244
2015-06-29 16:07:31 (Thread=1080) TransactionId: 9467829291803082250
2015-06-29 16:07:31 (Thread=1080) TransactionId: 14807322170593913366
2015-06-29 16:07:32 (Thread=1080) TransactionId: 14505120971797706442
2015-06-29 16:07:32 (Thread=1080) TransactionId: 959440637700136614
2015-06-29 16:07:32 (Thread=1080) TransactionId: 18409639761701648565
2015-06-29 16:07:32 (Thread=1080) TransactionId: 9402470609489901712
2015-06-29 16:07:33 (Thread=1080) TransactionId: 10435760566584835443
2015-06-29 16:07:33 (Thread=1080) TransactionId: 8776229299371174098
2015-06-29 16:07:33 (Thread=1080) TransactionId: 16203911644696243487
2015-06-29 16:07:34 (Thread=1080) TransactionId: 7136048506768380115
2015-06-29 16:07:34 (Thread=1080) TransactionId: 17999104420005527006
2015-06-29 16:07:34 (Thread=1080) TransactionId: 480345073946584514
2015-06-29 16:07:34 (Thread=1080) TransactionId: 8931022122478056590
2015-06-29 16:07:35 (Thread=1080) TransactionId: 1552125602090241285
2015-06-29 16:07:35 (Thread=1080) TransactionId: 13787969171734699892
2015-06-29 16:07:35 (Thread=1080) TransactionId: 3520544358741237911
2015-06-29 16:07:36 (Thread=1080) TransactionId: 13041662953264770074
2015-06-29 16:07:36 (Thread=1080) TransactionId: 1249400302381084610
2015-06-29 16:07:36 (Thread=1080) TransactionId: 12579071158564793861
2015-06-29 16:07:36 (Thread=1080) TransactionId: 417756801581171911
2015-06-29 16:07:37 (Thread=1080) TransactionId: 15918102038320836932
2015-06-29 16:07:37 (Thread=1080) TransactionId: 15174709794009167447
2015-06-29 16:07:37 (Thread=1080) TransactionId: 2600200411082651290
2015-06-29 16:07:38 (Thread=1080) TransactionId: 3480521374831443983
2015-06-29 16:07:38 (Thread=1080) TransactionId: 602668530031190249
2015-06-29 16:07:38 (Thread=1080) TransactionId: 2709353245133242936
2015-06-29 16:07:38 (Thread=1080) TransactionId: 6152804267456386053
2015-06-29 16:07:39 (Thread=1080) TransactionId: 6443082726377751116
2015-06-29 16:07:39 (Thread=1080) TransactionId: 6277597249891423754
2015-06-29 16:07:39 (Thread=1080) TransactionId: 4342649596463501793
2015-06-29 16:07:39 (Thread=1080) TransactionId: 237518996161098636
2015-06-29 16:07:40 (Thread=1080) TransactionId: 2059208623532646629
2015-06-29 16:07:40 (Thread=1080) TransactionId: 1126144350776587074
2015-06-29 16:07:40 (Thread=1080) TransactionId: 11511368652553555559
2015-06-29 16:07:41 (Thread=1080) TransactionId: 729960273712156778
2015-06-29 16:07:41 (Thread=1080) TransactionId: 12953040568810016242
2015-06-29 16:07:41 (Thread=1080) TransactionId: 17053580448145025353
2015-06-29 16:07:41 (Thread=1080) TransactionId: 9930622651050949857
2015-06-29 16:07:42 (Thread=1080) TransactionId: 2187238799489682006
2015-06-29 16:07:42 (Thread=1080) TransactionId: 6333480287799623739
2015-06-29 16:07:42 (Thread=1080) TransactionId: 17207406947403268470
2015-06-29 16:07:43 (Thread=1080) TransactionId: 1681047949551407409
2015-06-29 16:07:43 (Thread=1080) TransactionId: 14549016793691691186
2015-06-29 16:07:43 (Thread=1080) TransactionId: 5021175086847544047
2015-06-29 16:07:43 (Thread=1080) About to load 2501 documents.
2015-06-29 16:07:43 (Thread=1080) TransactionId: 15491587543644946013
2015-06-29 16:07:43 (Thread=1080) TransactionId: 117859090746734340
2015-06-29 16:07:44 (Thread=1080) TransactionId: 12432095888368770402
2015-06-29 16:07:44 (Thread=1080) TransactionId: 1970431170763309230
2015-06-29 16:07:44 (Thread=1080) TransactionId: 17065416216805352179
2015-06-29 16:07:45 (Thread=1080) TransactionId: 6691529783968369261
2015-06-29 16:07:45 (Thread=1080) TransactionId: 8158270415781819975
2015-06-29 16:07:45 (Thread=1080) TransactionId: 7911930135428526585
2015-06-29 16:07:45 (Thread=1080) TransactionId: 13099645207909320632
2015-06-29 16:07:46 (Thread=1080) TransactionId: 12317523322023186267
2015-06-29 16:07:46 (Thread=1080) TransactionId: 14753691699400837697
2015-06-29 16:07:46 (Thread=1080) TransactionId: 14942617828648985981
2015-06-29 16:07:47 (Thread=1080) TransactionId: 4197012346658445842
2015-06-29 16:07:47 (Thread=1080) TransactionId: 13826898100355093203
2015-06-29 16:07:47 (Thread=1080) TransactionId: 12466519622063987382
2015-06-29 16:07:48 (Thread=1080) TransactionId: 6680931011404636915
2015-06-29 16:07:48 (Thread=1080) TransactionId: 10637597664539240073
2015-06-29 16:07:48 (Thread=1080) TransactionId: 16602028918194697665
2015-06-29 16:07:48 (Thread=1080) TransactionId: 2800924054339262515
2015-06-29 16:07:49 (Thread=1080) TransactionId: 12438942460590434606
2015-06-29 16:07:49 (Thread=1080) TransactionId: 16248075742165105879
2015-06-29 16:07:49 (Thread=1080) TransactionId: 7271683506438058503
2015-06-29 16:07:50 (Thread=1080) TransactionId: 8242657180871902929
2015-06-29 16:07:51 (Thread=1080) TransactionId: 9749964425644213040
2015-06-29 16:07:51 (Thread=1080) TransactionId: 18443851720758155155
2015-06-29 16:07:51 (Thread=1080) TransactionId: 3411919803373339000
2015-06-29 16:07:52 (Thread=1080) TransactionId: 4407819111309240263
2015-06-29 16:07:52 (Thread=1080) TransactionId: 16954791815390290362
2015-06-29 16:07:52 (Thread=1080) TransactionId: 8452531928444185071
2015-06-29 16:07:52 (Thread=1080) TransactionId: 17117128055745546700
2015-06-29 16:07:53 (Thread=1080) TransactionId: 11836631455361436165
2015-06-29 16:07:53 (Thread=1080) TransactionId: 2346549748424240479
2015-06-29 16:07:53 (Thread=1080) TransactionId: 8628968470714802016
2015-06-29 16:07:54 (Thread=1080) TransactionId: 5698313210504961731
2015-06-29 16:07:54 (Thread=1080) TransactionId: 12822905520365011352
2015-06-29 16:07:54 (Thread=1080) TransactionId: 726764292457218381
2015-06-29 16:07:55 (Thread=1080) TransactionId: 18145237966982434288
2015-06-29 16:07:55 (Thread=1080) TransactionId: 3404402719330122763
2015-06-29 16:07:55 (Thread=1080) TransactionId: 8536754961937249942
2015-06-29 16:07:55 (Thread=1080) TransactionId: 6306291318381747692
2015-06-29 16:07:56 (Thread=1080) TransactionId: 17902003263486409819
2015-06-29 16:07:56 (Thread=1080) TransactionId: 6652266921376769455
2015-06-29 16:07:56 (Thread=1080) TransactionId: 583536928162772584
2015-06-29 16:07:57 (Thread=1080) TransactionId: 12274181767874750431
2015-06-29 16:07:57 (Thread=1080) TransactionId: 3184570255845567238
2015-06-29 16:07:57 (Thread=1080) TransactionId: 12081769436433472190
2015-06-29 16:07:57 (Thread=1080) TransactionId: 9302714603790074066
2015-06-29 16:07:58 (Thread=1080) TransactionId: 16147289603215998325
2015-06-29 16:07:58 (Thread=1080) TransactionId: 1034647406216281249
2015-06-29 16:07:58 (Thread=1080) TransactionId: 7754646689635212677
2015-06-29 16:07:59 (Thread=1080) TransactionId: 16233583735351383474
2015-06-29 16:07:59 (Thread=1080) About to load 2501 documents.
2015-06-29 16:07:59 (Thread=1080) TransactionId: 9583633161924597210
2015-06-29 16:07:59 (Thread=1080) TransactionId: 9338705339246018356
2015-06-29 16:07:59 (Thread=1080) TransactionId: 4868068419385906616
2015-06-29 16:08:00 (Thread=1080) TransactionId: 9454307110631482403
2015-06-29 16:08:00 (Thread=1080) TransactionId: 8901082008472097055
2015-06-29 16:10:00 (Thread=1080) com.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 60 retries
com.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 60 retries
    at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3506)
    at com.marklogic.client.impl.JerseyServices.postBulkDocuments(JerseyServices.java:3594)
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:552)
    at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
    at test.stress.JavaAPISession.putDocuments(JavaAPISession.java:284)
    at test.stress.BulkLoadTester.finishBatch(BulkLoadTester.java:47)
    at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:197)
    at test.stress.RestLoadTester.runTest(RestLoadTester.java:278)
    at test.stress.StressTest.run(StressTest.java:94)

2015-06-29 16:10:00 (Thread=1080) TransactionId: 17194200032422650940
2015-06-29 16:10:01 (Thread=1080) TransactionId: 3431335264558434817
2015-06-29 16:10:01 (Thread=1080) TransactionId: 4369004385664767797
2015-06-29 16:10:01 (Thread=1080) TransactionId: 2866214012734010396
2015-06-29 16:10:02 (Thread=1080) TransactionId: 3096587228643108715
2015-06-29 16:10:02 (Thread=1080) TransactionId: 17398544717691902625
2015-06-29 16:10:02 (Thread=1080) TransactionId: 338788105602082676
2015-06-29 16:10:03 (Thread=1080) TransactionId: 18436747142204906936
2015-06-29 16:10:03 (Thread=1080) TransactionId: 7260147259781715078
2015-06-29 16:10:03 (Thread=1080) TransactionId: 5301601477942474876
2015-06-29 16:10:04 (Thread=1080) TransactionId: 6094415726872403587
2015-06-29 16:10:04 (Thread=1080) TransactionId: 4998426169036013743
2015-06-29 16:10:04 (Thread=1080) TransactionId: 7412285264017278751
2015-06-29 16:10:05 (Thread=1080) TransactionId: 6668457195864179197
2015-06-29 16:10:05 (Thread=1080) TransactionId: 11267386546945768927
2015-06-29 16:10:05 (Thread=1080) TransactionId: 16403725208031004514
2015-06-29 16:10:06 (Thread=1080) TransactionId: 9968400658826332922
2015-06-29 16:10:06 (Thread=1080) TransactionId: 15246383198750724501
2015-06-29 16:10:06 (Thread=1080) TransactionId: 3337419774391293758
2015-06-29 16:10:07 (Thread=1080) TransactionId: 10900974523103066158
2015-06-29 16:10:07 (Thread=1080) TransactionId: 1972959381639095273
2015-06-29 16:10:07 (Thread=1080) TransactionId: 16556275118266384695
2015-06-29 16:10:08 (Thread=1080) TransactionId: 6937057450187908633
2015-06-29 16:10:08 (Thread=1080) TransactionId: 5607576376032092201
2015-06-29 16:10:08 (Thread=1080) TransactionId: 16404488736008131995
2015-06-29 16:10:09 (Thread=1080) TransactionId: 2979114215741429233
2015-06-29 16:10:09 (Thread=1080) TransactionId: 17533239350375423320
2015-06-29 16:10:09 (Thread=1080) TransactionId: 10322177326694128753
2015-06-29 16:10:10 (Thread=1080) TransactionId: 877068914050879540
2015-06-29 16:10:10 (Thread=1080) TransactionId: 1479002360321248053
2015-06-29 16:10:10 (Thread=1080) TransactionId: 15044274679959061148
2015-06-29 16:10:11 (Thread=1080) TransactionId: 7172748967119003373
2015-06-29 16:10:11 (Thread=1080) TransactionId: 12863482600537643550
2015-06-29 16:10:11 (Thread=1080) TransactionId: 17794779538568207772
2015-06-29 16:10:11 (Thread=1080) TransactionId: 816069255615155172
2015-06-29 16:10:12 (Thread=1080) TransactionId: 1796309294560349412
2015-06-29 16:10:12 (Thread=1080) TransactionId: 2579257041828367372
2015-06-29 16:10:13 (Thread=1080) TransactionId: 12391744891260654719
2015-06-29 16:10:13 (Thread=1080) TransactionId: 16340022443753169974
2015-06-29 16:10:13 (Thread=1080) TransactionId: 2789297497601529267
2015-06-29 16:10:14 (Thread=1080) TransactionId: 9298635508141238542
2015-06-29 16:10:14 (Thread=1080) TransactionId: 1990082472904211967
2015-06-29 16:10:14 (Thread=1080) TransactionId: 15760811766969043487
2015-06-29 16:10:14 (Thread=1080) TransactionId: 13924363916680969794
2015-06-29 16:10:15 (Thread=1080) TransactionId: 340769915781105308
2015-06-29 16:10:15 (Thread=1080) TransactionId: 8418547821096062762
2015-06-29 16:10:15 (Thread=1080) About to load 2501 documents.
2015-06-29 16:10:15 (Thread=1080) TransactionId: 9957562701428298437
2015-06-29 16:10:15 (Thread=1080) TransactionId: 5790197639622230169
2015-06-29 16:10:16 (Thread=1080) TransactionId: 11782949107466878489
2015-06-29 16:10:16 (Thread=1080) TransactionId: 5574798358065019992
2015-06-29 16:10:16 (Thread=1080) TransactionId: 1246011827334113145
2015-06-29 16:10:17 (Thread=1080) TransactionId: 14538575589107732205
2015-06-29 16:10:17 (Thread=1080) TransactionId: 5931560904765289599
2015-06-29 16:10:17 (Thread=1080) TransactionId: 13159245066380358367
2015-06-29 16:10:17 (Thread=1080) TransactionId: 15768734985874518062
2015-06-29 16:10:18 (Thread=1080) TransactionId: 3529841287948573979
2015-06-29 16:10:18 (Thread=1080) TransactionId: 5864625210032882986
2015-06-29 16:10:18 (Thread=1080) TransactionId: 7155723752122348627
2015-06-29 16:10:19 (Thread=1080) TransactionId: 1653545312695504973
2015-06-29 16:10:19 (Thread=1080) TransactionId: 1886423659362346405
2015-06-29 16:10:19 (Thread=1080) TransactionId: 14017241504373363756
2015-06-29 16:10:20 (Thread=1080) TransactionId: 17279433947820916952
2015-06-29 16:10:20 (Thread=1080) TransactionId: 6847745729839880452
2015-06-29 16:10:20 (Thread=1080) TransactionId: 14643612550860110235
2015-06-29 16:10:20 (Thread=1080) TransactionId: 10847761048367757108
2015-06-29 16:10:21 (Thread=1080) TransactionId: 5520293062260912366
2015-06-29 16:10:21 (Thread=1080) TransactionId: 5143257622688035034
2015-06-29 16:10:21 (Thread=1080) TransactionId: 221276570356381142
2015-06-29 16:10:22 (Thread=1080) TransactionId: 7040015963697447715
2015-06-29 16:10:22 (Thread=1080) TransactionId: 1786744422522891529
2015-06-29 16:10:22 (Thread=1080) TransactionId: 11505263588834316245
2015-06-29 16:10:22 (Thread=1080) TransactionId: 15600622944498140477
2015-06-29 16:10:23 (Thread=1080) TransactionId: 909391396086830047
2015-06-29 16:10:23 (Thread=1080) TransactionId: 17676155274433467729
2015-06-29 16:10:23 (Thread=1080) TransactionId: 12641407439920323698
2015-06-29 16:10:24 (Thread=1080) TransactionId: 2304083615009592503
2015-06-29 16:10:24 (Thread=1080) TransactionId: 8261343917809715786
2015-06-29 16:10:24 (Thread=1080) TransactionId: 10753587762962525631
2015-06-29 16:10:24 (Thread=1080) TransactionId: 9310802275286107081
2015-06-29 16:10:25 (Thread=1080) TransactionId: 6321620796821289167
2015-06-29 16:10:25 (Thread=1080) TransactionId: 6092871963878911
2015-06-29 16:10:25 (Thread=1080) TransactionId: 290318031823672154
2015-06-29 16:10:26 (Thread=1080) TransactionId: 10697588729955750069
2015-06-29 16:10:26 (Thread=1080) TransactionId: 15288985800626562804
2015-06-29 16:10:27 (Thread=1080) TransactionId: 2970755218423553111
2015-06-29 16:10:27 (Thread=1080) TransactionId: 14968781366791255610
2015-06-29 16:10:27 (Thread=1080) TransactionId: 16863101838405120602
2015-06-29 16:10:28 (Thread=1080) TransactionId: 5158881216655668455
2015-06-29 16:10:28 (Thread=1080) TransactionId: 12771317836086981148
2015-06-29 16:10:28 (Thread=1080) TransactionId: 272878195315242517
2015-06-29 16:10:28 (Thread=1080) TransactionId: 9518735429595158690
2015-06-29 16:10:29 (Thread=1080) TransactionId: 14599711126971351254
2015-06-29 16:10:29 (Thread=1080) TransactionId: 6060276184583125338
2015-06-29 16:10:29 (Thread=1080) TransactionId: 10312876131287493305
2015-06-29 16:10:30 (Thread=1080) TransactionId: 17077864695170453113
2015-06-29 16:10:30 (Thread=1080) TransactionId: 5639844667643446454
2015-06-29 16:10:30 (Thread=1080) TransactionId: 4482824513975361256
2015-06-29 16:10:30 (Thread=1080) Test took: 196516ms

**Comment by georgeajit** [comment]
I still see these exceptions in 9.0 EA 1 ML Server Build / Java Client API 4.0 stress environment.

**Comment by sammefford** [comment]
Ajit, when did the D-node go down?  This shows the error at 16:10 and the thread retries started at 16:08.

**Comment by sammefford** [comment]
And when did the D-node start coming back online?  When did it finish coming back online?

**Comment by sammefford** [comment]
I took a close look at this today.  I'm sure this isn't an error in the Java layer so I'll close this.  This appears to me to either be an error in the rewriter or in multi-request transactions.  I opened https://bugtrack.marklogic.com/bug/38581 so the server team can address this.
