### ISSUE TITLE
Stress Test  Exception - Transaction commit / rollback failed  at times when D Node goes down

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#316]
When a D Node goes down the Java program that loads documents logs the following exceptions for bothe transaction commit and rollbacks.

Here is the log for Thread 677

2015-06-29 14:59:56 (Thread=677) ========
Starting test with uniqueURI = /GBLGAQGDAINMDRKR/201552914595650/1/
# 

TestcaseID = bulkLoadTester
ThreadID = 677
BinaryTest = false
JSONTest = false
InsertTime = false
NumberOfLoops = 5
MaxSleepTime = 1
LogOption = debug
WriteToScreen = true
LogFilename = auto
OutputFileName =

2015-06-29 14:59:56 (Thread=677) About to load 2501 documents.
2015-06-29 14:59:56 (Thread=677) TransactionId: 16065772584398336078
2015-06-29 14:59:56 (Thread=677) TransactionId: 15626179429712241317

...
...

2015-06-29 15:00:02 (Thread=677) com.marklogic.client.FailedRequestException: Local message: transaction commit failed: Bad Request. Server Message: XDMP-NOTXN: xdmp:xa-complete1(xs:unsignedLong("17363436230307622588"), xs:unsignedLong("1834030360301969335"), fn:true()) -- No transaction with identifier 1834030360301969335
com.marklogic.client.FailedRequestException: Local message: transaction commit failed: Bad Request. Server Message: XDMP-NOTXN: xdmp:xa-complete1(xs:unsignedLong("17363436230307622588"), xs:unsignedLong("1834030360301969335"), fn:true()) -- No transaction with identifier 1834030360301969335
    at com.marklogic.client.impl.JerseyServices.completeTransaction(JerseyServices.java:1706)
    at com.marklogic.client.impl.JerseyServices.commitTransaction(JerseyServices.java:1632)
    at com.marklogic.client.impl.TransactionImpl.commit(TransactionImpl.java:74)
    at test.stress.JavaAPISession.commitTransaction(JavaAPISession.java:129)
    at test.stress.RestLoadTester.commitRestTransaction(RestLoadTester.java:77)
    at test.stress.BulkLoadTester.finishBatch(BulkLoadTester.java:50)
    at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:197)
    at test.stress.RestLoadTester.runTest(RestLoadTester.java:278)
    at test.stress.StressTest.run(StressTest.java:94)
2015-06-29 15:00:02 (Thread=677) com.marklogic.client.FailedRequestException: Local message: transaction rollback failed: Bad Request. Server Message: XDMP-NOTXN: xdmp:xa-complete1(xs:unsignedLong("17363436230307622588"), xs:unsignedLong("1834030360301969335"), fn:false()) -- No transaction with identifier 1834030360301969335
com.marklogic.client.FailedRequestException: Local message: transaction rollback failed: Bad Request. Server Message: XDMP-NOTXN: xdmp:xa-complete1(xs:unsignedLong("17363436230307622588"), xs:unsignedLong("1834030360301969335"), fn:false()) -- No transaction with identifier 1834030360301969335
    at com.marklogic.client.impl.JerseyServices.completeTransaction(JerseyServices.java:1706)
    at com.marklogic.client.impl.JerseyServices.rollbackTransaction(JerseyServices.java:1638)
    at com.marklogic.client.impl.TransactionImpl.rollback(TransactionImpl.java:79)
    at test.stress.JavaAPISession.rollbackTransaction(JavaAPISession.java:137)
    at test.stress.RestLoadTester.rollbackRestTransaction(RestLoadTester.java:83)
    at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:237)
    at test.stress.RestLoadTester.runTest(RestLoadTester.java:278)
    at test.stress.StressTest.run(StressTest.java:94)
2015-06-29 15:00:02 (Thread=677) TransactionId: 17129907621398505719
Entering int  endFinishedTests()

...
...

2015-06-29 15:03:04 (Thread=677) TransactionId: 2718635990176040848
2015-06-29 15:03:04 (Thread=677) TransactionId: 18286127724636132896
2015-06-29 15:03:05 (Thread=677) TransactionId: 2798161321207930140
2015-06-29 15:03:05 (Thread=677) TransactionId: 5249236011309410786
2015-06-29 15:03:05 (Thread=677) TransactionId: 6696853871857275008
2015-06-29 15:03:06 (Thread=677) TransactionId: 17436886326540886145
2015-06-29 15:03:06 (Thread=677) TransactionId: 18274234655679258502
2015-06-29 15:03:06 (Thread=677) Test took: 190483ms

**Comment by georgeajit** [comment]
I still see these exceptions in 9.0 EA 1 ML Server Build / Java Client API 4.0 stress environment.

**Comment by sammefford** [comment]
I was thinking this is expected behavior.  A transaction is tied to a host.  If that host goes down, there's no way to recover the transaction and the transaction will fail.  But then I realized the host we're communicating with (the e-node) isn't going down here, it's a d-node that goes down.  I'll double-check whether a downed d-node should affect a transaction.

**Comment by sammefford** [comment]
I confirmed that this should not happen.  A D-node failure and failover should not affect a transaction other than delays which might cause a timeout.  This is happening directly after the d-node fails, so this should not be happening.

**Comment by sammefford** [comment]
I went onto the server you pointed me to, and I can't see any XDMP-NOTXN errors either in the /tmp/place*.out files or /space/wire-trace-logs/*.  Can you let me know when you next see this?

**Comment by georgeajit** [comment]
This happens when transactions around the time d node goes down. Will need to run stress test again.

**Comment by sammefford** [comment]
Ok, I now have an isolated case of this in the logs.  I see a transaction start at 16:00:01,868:

```
2016-03-22 16:00:01,868 (Thread-1105) >> "POST /v1/transactions?database=MedlineDB HTTP/1.1[\r][\n]"
2016-03-22 16:00:01,868 (Thread-1105) >> "Authorization: Digest username="admin",realm="public",nonce="f9d7d36ec5ca998cb2d42f90285464c0",opaque="c39b7d2ec04576c2",qop=auth,uri="/v1/transactions",cnonce="4ebe9e24",nc=00001a7d,response="b99c250a5ad6e5af9e1448e2caf2cb15"[\r][\n]"
2016-03-22 16:00:01,868 (Thread-1105) >> "Content-Length: 0[\r][\n]"
2016-03-22 16:00:01,868 (Thread-1105) >> "Host: rh7v-intel64-90-xa-stress-1:8011[\r][\n]"
2016-03-22 16:00:01,868 (Thread-1105) >> "Connection: Keep-Alive[\r][\n]"
2016-03-22 16:00:01,868 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,871 (Thread-1105) << "HTTP/1.1 303 See Created Transaction[\r][\n]"
2016-03-22 16:00:01,871 (Thread-1105) << "Set-Cookie: HostId=12821138310871992001[\r][\n]"
2016-03-22 16:00:01,871 (Thread-1105) << "Location: /v1/transactions/2359044135675102871[\r][\n]"
2016-03-22 16:00:01,871 (Thread-1105) << "Server: MarkLogic[\r][\n]"
2016-03-22 16:00:01,871 (Thread-1105) << "Content-Length: 0[\r][\n]"
2016-03-22 16:00:01,871 (Thread-1105) << "Connection: Keep-Alive[\r][\n]"
2016-03-22 16:00:01,871 (Thread-1105) << "Keep-Alive: timeout=5[\r][\n]"
2016-03-22 16:00:01,871 (Thread-1105) << "[\r][\n]"
```

Then it writes several documents in the transaction like the following example:

```
2016-03-22 16:00:01,872 (Thread-1105) >> "PUT /v1/documents?database=MedlineDB&txid=2359044135675102871&category=content&category=collections&uri=/GNXZSRDMSLXMCZJQ/201622215590996/16/1doc-2385.xml HTTP/1.1[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "Cookie: HostId=12821138310871992001;Version=1[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "Content-Type: multipart/mixed; boundary=Boundary_9538612_153329287_1458687601871[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "Authorization: Digest username="admin",realm="public",nonce="f9d7d36ec5ca998cb2d42f90285464c0",opaque="c39b7d2ec04576c2",qop=auth,uri="/v1/documents",cnonce="b626a468",nc=00001a7e,response="dfdae9ff639d52e940d0812ef17711d5"[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "Transfer-Encoding: chunked[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "Host: rh7v-intel64-90-xa-stress-1:8011[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "Connection: Keep-Alive[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "4d[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "--Boundary_9538612_153329287_1458687601871[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "Content-Type: application/xml[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "10d[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "<?xml version="1.0" encoding="utf-8"?><rapi:metadata xmlns:rapi="http://marklogic.com/rest-api" xmlns:prop="http://marklogic.com/xdmp/property"><rapi:collections><rapi:collection>/GNXZSRDMSLXMCZJQ/201622215590996/16/</rapi:collection></rapi:collections></rapi:metadata>"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "4f[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "--Boundary_9538612_153329287_1458687601871[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "Content-Type: application/xml[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "733[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "<root><document>2189</document><frag><qa:int-1 qa:value="4078" xmlns:qa="http://marklogic.com/qa">4078</qa:int-1><qa:uint-1 qa:value="3169" xmlns:qa="http://marklogic.com/qa">3169</qa:uint-1><qa:long-1 qa:value="5828" xmlns:qa="http://marklogic.com/qa">5828</qa:long-1><qa:ulong-1 qa:value="5987" xmlns:qa="http://marklogic.com/qa">5987</qa:ulong-1><qa:float-1 qa:value="923.129" xmlns:qa="http://marklogic.com/qa">923.129</qa:float-1><qa:double-1 qa:value="65097.094017094" xmlns:qa="http://marklogic.com/qa">65097.094017094</qa:double-1><qa:decimal-1 qa:value="373048.181818182" xmlns:qa="http://marklogic.com/qa">373048.181818182</qa:decimal-1><qa:datetime-1 qa:value="1961-10-02T03:36:56" xmlns:qa="http://marklogic.com/qa">1961-10-02T03:36:56</qa:datetime-1><qa:time-1 qa:value="10:37:26" xmlns:qa="http://marklogic.com/qa">10:37:26</qa:time-1><qa:date-1 qa:value="1658-03-19" xmlns:qa="http://marklogic.com/qa">1658-03-19</qa:date-1><qa:gyearmonth-1 qa:value="1951-05" xmlns:qa="http://marklogic.com/qa">1951-05</qa:gyearmonth-1><qa:gyear-1 qa:value="2036" xmlns:qa="http://marklogic.com/qa">2036</qa:gyear-1><qa:gmonth-1 qa:value="--08" xmlns:qa="http://marklogic.com/qa">--08</qa:gmonth-1><qa:gday-1 qa:value="---01" xmlns:qa="http://marklogic.com/qa">---01</qa:gday-1><qa:yearmonthduration-1 qa:value="P54Y4M" xmlns:qa="http://marklogic.com/qa">P54Y4M</qa:yearmonthduration-1><qa:daytimeduration-1 qa:value="P27DT19H27M6S" xmlns:qa="http://marklogic.com/qa">P27DT19H27M6S</qa:daytimeduration-1><qa:string-1 qa:value="Enable extensible functionalities" xmlns:qa="http://marklogic.com/qa">Enable extensible functionalities</qa:string-1><qa:anyuri-1 qa:value="nfs://yahoo.com/fleeble/foo.xqy" xmlns:qa="http://marklogic.com/qa">nfs://yahoo.com/fleeble/foo.xqy</qa:anyuri-1></frag></root>[\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "--Boundary_9538612_153329287_1458687601871--[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "0[\r][\n]"
2016-03-22 16:00:01,872 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:01,880 (Thread-1105) << "HTTP/1.1 201 Created[\r][\n]"
2016-03-22 16:00:01,880 (Thread-1105) << "Set-Cookie: HostId=12821138310871992001[\r][\n]"
2016-03-22 16:00:01,880 (Thread-1105) << "Location: /v1/documents?uri=/GNXZSRDMSLXMCZJQ/201622215590996/16/1doc-2385.xml[\r][\n]"
2016-03-22 16:00:01,880 (Thread-1105) << "Server: MarkLogic[\r][\n]"
2016-03-22 16:00:01,880 (Thread-1105) << "Content-Length: 0[\r][\n]"
2016-03-22 16:00:01,880 (Thread-1105) << "Connection: Keep-Alive[\r][\n]"
2016-03-22 16:00:01,880 (Thread-1105) << "Keep-Alive: timeout=5[\r][\n]"
2016-03-22 16:00:01,880 (Thread-1105) << "[\r][\n]"
```

But when it tries to commit the transaction suddenly the transaction isn't there.  I'm also including the response to the previous write showing that the transaction was supposedly there 13 ms earlier:

```
2016-03-22 16:00:02,003 (Thread-1105) << "HTTP/1.1 201 Created[\r][\n]"
2016-03-22 16:00:02,003 (Thread-1105) << "Set-Cookie: HostId=12821138310871992001[\r][\n]"
2016-03-22 16:00:02,003 (Thread-1105) << "Location: /v1/documents?uri=/GNXZSRDMSLXMCZJQ/201622215590996/16/1doc-1831.xml[\r][\n]"
2016-03-22 16:00:02,003 (Thread-1105) << "Server: MarkLogic[\r][\n]"
2016-03-22 16:00:02,003 (Thread-1105) << "Content-Length: 0[\r][\n]"
2016-03-22 16:00:02,003 (Thread-1105) << "Connection: Keep-Alive[\r][\n]"
2016-03-22 16:00:02,003 (Thread-1105) << "Keep-Alive: timeout=5[\r][\n]"
2016-03-22 16:00:02,003 (Thread-1105) << "[\r][\n]"
2016-03-22 16:00:02,004 (Thread-1105) >> "POST /v1/transactions/2359044135675102871?result=commit HTTP/1.1[\r][\n]"
2016-03-22 16:00:02,004 (Thread-1105) >> "Cookie: HostId=12821138310871992001;Version=1[\r][\n]"
2016-03-22 16:00:02,004 (Thread-1105) >> "Authorization: Digest username="admin",realm="public",nonce="f9d7d36ec5ca998cb2d42f90285464c0",opaque="c3
9b7d2ec04576c2",qop=auth,uri="/v1/transactions/2359044135675102871",cnonce="b2ec8b56",nc=00001a88,response="aa77b8ff90b98f16756305b3bbad9964"[\r][\
n]"
2016-03-22 16:00:02,005 (Thread-1105) >> "Content-Length: 0[\r][\n]"
2016-03-22 16:00:02,005 (Thread-1105) >> "Host: rh7v-intel64-90-xa-stress-1:8011[\r][\n]"
2016-03-22 16:00:02,005 (Thread-1105) >> "Connection: Keep-Alive[\r][\n]"
2016-03-22 16:00:02,005 (Thread-1105) >> "[\r][\n]"
2016-03-22 16:00:02,216 (Thread-1105) << "HTTP/1.1 400 Bad Request[\r][\n]"
2016-03-22 16:00:02,216 (Thread-1105) << "Content-type: application/json; charset=UTF-8[\r][\n]"
2016-03-22 16:00:02,216 (Thread-1105) << "Server: MarkLogic[\r][\n]"
2016-03-22 16:00:02,216 (Thread-1105) << "Content-Length: 281[\r][\n]"
2016-03-22 16:00:02,216 (Thread-1105) << "Connection: Keep-Alive[\r][\n]"
2016-03-22 16:00:02,216 (Thread-1105) << "Keep-Alive: timeout=5[\r][\n]"
2016-03-22 16:00:02,216 (Thread-1105) << "[\r][\n]"
2016-03-22 16:00:02,216 (Thread-1105) << "{"errorResponse":{"statusCode":400, "status":"Bad Request", "messageCode":"XDMP-NOTXN", "message":"XDMP-N
OTXN: xdmp:xa-complete1(xs:unsignedLong(\"12821138310871992001\"), xs:unsignedLong(\"2359044135675102871\"), fn:true()) -- No transaction with iden
tifier 2359044135675102871"}}"
```

**Comment by sammefford** [comment]
Ganesh, I don't see anything we can do at the Java or REST layers to resolve this.  Can you please help me identify the server engineer who should take this to the next step?  I presume they'll want Ajit's help getting some trace logs or something.

As with most stress test issues we've seen I have no simple way to duplicate the issue.  This doesn't even occur every time we run the stress test let alone every time the d-node goes drops then recovers.  I only see this once in the three hour stress test where Ajit saw it most recently.

**Comment by georgeajit** [comment]
Did see the same error on 9.0 EA3 Java Client API Stress Test. Here is the Stress Test result:
08/19: Completed 3+ hrs of run. Git Issues not fixed yet.  316, 416, 449. Server logs are fine.

This is the client log that contains the same error.
```
2016-08-19 10:00:02 (Thread=72) TransactionId: 591010866374244861
2016-08-19 10:00:02 (Thread=72) com.marklogic.client.FailedRequestException: Local message: transaction commit failed: Bad Request. Server Message: XDMP-NOTXN: xdmp:xa-complete1(xs:unsignedLong("16485443894496730293"), xs:unsignedLong("591010866374244861"), fn:true()) -- No transaction with identifier 591010866374244861
com.marklogic.client.FailedRequestException: Local message: transaction commit failed: Bad Request. Server Message: XDMP-NOTXN: xdmp:xa-complete1(xs:unsignedLong("16485443894496730293"), xs:unsignedLong("591010866374244861"), fn:true()) -- No transaction with identifier 591010866374244861
    at com.marklogic.client.impl.JerseyServices.completeTransaction(JerseyServices.java:1618)
    at com.marklogic.client.impl.JerseyServices.commitTransaction(JerseyServices.java:1575)
    at com.marklogic.client.impl.TransactionImpl.commit(TransactionImpl.java:100)
    at test.stress.JavaAPISession.commitTransaction(JavaAPISession.java:144)
    at test.stress.RestLoadTester.commitRestTransaction(RestLoadTester.java:77)
    at test.stress.RestLoadTester.finishBatch(RestLoadTester.java:257)
    at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:197)
    at test.stress.RestLoadTester.runTest(RestLoadTester.java:278)
    at test.stress.StressTest.run(StressTest.java:138)
2016-08-19 10:00:02 (Thread=72) com.marklogic.client.FailedRequestException: Local message: transaction rollback failed: Bad Request. Server Message: XDMP-NOTXN: xdmp:xa-complete1(xs:unsignedLong("16485443894496730293"), xs:unsignedLong("591010866374244861"), fn:false()) -- No transaction with identifier 591010866374244861
com.marklogic.client.FailedRequestException: Local message: transaction rollback failed: Bad Request. Server Message: XDMP-NOTXN: xdmp:xa-complete1(xs:unsignedLong("16485443894496730293"), xs:unsignedLong("591010866374244861"), fn:false()) -- No transaction with identifier 591010866374244861
    at com.marklogic.client.impl.JerseyServices.completeTransaction(JerseyServices.java:1618)
    at com.marklogic.client.impl.JerseyServices.rollbackTransaction(JerseyServices.java:1581)
    at com.marklogic.client.impl.TransactionImpl.rollback(TransactionImpl.java:105)
    at test.stress.JavaAPISession.rollbackTransaction(JavaAPISession.java:152)
    at test.stress.RestLoadTester.rollbackRestTransaction(RestLoadTester.java:83)
    at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:237)
    at test.stress.RestLoadTester.runTest(RestLoadTester.java:278)
    at test.stress.StressTest.run(StressTest.java:138)
2016-08-19 10:00:02 (Thread=72) TransactionId: 3722542330177416009
Deleting user 16
pos[0] alive:  restloadtester (/space/HEAD/qa/stress/widowmaker/loadtests/restLoadTester_noTransactions.xml)
```
