### ISSUE TITLE
Method executeConstruct withMimetype N3 as output produces ForbiddenUserException

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#337]
While trying to generate triples of N3 format from a . NT file using executeConstruct method, there is a ForbiddenUserException thrown on the client.
The test case runs fine if N3 is not used.

Input file used: foaf1.nt is available the test-complete project in the semantics/data folder. The contents of this file was loaded into a database in the setUp.

Here is the test case:

SetUp Method : 
public static void setUp() throws Exception
	{
		System.out.println("In SPARQL Query Manager Test setup");
		newline = System.getProperty("line.separator");
		setupJavaRESTServer(dbName, fNames[0], restServerName,8011);
		enableCollectionLexicon(dbName);
		enableTripleIndex(dbName);
		Thread.sleep(10000);
		//You can enable the triple positions index for faster near searches using cts:triple-range-query.
		writeclient = DatabaseClientFactory.newClient("localhost", restPort,
				"rest-writer", "x", Authentication.DIGEST);
		readclient = DatabaseClientFactory.newClient("localhost", restPort,
				"rest-reader", "x", Authentication.DIGEST);
		client = DatabaseClientFactory.newClient("localhost", restPort, "rest-admin", "x", Authentication.DIGEST);
		
		//Insert the required Graphs and triples for most of all the tests.
		
		//NTRIPLES   "application/n-triples"
		writeSPARQLDocumentUsingFileHandle(writeclient, "src/test/java/com/marklogic/client/functionaltest/data/semantics/",
				                             "foaf1.nt", "http://marklogic.com/qatests/ntriples/", null, RDFMimeTypes.NTRIPLES);
}

Test case:
========
/* This test checks a SPARQL construct query results.
	 * The database should contain triples from foaf1.nt file. 
	 * Results are returned in a sequence of sem:triple values as triples in memory.
	 * 
	 * The query should be returning one result.
     * 
     * Uses StringHandle (TriplesReadHandle)
	 * 
	 */
	@Test
	public void testExecuteConstructInTransaction() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testExecuteConstructInTransaction method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		Transaction t = writeclient.openTransaction();

		StringBuffer sparqlQuery = new StringBuffer().append(" PREFIX foaf: <http://xmlns.com/foaf/0.1/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("CONSTRUCT {<http://www.ucsb.edu/random-alum> foaf:knows ?alum }");
		sparqlQuery.append(newline);
		sparqlQuery.append("where");
		sparqlQuery.append(newline);
		sparqlQuery.append("{ ?alum foaf:schoolHomepage <http://www.ucsb.edu/> }");		
		
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(sparqlQuery.toString());
		// Execute Construct query 	with RDFMimeTypes.NTRIPLES	
		String[] jsonResults = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.NTRIPLES), t).get().split(" ");
		
		// Account for the dot at the end of the triple. Hence size is 4.
		assertEquals("Method testExecuteConstructInTransaction in-memory Triple part size is incorrect", 4, jsonResults.length);
		assertEquals("Method testExecuteConstructInTransaction in-memory subject is incorrect", "<http://www.ucsb.edu/random-alum>", jsonResults[0]);
		assertEquals("Method testExecuteConstructInTransaction in-memory predicate is incorrect", "<http://xmlns.com/foaf/0.1/knows>", jsonResults[1]);
		assertEquals("Method testExecuteConstructInTransaction in-memory object is incorrect", "<1bfbfb8:ff2d706919:-7fa9>", jsonResults[2]);		
		
		// Add tests for additional MIME Type.
		// Execute Construct query 	with RDFMimeTypes.NTRIPLES
		
		String strN3 = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.N3), t).get().toString();
		System.out.println("strN3 " + strN3);
		System.out.println("\n===========================");
		String strRDFJSON = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.RDFJSON), t).get().toString();
		System.out.println("strRDFJSON " + strRDFJSON);
		System.out.println("\n===========================");
		// [{"http://www.ucsb.edu/random-alum":{"http://xmlns.com/foaf/0.1/knows":[{"value":"1bfbfb8:ff2d706919:-7fa9",, "type":"uri"}]}}]
		String strRDFXML = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.RDFXML), t).get().toString();
		System.out.println("strRDFXML " + strRDFXML);
		System.out.println("\n===========================");

		String strTRIPLEXML = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.TRIPLEXML), t).get().toString();
		System.out.println("strTRIPLEXML " + strTRIPLEXML);
		System.out.println("\n===========================");
		String strTURTLE = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.TURTLE), t).get().toString();
		System.out.println("strTURTLE " + strTURTLE);
		System.out.println("\n===========================");
		
		// Handle the transaction.
		t.commit();
	}

Here is the stack trace:
com.marklogic.client.ForbiddenUserException: Local message: User is not allowed to apply resource at /graphs/sparql. Server Message: You do not have permission to this method and URL.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4594)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3494)
	at com.marklogic.client.impl.JerseyServices.executeSparql(JerseyServices.java:5614)
	at com.marklogic.client.impl.SPARQLQueryManagerImpl.executeQueryImpl(SPARQLQueryManagerImpl.java:88)
	at com.marklogic.client.impl.SPARQLQueryManagerImpl.executeQueryImpl(SPARQLQueryManagerImpl.java:81)
	at com.marklogic.client.impl.SPARQLQueryManagerImpl.executeConstruct(SPARQLQueryManagerImpl.java:102)
	at com.marklogic.client.functionaltest.TestBasicSemanticsSparql.testExecuteConstructInTransaction(TestBasicSemanticsSparql.java:472)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by sammefford** [comment]
I can reproduce this in the underlying REST layer.  I logged bug 35028 against it.  I'm going to close this as I don't see anything I can do about it in the Java layer.
