### ISSUE TITLE
SemanticsPermissionsTest.E_testMergePermissions unit test fails

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#350]
Here is the console and Error message output from the unit test:
Error Message

Local message: failed to apply resource at graphs: Bad Request. Server Message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: Cannot combine perm:* parameters for /v1/graphs with a permissions body

Stacktrace

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at graphs: Bad Request. Server Message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: Cannot combine perm:* parameters for /v1/graphs with a permissions body
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4596)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3492)
	at com.marklogic.client.impl.JerseyServices.mergePermissions(JerseyServices.java:5472)
	at com.marklogic.client.impl.GraphManagerImpl.mergePermissions(GraphManagerImpl.java:177)
	at com.marklogic.client.impl.GraphManagerImpl.mergePermissions(GraphManagerImpl.java:172)
	at com.marklogic.client.test.SemanticsPermissionsTest.E_testMergePermissions(SemanticsPermissionsTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Standard Output

10:42:06.118 [main] DEBUG c.m.client.impl.JerseyServices - Posting graphs

**Comment by kkanthet** [comment]
Issue is caused by https://bugtrack.marklogic.com/35201 should be fixed in tomorrows build

**Comment by georgeajit** [comment]
The test passes on 08/25 and 08/26 runs fine on nightly regression and Jenkins respectively.
