### ISSUE TITLE
 getColumnNames not implemented for RowSet and throws UnsupportedOperationException

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#450]
For the following code snippet, we have 

```
RowSet<RowRecord> rowSet = rowMgr.resultRows(plan2);
String[] colNames = rowSet.getColumnNames();
```

exceptions reported.

```
java.lang.UnsupportedOperationException: getColumnNames() is not implemented yet
    at com.marklogic.client.impl.RowManagerImpl$RowSetImpl.getColumnNames(RowManagerImpl.java:239)
    at com.marklogic.client.functionaltest.TestOpticPlanBuilder.testjoinInnerOffsetAndLimitFromView(TestOpticPlanBuilder.java:539)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by georgeajit** [comment]
Here is the plan used.
```
ExportablePlan plan2 = p.fromView("opticFunctionalTest", "detail", "qadetail")
                .joinInner(p.fromView("opticFunctionalTest", "master", "qamaster"), 
		                   p.on(p.viewCol("qadetail", "masterId"), p.viewCol("qamaster", "id"))
		                  )
                 .select(p.viewCol("qadetail", "id"), 
		                 p.viewCol("qadetail", "name"), 
		                 p.viewCol("qamaster", "id"), 
		                 p.viewCol("qamaster", "name")
		                 )
                 .orderBy(p.desc(p.viewCol("qadetail", "name")))
                 .offset(1)
                 .limit(3);
```

**Comment by ehennum** [comment]
Should be working now.  Thanks for catching that.

**Comment by georgeajit** [comment]
The test works now.
