### ISSUE TITLE
RowRecord getValueAs throws java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#453]
The following Java Test snippet on a plan execution that has a String in the response throws 

```
java.lang.NoSuchMethodException
```

Here is the snippet:

```
RowSet<RowRecord> rowSet = rowMgr.resultRows(plan2);            
Iterator<RowRecord> rowItr = rowSet.iterator();

RowRecord record = null;
  if(rowItr.hasNext()) {            
            record = rowItr.next(); 
            assertEquals("Element 1 RowSet Iterator value incorrect", 1, record.getInt("qamaster.id"));
            assertEquals("Element 1 RowSet Iterator value incorrect", 5, record.getInt("qadetail.id"));
            assertEquals("Element 1 RowSet Iterator value incorrect", "Detail 5", record.getString("qadetail.name"));
            assertEquals("Element 1 RowSet Iterator value incorrect", "Master 1", record.getString("qamaster.name"));
            try {
                XsStringVal str = record.getValueAs("qamaster.name", XsStringVal.class);
                assertEquals("Element 1 RowSet Iterator value incorrect", "Master 1", str.getString());
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
```

This is the exception trace:

```
java.lang.NoSuchMethodException: com.marklogic.client.type.XsStringVal.<init>(java.lang.String)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.getConstructor(Unknown Source)
    at com.marklogic.client.impl.RowManagerImpl$RowRecordImpl.getValueAs(RowManagerImpl.java:532)
    at com.marklogic.client.functionaltest.TestOpticPlanBuilder.testjoinInnerOffsetAndLimitFromView(TestOpticPlanBuilder.java:605)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by ehennum** [comment]
How is this issue different from case 2 in #451? Please see the comment on that issue.

**Comment by georgeajit** [comment]
Works with ```XsStringVal.class```
