### ISSUE TITLE
mvn exec:java@test-server-init gives me "Could not find goal 'java@test-server-init'"

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#458]
Here's what I'm seeing on the develop branch:

```
$ mvn exec:java@test-server-init
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.050 s
[INFO] Finished at: 2016-08-25T10:28:01-06:00
[INFO] Final Memory: 6M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'java@test-server-init' in plugin org.codehaus.mojo:exec-maven-plugin:1.5.0 among available goals exec, help, java -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException
```

**Comment by robsman** [comment]
Hi Sam,

what version of Maven are you using? The ...@... syntax is only available from Maven 3.3.1 on.

Can you alternatively try

    $ mvn exec:java -DexecutionId=test-server-init
    ...

**Comment by sammefford** [comment]
You guessed it.  I'm on 3.2.3.  Shall we document the backward-compatible syntax in case others might be on old maven?

However, I'm wondering if teardown is really working.  First, I tried init, and got the following error:

```
$ mvn exec:java -DexecutionId=test-server-init
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building MarkLogic Java Client API 4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ java-client-api ---
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to create REST server: 400 Bad Request
Please check the server log for detail
        at com.marklogic.client.example.util.Bootstrapper.makeServer(Bootstrapper.java:170)
        at com.marklogic.client.example.util.Bootstrapper.makeServer(Bootstrapper.java:106)
        at com.marklogic.client.example.util.Bootstrapper.main(Bootstrapper.java:89)
        at com.marklogic.client.test.util.TestServerBootstrapper.bootstrapRestServer(TestServerBootstrapper.java:53)
        at com.marklogic.client.test.util.TestServerBootstrapper.main(TestServerBootstrapper.java:124)
        ... 6 more
```

So I figured I should do teardown to get back to the starting point, then I could try init.  But running teardown surprisingly gave me the same error:

```
$ mvn exec:java -DexecutionId=test-server-teardown
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building MarkLogic Java Client API 4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ java-client-api ---
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to create REST server: 400 Bad Request
Please check the server log for detail
        at com.marklogic.client.example.util.Bootstrapper.makeServer(Bootstrapper.java:170)
        at com.marklogic.client.example.util.Bootstrapper.makeServer(Bootstrapper.java:106)
        at com.marklogic.client.example.util.Bootstrapper.main(Bootstrapper.java:89)
        at com.marklogic.client.test.util.TestServerBootstrapper.bootstrapRestServer(TestServerBootstrapper.java:53)
        at com.marklogic.client.test.util.TestServerBootstrapper.main(TestServerBootstrapper.java:124)
        ... 6 more
```

**Comment by robsman** [comment]
For teardown, please use

    $ mvn exec:java -Dexec.arguments=teardown

The workaround for init is already in CONTRIBUTING.md although maybe not prominently enough. Question is, maybe we could alternatively make the POM require at least Maven 3.3.1 to avoid future confusion?

**Comment by sammefford** [comment]
Hmm, I'm not seeing a pressing need to force anyone to upgrade their maven.  Am I missing something?  I'll just take this task to change the README.md and CONTRIBUTING.md  to the backward-compatible command-line sytnax.

**Comment by robsman** [comment]
Fine with me. Thanks.
