### ISSUE TITLE
Incorrect exception message when using invalid certificate (Certificate Based Authentication)

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#460]
When calling client.newServerEval() using client object created with incorrect password and DIGEST authentication, the exception message is 

client = DatabaseClientFactory.newClient("hp1040-3505.marklogic.com", 8000, "admin","admitn",Authentication.DIGEST);

```
Exception in thread "main" com.marklogic.client.FailedRequestException: Local message: failed to apply resource at eval: Unauthorized. Server Message: Unauthorized
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4200)
	at com.marklogic.client.impl.JerseyServices.postIteratedResourceImpl(JerseyServices.java:3665)
	at com.marklogic.client.impl.JerseyServices.postEvalInvoke(JerseyServices.java:3608)
	at com.marklogic.client.impl.ServerEvaluationCallImpl.eval(ServerEvaluationCallImpl.java:163)
	at com.marklogic.client.functionaltest.TestCertBasedAuth.main(TestCertBasedAuth.java:97)
```

When calling client.newServerEval() using certificate with common name not matching a user name , the exception message is 

```
Exception in thread "main" com.marklogic.client.ForbiddenUserException: Local message: User is not allowed to apply resource at eval. Server Message: Server (not a REST instance?) did not respond with an expected REST Error message.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4196)
	at com.marklogic.client.impl.JerseyServices.postIteratedResourceImpl(JerseyServices.java:3665)
	at com.marklogic.client.impl.JerseyServices.postEvalInvoke(JerseyServices.java:3608)
	at com.marklogic.client.impl.ServerEvaluationCallImpl.eval(ServerEvaluationCallImpl.java:163)
	at com.marklogic.client.functionaltest.TestCertBasedAuth.main(TestCertBasedAuth.java:97)
```

**Comment by srinathgit** [comment]
Similarly, when writing docs,

Invalid password with DIGEST auth

```
Exception in thread "main" com.marklogic.client.FailedRequestException: Local message: write failed: Unauthorized. Server Message: Unauthorized
	at com.marklogic.client.impl.JerseyServices.putPostDocumentImpl(JerseyServices.java:1381)
	at com.marklogic.client.impl.JerseyServices.putDocument(JerseyServices.java:1183)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:913)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:751)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:681)
	at com.marklogic.client.functionaltest.TestCertBasedAuth.main(TestCertBasedAuth.java:103)

``` 

with invalid certificate

```
Exception in thread "main" com.marklogic.client.ForbiddenUserException: Local message: User is not allowed to write documents. Server Message: Server (not a REST instance?) did not respond with an expected REST Error message.
	at com.marklogic.client.impl.JerseyServices.putPostDocumentImpl(JerseyServices.java:1363)
	at com.marklogic.client.impl.JerseyServices.putDocument(JerseyServices.java:1183)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:913)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:751)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:681)
	at com.marklogic.client.functionaltest.TestCertBasedAuth.main(TestCertBasedAuth.java:103)
```

**Comment by vivekmuniyandi** [comment]
These are the errors I get from the REST server and we just check the exceptions and re throw it. I will confirm this with Erik and Sam and will follow up with this. Thanks.

**Comment by vivekmuniyandi** [comment]
As already pointed out, these were the errors which are rethrown in the Java layer and it is not generated in the Java Layer. It could be an issue with the underlying REST layer or the C++ appserver layer below it. Erik and I sat together and enabled debug logs in both the main modules and in the error handler modules but we couldn't find anything in the REST layer. Srinath and I had a chat and he checked in the underlying C++ appserver and confirmed that the appserver itself sends a 403 Forbidden exception. Hence there is nothing to fix here in the Java API. Srinath said he would follow up with Wayne on this. Thanks.
