### ISSUE TITLE
SSLTest expected exception message needs to be changed.

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#461]
On hotfixes, when this test is run on a non-SSL enabled REST server, we have an assert. Here is the stack trace.

```
<failure message="expected:&lt;...ntHandlerException: [javax.net.ssl.SSLPeerUnverifiedException: peer not authenticat]ed&gt; but was:&lt;...ntHandlerException: [org.apache.http.conn.HttpHostConnectException: Connection to https://localhost:8012 refus]ed&gt;" type="org.junit.ComparisonFailure">org.junit.ComparisonFailure: expected:&lt;...ntHandlerException: [javax.net.ssl.SSLPeerUnverifiedException: peer not authenticat]ed&gt; but was:&lt;...ntHandlerException: [org.apache.http.conn.HttpHostConnectException: Connection to https://localhost:8012 refus]ed&gt;
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.marklogic.client.test.SSLTest.testSSLAuth(SSLTest.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</failure>
```

**Comment by sammefford** [comment]
I don't understand,  Could you please explain a bit more?

For example:
* You say "SSLTest expected exception message needs to be changed".  Why?  To what should w change it?
* what does "On hotfixes" mean?
* you said "when this test is run".  What test?
* by "we have an assert" do you mean you have an assertion that fails to pass?  What is the assertion?
* the first line of the stack trace looks garbled.  Any idea why?

**Comment by georgeajit** [comment]
The above test failed when hotfix 8.0-5.8 was tested on Linux platform with SSL enabled on a MarkLogic server installation. We don't see this assert failure when SSL is not enabled on a MarkLogic installation.

The test SSLTest.java has an assert failure at 
```
com.marklogic.client.test.SSLTest.testSSLAuth(SSLTest.java:79)
```
The actual exception message, when SSLTest is run on a SSL enable MarkLogic Server, is different than the one in the test. 

The test passes when when MarkLogic server is not enabled with SSL.

**Comment by vivekmuniyandi** [comment]
This is a valid scenario. The error message need not be changed. Similar to https://github.com/marklogic/java-client-api/issues/462, I think this also had some communication issue to the server. I tested it locally and I get the unit test passed. It's indeed 'Peer not authenticated' exception only. Here also Could not connect to the host exception is thrown.

**Comment by georgeajit** [comment]
Closed the issue.
