### ISSUE TITLE
Fix InvalidUserTest when run on a SSL enabled MarkLogic Server

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#462]
Here is the output with stack trace when run on a MarkLogic Server with SSL enabled. I don't think REST server is SSL enabled. 

```
<testsuite failures="1" time="0.033" errors="0" skipped="0" tests="1" name="com.marklogic.client.test.InvalidUserTest">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/home/builder/java/jdk1.7.0_79/jre/lib/amd64"/>
    <property name="java.vm.version" value="24.79-b02"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/space/builder/builds/linux64/b8_0-5/java-client-api-dev"/>
    <property name="java.runtime.version" value="1.7.0_79-b15"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/home/builder/java/jdk1.7.0_79/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value=" "/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/home/builder/mvn/apache-maven-3.2.5/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value=".:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="51.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="3.10.0-327.22.2.el7.x86_64"/>
    <property name="user.home" value="/home/builder"/>
    <property name="user.timezone" value="America/Los_Angeles"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.7"/>
    <property name="user.name" value="builder"/>
    <property name="java.class.path" value="/home/builder/mvn/apache-maven-3.2.5/boot/plexus-classworlds-2.5.2.jar"/>
    <property name="java.vm.specification.version" value="1.7"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/home/builder/java/jdk1.7.0_79/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher test"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.7.0_79"/>
    <property name="java.ext.dirs" value="/home/builder/java/jdk1.7.0_79/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/home/builder/java/jdk1.7.0_79/jre/lib/resources.jar:/home/builder/java/jdk1.7.0_79/jre/lib/rt.jar:/home/builder/java/jdk1.7.0_79/jre/lib/sunrsasign.jar:/home/builder/java/jdk1.7.0_79/jre/lib/jsse.jar:/home/builder/java/jdk1.7.0_79/jre/lib/jce.jar:/home/builder/java/jdk1.7.0_79/jre/lib/charsets.jar:/home/builder/java/jdk1.7.0_79/jre/lib/jfr.jar:/home/builder/java/jdk1.7.0_79/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/home/builder/mvn/apache-maven-3.2.5"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase time="0.033" classname="com.marklogic.client.test.InvalidUserTest" name="testInvalidUserAuth">
    <failure message="expected:&lt;com.[marklogic.client.FailedRequestException: Local message: write failed: Unauthorized. Server Message: Unauthoriz]ed&gt; but was:&lt;com.[sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8012 refus]ed&gt;" type="org.junit.ComparisonFailure">org.junit.ComparisonFailure: expected:&lt;com.[marklogic.client.FailedRequestException: Local message: write failed: Unauthorized. Server Message: Unauthoriz]ed&gt; but was:&lt;com.[sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8012 refus]ed&gt;
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.marklogic.client.test.InvalidUserTest.testInvalidUserAuth(InvalidUserTest.java:56)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</failure>
    <system-out>00:07:51.525 [main] DEBUG c.m.client.DatabaseClientFactory - Creating new database client for server at localhost:8012
00:07:51.525 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8012 as MyFooUser
00:07:51.555 [main] INFO  c.m.client.impl.DocumentManagerImpl - Writing content for /example/text.txt
00:07:51.556 [main] DEBUG c.m.client.impl.JerseyServices - Sending /example/text.txt document in transaction null
00:07:51.556 [main] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
00:07:51.556 [main] DEBUG c.m.client.impl.JerseyServices - Releasing connection
</system-out>
  </testcase>
</testsuite>
```

**Comment by sammefford** [comment]
Could you please give me some more information on what you're looking for me to do here?

**Comment by georgeajit** [comment]
The above test failed when hotfix 8.0-5.8 was tested on Linux platform with SSL enabled on a MarkLogic server installation. We don't see this assert failure when SSL is not enabled on a MarkLogic installation.

**Comment by vivekmuniyandi** [comment]
This test is not supposed to be run on a server with SSL enabled. Here is the database client which we create:

DatabaseClient client = DatabaseClientFactory.newClient(
          "localhost", 8012, "MyFooUser", "x", Authentication.DIGEST);

There is no SSL Context involved. 

Also, this looks like an one time issue. The error message which the Server has thrown is 

org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8012 refused.

Looks like the server was down or it was an invalid port. The test ran without any error if it was enabled on a server without SSL enabled.

**Comment by georgeajit** [comment]
Closed the issue.
