### ISSUE TITLE
Latest checkout of Java Stress test client throws NoClassDefFoundError: org/quartz/SchedulerException

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#479]
Did a SVN checkout of MarkLogic qa folder from trunk (Head) on 09/14/2016. Ran the following commands from qa/stress folder on the server from where Stress client program is to be executed.

```
make clean
make
```

Exercise the REST API and Java API by running "nohup sh ./run-rest.sh > /space/stress-run.out 2>&1 &" in the stress/widowmaker directory.

Looking at the /space/stress-run.out, I see the following exception. The same command runs fine from 8.0 env.

Java version used is 1.8. 

Right now able to use 8.0 env's stress client with 4.0-SNAPSHOT jar to run stress test

```
-s
setting stress manager file to /space/linux64/HEAD/qa/stress/widowmaker/restTests.xml
StressTestProperties:  loading from StressTestProperties.xml
Properties file not found:  StressTestProperties.xml
loadStressTestExtensions
finished locating extensions at 1
Exception in thread "main" java.lang.NoClassDefFoundError: org/quartz/SchedulerException
    at test.stress.StressTest.main(StressTest.java:452)
Caused by: java.lang.ClassNotFoundException: org.quartz.SchedulerException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 1 more
```

**Comment by sammefford** [comment]
Yeah, it looks like some underlying classes now need the quartz scheduler.  So I added lib/stress/lib/common/quartz-2.2.2.jar to the $CLASSPATH in stress/widowmaker/run-rest.sh.

**Comment by georgeajit** [comment]
Able to run Java / REST Client API Stress test on the develop branch with the latest Stress Client.
