### ISSUE TITLE
exportAs on a plan throws java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#493]
Using the snippet on a plan to do exportAs(), throws exception.

```
ExportablePlan exportedPlan = plan1.joinInner(plan2, p.on(masterIdCol1, masterIdCol2), p.on(idCol1, idCol2))
                                           .orderBy(p.desc(detailNameCol))
                                           .offsetLimit(1, 100);
...
...

// ExportAs the Plan to a handle.
StringHandle strHandle = exportedPlan.exportAs(StringHandle.class);
...
...
```

Exception

```
java.lang.UnsupportedOperationException: exportAs() is not implemented yet
    at com.marklogic.client.impl.PlanBuilderBase$PlanBase.exportAs(PlanBuilderBase.java:169)
    at com.marklogic.client.impl.PlanBuilderImpl$PlanCallImpl.exportAs(PlanBuilderImpl.java:476)
    at com.marklogic.client.functionaltest.TestOpticOnViews.testExportAndImportPlan(TestOpticOnViews.java:831)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by georgeajit** [comment]
Note to QA : Test to handle this scenario is testExportAndImportPlan in TestOpticOnViews class.

**Comment by ehennum** [comment]
It should be possible to execute exportAs() on any plan that supports export()

The class must have a registered read handle that supports the JSON format.  For instance, String.class works because StringHandle can support JSON.

**Comment by georgeajit** [comment]
Works fine.
