### ISSUE TITLE
Not able to specify null in object to pattern method. Compiler error for pattern method.

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#498]
For a PlanBuilder p and PlanColumns as below we are able to specify null as subject value in the pattern method, but a null as object value produces compiler error.

```
RowManager rowMgr = client.newRowManager();
PlanBuilder p = rowMgr.newPlanBuilder();
PlanBuilder.Prefixer  bb = p.prefixer("http://marklogic.com/baseball/players");

PlanColumn ageCol = p.col("age");
PlanColumn idCol = p.col("id");
PlanColumn nameCol = p.col("name");
PlanColumn teamCol = p.col("team");
```

Null in the subject works and returns rows.

```
ModifyPlan outputNoSubject = p.fromTriples(p.pattern(null, bb.iri("age"), ageCol), "myPlayer", null, null)
                                     .orderBy(p.desc(p.viewCol("myPlayer", "age")));
```

Null in the object throws compiler error.

```
ModifyPlan outputNoObject = p.fromTriples( p.pattern(idCol, bb.iri("age"), null), "myPlayer", null, null)
                             .orderBy(p.asc(p.viewCol("myPlayer", "id")));
```

The compilation error (from Eclipse IDE) is

```
The method pattern(PlanTripleIriSeq, PlanTripleIriSeq, PlanTripleVal[]) is ambiguous for the type PlanBuilder
```

But we are able to use PlanTriplePatternSeq  object with null in the object.

```
//access with qualifier and no object
PlanTriplePatternSeq patSeqObj = p.patterns(p.pattern(idCol, bb.iri("age")), null);
ModifyPlan outputNoObject = p.fromTriples(patSeqObj, "myPlayer", null, null)
                             .orderBy(p.asc(p.viewCol("myPlayer", "id")));
jacksonHandle = new JacksonHandle();
jacksonHandle.setMimetype("application/json");

rowMgr.resultDoc(outputNoObject, jacksonHandle);
jsonResults = jacksonHandle.get();
...
...
```

 This does not throw a compiler error. However, at runtime we get FailedRequestException.

```
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at rows: Bad Request. Server Message: OPTIC-INVALARGS: fn.error(null, 'OPTIC-INVALARGS', errMsg+'null'); -- Invalid arguments: cannot specify fromTriples() with invalid triple patterns: null
    at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4231)
    at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3156)
    at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3110)
    at com.marklogic.client.impl.RowManagerImpl.resultDoc(RowManagerImpl.java:135)
    at com.marklogic.client.impl.RowManagerImpl.resultDoc(RowManagerImpl.java:121)
    at com.marklogic.client.functionaltest.TestOpticOnTriples.testAccessWithQualifier(TestOpticOnTriples.java:754)
```

For reference, here are the JavaScript Optics API tests:

```
it('TEST 24 - access with qualifier and no subject', function(done){
    var src =  
      `const op = require('/MarkLogic/optic');
      const bb = op.prefixer('http://marklogic.com/baseball/players/');
      const ageCol = op.col('age');
      const idCol = op.col('id');
      const nameCol = op.col('name');
      const teamCol = op.col('team');
      const output =
        op.fromTriples([
          op.pattern(null, bb('age'), ageCol)
        ], 'myPlayer', null, null, {dedup: 'on'})
        .orderBy(op.desc(op.viewCol('myPlayer', 'age')))
        .result();
      output;`

    db.eval(src)
    .result(function(output) {
      //console.log(JSON.stringify(output, null, 2));
      expect(output.length).to.equal(8);
      expect(output[0].value['myPlayer.age']).to.equal(34);
      expect(output[7].value['myPlayer.age']).to.equal(19);
      done();
    }, done);
  });

  it('TEST 25 - access with qualifier and no object', function(done){
    var src =  
      `const op = require('/MarkLogic/optic');
      const bb = op.prefixer('http://marklogic.com/baseball/players/');
      const ageCol = op.col('age');
      const idCol = op.col('id');
      const nameCol = op.col('name');
      const teamCol = op.col('team');
      const output =
        op.fromTriples([
          op.pattern(idCol, bb('age'), null)
        ], 'myPlayer', null, null, {dedup: 'on'})
        .orderBy(op.asc(op.viewCol('myPlayer', 'id')))
        .result();
      output;`

    db.eval(src)
    .result(function(output) {
      //console.log(JSON.stringify(output, null, 2));
      expect(output.length).to.equal(8);
      expect(output[0].value['myPlayer.id']).to.equal('http://marklogic.com/baseball/id#001');
      expect(output[7].value['myPlayer.id']).to.equal('http://marklogic.com/baseball/id#008');
      done();
    }, done);
  });
```

**Comment by ehennum** [comment]
The first case is expected for Java where a function has overloads with the same arity that are distinct only in the parameter position where null is being passed.  

The expected pattern is to cast the null, as in p.pattern(..., ..., (PlanTripleVal) null)

Please try either that approach and also simply omitting the object.

One footnote:  the following line is passing a null as the second pattern, not as an object:

    p.patterns( p.pattern(idCol, bb.iri("age")), null);

The error message from the server says that the pattern is null, which is not a valid pattern.

**Comment by georgeajit** [comment]
The pattern casting the null, as in p.pattern(..., ..., (PlanTripleVal) null) works.

**Comment by jmakeig** [comment]
> `(PlanTripleVal) null`

Love me some Java!
