### ISSUE TITLE
We need better error handling when a content database is specified with REST management operations

### ISSUE THREAD

**Issue by sanjuthomas** [marklogic/java-client-api#502]
This could be a question to start with - 
I am using the following - 
1. ML Version 8.0-4
2. Java Client API Version - 3.0.5.1

I could write a client to deploy library using ExtensionLibrariesManager.write(....). Though it's forced me to start with /ext/, it worked fine.

Then I wrote a client to read the same library using ExtensionLibrariesManager.read(.....) and It failed.

I could be doing some mistake - 

Following is the get request the read method created - 
http://localhost:15000/v1/ext/libraries/test-lib.sjs?database=azsearch-modules
This is the error that I got - 

```
REST-UNSUPPORTEDPARAM: (rest:UNSUPPORTEDPARAM) Endpoint does not support query parameter: database
in /MarkLogic/appservices/utils/rest-impl.xqy, at 885:6, in rest-impl:no-match(fn:true(), xs:QName("rest:UNSUPPORTEDPARAM"), "database") [1.0-ml]
$raise-errors = fn:true()
$error = xs:QName("rest:UNSUPPORTEDPARAM")
$msgparams = "database"
$trace = ()

```

I saw a test case around this in the repo - 

https://github.com/marklogic/java-client-api/blob/7e9cc12e59ec2ac730bbe8d5b1522c220f51349a/src/test/java/com/marklogic/client/test/ExtensionLibrariesTest.java

Is that test case passing?

**Comment by sanjuthomas** [comment]
In case you are interested to see my test case.

https://github.com/sanjuthomas/marklogic-module-deployer/blob/master/src/test/java/org/sanju/ml/deployer/TestLibraryDeployer.java

**Comment by sammefford** [comment]
Yes, ExtensiontLibrariesTest is passing.  

The issue you're facing is that your DatabaseClient is pointed to a particular content database, whereas your extension belongs in the modules database.  Therefore you can't point to a particular content database when you're doing REST admin operations like installing a REST extension. In order to make it clear that you can't change the content database it writes to, the REST endpoint doesn't even accept the database parameter.  Rather than silently ignore your specified content database, we pass it through and allow you to see the error from REST.  The solution is don't point to a particular content database when you're doing a REST admin operation that works against the modules database.

I can't explain why your write succeeds.  Are you sure it's using the same DatabaseClient instance?

**Comment by sanjuthomas** [comment]
Yes, I understand that the modules are deployed in the module database. And it works fine during PUT and the library saved into module database. I am using the same connection forget. More importantly in the put request also,  I have seen the database param. Maybe because I created the connection with the module database as database? Here is my connection creator class. 

https://github.com/sanjuthomas/marklogic-module-deployer/blob/master/src/main/java/org/sanju/ml/ConnectionManager.java

**Comment by sanjuthomas** [comment]
Yes, get works when I create the connection without the module database as the 3rd param. Again, should the behavior be same for put and get?

**Comment by sanjuthomas** [comment]
Again, on the error handling front, we can improve I believe. This is what I got on the client side- 

```
com.marklogic.client.FailedRequestException: Local message: failed to read resource at /ext/libraries/test-lib.sjs: Internal Server Error. Server Message: Server (not a REST instance?) did not respond with an expected REST Error message.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4647)
	at com.marklogic.client.impl.JerseyServices.getResource(JerseyServices.java:3215)
	at com.marklogic.client.impl.ExtensionLibrariesManagerImpl.read(ExtensionLibrariesManagerImpl.java:92)
	at org.sanju.ml.deployer.TestLibraryDeployer.shoulDeployLibraries(TestLibraryDeployer.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```
I had to debug and stop at Jersey code to see the end point invoked to figure out what's going on.  Error was available on the server log though.

**Comment by sammefford** [comment]
Ooh, I agree, we can definitely do better than that error message.  One small bit of good news on that front is we already took a related suggestion and now the 8.0.6 release (just out) will provide you with the entire response payload when it cannot parse it as a REST error.  Nevertheless, I'll take this as a bug.  I'm thinking the correct behavior here is to throw an error client-side clarifying that the database param cannot be specified whenever doing operations against the modules database.  Again, the rationale is that the REST endpoints in question generally don't accept the database param plus if they did it could be very confusing to have one's modules go into the specified content database instead of the REST server's configured modules database.

Does that sound like the right approach?

**Comment by sanjuthomas** [comment]
Agree.
