### ISSUE TITLE
Not able to run stress test with existing Java/REST API wiki page procedures

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#510]
An attempt to run Java / REST API Stress test for EA4 on MarkLogic Server nightly 9.0 release, with existing wiki page steps and scripts, failed.

Wiki page can be found at:
https://wiki.marklogic.com/pages/viewpage.action?spaceKey=ENGINEERING&title=REST+and+Java+API+Stress+Test+Configuration

Servers used are 
rh7v-intel64-90-java-stress-1
rh7v-intel64-90-java-stress-2
rh7v-intel64-90-java-stress-3
rh7v-intel64-90-java-stress-4

The machine stress-4 was used as client. 

I see the following Exceptions (snippets) from the Java Stress Client program.
```
...
...
2016-10-21 10:41:28 (Thread=43) about to load the content
2016-10-21 10:41:28 (Thread=42) com.marklogic.client.ResourceNotFoundException: Could not write non-existent document
com.marklogic.client.ResourceNotFoundException: Could not write non-existent document
    at com.marklogic.client.impl.JerseyServices.putPostDocumentImpl(JerseyServices.java:1517)
    at com.marklogic.client.impl.JerseyServices.putDocument(JerseyServices.java:1193)
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:924)
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:762)
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:706)
    at test.stress.JavaAPISession.putDocument(JavaAPISession.java:190)
    at test.stress.RestLoadTester.putDocument(RestLoadTester.java:251)
    at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:188)
    at test.stress.RestCRUDTester.runTest(RestCRUDTester.java:556)
    at test.stress.StressTest.run(StressTest.java:364)
2016-10-21 10:41:28 (Thread=40) com.marklogic.client.FailedRequestException: Local message: transaction open failed: Not Found. Server Message: Server (not a REST instance?) did not respond with an expected REST Error message.
com.marklogic.client.FailedRequestException: Local message: transaction open failed: Not Found. Server Message: Server (not a REST instance?) did not respond with an expected REST Error message.
    at com.marklogic.client.impl.JerseyServices.openTransaction(JerseyServices.java:1619)
    at com.marklogic.client.impl.DatabaseClientImpl.openTransaction(DatabaseClientImpl.java:81)
    at test.stress.JavaAPISession.beginTransaction(JavaAPISession.java:137)
    at test.stress.JavaAPISession.beginTransaction(JavaAPISession.java:54)
    at test.stress.RestLoadTester.beginRestTransaction(RestLoadTester.java:68)
    at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:141)
    at test.stress.RestLoadTester.runTest(RestLoadTester.java:278)
    at test.stress.StressTest.run(StressTest.java:364)
2016-10-21 10:41:28 (Thread=42) com.marklogic.client.ResourceNotFoundException: Could not write non-existent document
com.marklogic.client.ResourceNotFoundException: Could not write non-existent document
    at com.marklogic.client.impl.JerseyServices.putPostDocumentImpl(JerseyServices.java:1517)
    at com.marklogic.client.impl.JerseyServices.putDocument(JerseyServices.java:1193)
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:924)
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:762)
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:706)
    at test.stress.JavaAPISession.putDocument(JavaAPISession.java:190)
    at test.stress.RestLoadTester.putDocument(RestLoadTester.java:251)
    at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:188)
    at test.stress.RestCRUDTester.runTest(RestCRUDTester.java:556)
    at test.stress.StressTest.run(StressTest.java:364)
2016-10-21 10:41:28 (Thread=40) com.marklogic.client.FailedRequestException: Local message: transaction open failed: Not Found. Server Message: Server (not a REST instance?) did not respond with an expected REST Error message.
com.marklogic.client.FailedRequestException: Local message: transaction open failed: Not Found. Server Message: Server (not a REST instance?) did not respond with an expected REST Error message.
...
...
```

Looks like the the client is trying to access some of the servers as a REST server (while they are yet to be configured as a REST server). The current Stress test  configuration is one E Node (stress-1 server) and two D Nodes (stress-2 and stress-3 servers).

The E Node is functioning well. Here is the output from http://rh7v-intel64-90-java-stress-1:8011/
```
MarkLogic REST Server

    Search and retrieve XML results - /v1/search?format=xml
    Search and retrieve JSON results - /v1/search?format=json
    Search example - /v1/search?q=&start=10&pageLength=5
    Query Configuration - /v1/config/query
    Transform Configuration - /v1/config/transforms
    Add document (HTTP PUT)
        Add JSON document: curl -v --digest --user admin:***** -H "Content-Type: application/json" -X PUT -d '{"person":{"first":"John", "last":"Doe"}}' "http://localhost:8003/v1/documents?uri=/docs/person.json"
        Add XML document: curl -v --digest --user admin:***** -H "Content-Type: application/xml" -X PUT -d '<person><first>John</first><last>Doe</last></person>' "http://localhost:8003/v1/documents?uri=/docs/person.xml"
    View document (HTTP GET)
        View JSON document: /v1/documents?uri=/docs/person.json
        View XML document: /v1/documents?uri=/docs/person.xml
    Remove document (HTTP DELETE)
        Remove JSON document: curl -v --digest --user admin:***** -H "Content-Type: application/json" -X DELETE "http://localhost:8003/v1/documents?uri=/docs/person.json"
        Remove XML document: curl -v --digest --user admin:***** -H "Content-Type: application/xml" -X DELETE "http://localhost:8003/v1/documents?uri=/docs/person.xml"
```

We need to have modified XQuery scripts that makes all servers E/D nodes to accomodate the testing of datamovement functionality into the regular Java/REST API stress test.

This needs to be a priority 1 issue for EA4.

**Comment by georgeajit** [comment]
The Java stress client program log is available at 
```
/space/place1021.out
```

**Comment by georgeajit** [comment]
This was an environment issue. Sam pointed out the configuration issue.
