### ISSUE TITLE
Incorrect behavior of HostAvailabilityListener when host is shutdown

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#516]
A. The following test is done on a single node server with a db associated with a single forest. The 'minhosts' is set to 1 for HostAvailabilityListener . 

B.When the loading of documents is being done, the server is shutdown. I see the following message which is expected (for threads pool-1-thread-1 and pool-1-thread-2 as well)

```
17:26:28.030 [main] ERROR c.m.c.d.HostAvailabilityListener - Encountered [com.sun.jersey.api.client.ClientHandlerException: org.apache.http.NoHttpResponseException: The target server failed to respond] on host "localhost" but black-listing it would drop job below minHosts (1), so stopping job "unnamed"
com.sun.jersey.api.client.ClientHandlerException: org.apache.http.NoHttpResponseException: The target server failed to respond
```

C. But, the job doesn't stop and the retrying of failed batches starts and they continue on forever. The following exception/ message seems to repeat forever (for atleast 45 minutes )

```
17:26:28.065 [pool-1-thread-2] WARN  c.m.c.d.HostAvailabilityListener - Retrying failed batch: 894, results so far: 17880, uris: [/local/ABC-17860, /local/ABC-17861, /local/ABC-17862, /local/ABC-17863, /local/ABC-17864, /local/ABC-17865, /local/ABC-17866, /local/ABC-17867, /local/ABC-17868, /local/ABC-17869, /local/ABC-17870, /local/ABC-17871, /local/ABC-17872, /local/ABC-17873, /local/ABC-17874, /local/ABC-17875, /local/ABC-17876, /local/ABC-17877, /local/ABC-17878, /local/ABC-17879]
17:26:28.066 [pool-1-thread-2] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:26:28.066 [pool-1-thread-2] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:26:28.072 [pool-1-thread-1] WARN  c.m.c.d.HostAvailabilityListener - Retrying failed batch: 895, results so far: 17900, uris: [/local/ABC-17880, /local/ABC-17881, /local/ABC-17882, /local/ABC-17883, /local/ABC-17884, /local/ABC-17885, /local/ABC-17886, /local/ABC-17887, /local/ABC-17888, /local/ABC-17889, /local/ABC-17890, /local/ABC-17891, /local/ABC-17892, /local/ABC-17893, /local/ABC-17894, /local/ABC-17895, /local/ABC-17896, /local/ABC-17897, /local/ABC-17898, /local/ABC-17899]
17:26:28.073 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:26:28.073 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:26:28.077 [main] WARN  c.m.c.d.HostAvailabilityListener - Retrying failed batch: 908, results so far: 18160, uris: [/local/ABC-18140, /local/ABC-18141, /local/ABC-18142, /local/ABC-18143, /local/ABC-18144, /local/ABC-18145, /local/ABC-18146, /local/ABC-18147, /local/ABC-18148, /local/ABC-18149, /local/ABC-18150, /local/ABC-18151, /local/ABC-18152, /local/ABC-18153, /local/ABC-18154, /local/ABC-18155, /local/ABC-18156, /local/ABC-18157, /local/ABC-18158, /local/ABC-18159]
17:26:28.079 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:26:28.079 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:26:28.096 [pool-1-thread-2] ERROR c.m.c.d.HostAvailabilityListener - Encountered [com.sun.jersey.api.client.ClientHandlerException: org.apache.http.NoHttpResponseException: The target server failed to respond] on host "localhost" but black-listing it would drop job below minHosts (1), so stopping job "unnamed"
com.sun.jersey.api.client.ClientHandlerException: org.apache.http.NoHttpResponseException: The target server failed to respond
    at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:184) ~[jersey-apache-client4-1.17.jar:1.17]
    at com.marklogic.client.impl.DigestChallengeFilter.handle(DigestChallengeFilter.java:34) ~[classes/:na]
    at com.sun.jersey.api.client.filter.HTTPDigestAuthFilter.handle(HTTPDigestAuthFilter.java:493) ~[jersey-client-1.17.jar:1.17]
    at com.sun.jersey.api.client.Client.handle(Client.java:648) ~[jersey-client-1.17.jar:1.17]
    at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680) ~[jersey-client-1.17.jar:1.17]
    at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.17.jar:1.17]
    at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:568) ~[jersey-client-1.17.jar:1.17]
    at com.marklogic.client.impl.JerseyServices.doPost(JerseyServices.java:3925) ~[classes/:na]
    at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3212) ~[classes/:na]
    at com.marklogic.client.impl.JerseyServices.postBulkDocuments(JerseyServices.java:3330) ~[classes/:na]
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:618) ~[classes/:na]
    at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:1) ~[classes/:na]
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:611) ~[classes/:na]
    at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:1) ~[classes/:na]
    at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:933) [classes/:na]
    at com.marklogic.client.datamovement.impl.WriteBatcherImpl.retry(WriteBatcherImpl.java:463) ~[classes/:na]
    at com.marklogic.client.datamovement.HostAvailabilityListener.processFailure(HostAvailabilityListener.java:137) ~[classes/:na]
    at com.marklogic.client.datamovement.impl.WriteBatcherImpl.lambda$2(WriteBatcherImpl.java:436) ~[classes/:na]
    at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:960) [classes/:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_74]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_74]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_74]
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
    at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:101) ~[httpclient-4.1.1.jar:4.1.1]
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:252) ~[httpcore-4.1.jar:4.1]
    at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281) ~[httpcore-4.1.jar:4.1]
    at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:247) ~[httpclient-4.1.1.jar:4.1.1]
    at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:219) ~[httpclient-4.1.1.jar:4.1.1]
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:298) ~[httpcore-4.1.jar:4.1]
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.1.jar:4.1]
    at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:633) ~[httpclient-4.1.1.jar:4.1.1]
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:454) ~[httpclient-4.1.1.jar:4.1.1]
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820) ~[httpclient-4.1.1.jar:4.1.1]
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:776) ~[httpclient-4.1.1.jar:4.1.1]
    at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170) ~[jersey-apache-client4-1.17.jar:1.17]
    ... 23 common frames omitted
```

Test:

```

        @Test
        public void testFailOver() throws Exception{
            try{
                final String query1 = "fn:count(fn:doc())";

                final MutableInt successCount = new MutableInt(0);

                final MutableBoolean failState = new MutableBoolean(false);
                final MutableInt failCount = new MutableInt(0);

                WriteBatcher ihb2 =  dmManager.newWriteBatcher();
                ihb2.withBatchSize(20);
                ihb2.withThreadCount(2);
                dmManager.startJob(ihb2);

                ihb2.setBatchFailureListeners(
                          new HostAvailabilityListener(dmManager)
                            .withSuspendTimeForHostUnavailable(Duration.ofSeconds(10))
                            .withMinHosts(1)
                        );  
                ihb2.onBatchSuccess(
                        (client, batch) -> {

                            successCount.add(batch.getItems().length);
                          }
                        )
                        .onBatchFailure(
                          (client, batch, throwable) -> {
                              throwable.printStackTrace();

                              failState.setTrue();
                              failCount.add(batch.getItems().length);
                          });





                for (int j =0 ;j < 50000; j++){
                    String uri ="/local/ABC-"+ j;
                    ihb2.add(uri, stringHandle);
                }


                ihb2.flushAndWait();


                System.out.println("Fail : "+failCount.intValue());
                System.out.println("Success : "+successCount.intValue());
                System.out.println("Count : "+ dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue());

                Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue()==50000);

            }
            catch(Exception e){
                e.printStackTrace();
            }
        }

```

**Comment by srinathgit** [comment]
This issue is fixed

**Comment by sammefford** [comment]
I think this was 4.0.1
