### ISSUE TITLE
Using JacksonHandle.class in exportAs throws IllegalArgumentException

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#521]
In the following snippet:
```
RowManager rowMgr = client.newRowManager();
		PlanBuilder p = rowMgr.newPlanBuilder();
		JacksonHandle exportHandle = new JacksonHandle();
		
		ViewPlan plan1 = p.fromView("opticFunctionalTest", "detail");
		ViewPlan plan2 = p.fromView("opticFunctionalTest", "master");
		
		PlanColumn masterIdCol1 = plan1.col("masterId");
		PlanColumn masterIdCol2 = plan2.col("id");
		PlanColumn idCol1 = plan2.col("id");
		PlanColumn idCol2 = plan1.col("id");
		PlanColumn detailNameCol = plan1.col("name");
		PlanColumn masterNameCol = plan2.col("name");
		
		ModifyPlan exportedPlan = plan1.joinInner(plan2, p.on(masterIdCol1, masterIdCol2), p.on(idCol1, idCol2))
		                                   .orderBy(p.desc(detailNameCol))
		                                   .offsetLimit(1, 100);
		ModifyPlan exportedPlan2 = plan1.joinInner(plan2, p.on(masterIdCol1, masterIdCol2), p.on(idCol1, idCol2))
                .orderBy(p.desc(detailNameCol))
                .offsetLimit(1, 100);	
```

This export works
```
               //Export the Plan to a handle.
		exportedPlan.export(exportHandle);
		JsonNode exportNoded = exportHandle.get();
		// verify parts of the Exported Plan String.
		assertEquals("Plan export incorrect", "from-view", exportNoded.path("$optic").path("args").get(0).path("fn").asText());
		assertEquals("Plan export incorrect", "join-inner", exportNoded.path("$optic").path("args").get(1).path("fn").asText());
		assertEquals("Plan export incorrect", "from-view", exportNoded.path("$optic").path("args").get(1).path("args").get(0).path("args").get(0).path("fn").asText());
		assertEquals("Plan export incorrect", "order-by", exportNoded.path("$optic").path("args").get(2).path("fn").asText());
		assertEquals("Plan export incorrect", "offset-limit", exportNoded.path("$optic").path("args").get(3).path("fn").asText());
```
However, this exportAs with JacksonHandle.class produces an  IllegalArgumentException at runtime.

```
JacksonHandle JackHandleAs = exportedPlan2.exportAs(JacksonHandle.class);
```

Here is the stack trace:
java.lang.IllegalArgumentException: No factory for class com.marklogic.client.io.JacksonHandle
	at com.marklogic.client.impl.HandleFactoryRegistryImpl.makeHandle(HandleFactoryRegistryImpl.java:98)
	at com.marklogic.client.impl.PlanBuilderBase$PlanBase.exportAs(PlanBuilderBase.java:367)
	at com.marklogic.client.impl.PlanBuilderImpl$PlanCallImpl.exportAs(PlanBuilderImpl.java:513)
	at com.marklogic.client.functionaltest.TestOpticOnViews.testExportPlanWithPlanCol(TestOpticOnViews.java:768)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
Note: The String.class with exportAs works fine.

**Comment by sammefford** [comment]
Ajit, are you aware that JacksonHandle (and most handles, for that matter) is not regiestered with HandleFactoryRegistry?  Why would you use exportAs with JacksonHandle when you could use export?  The purpose for exportAs is to allow you direct access to the types handled by the handles.  In this case, JsonNode is the thing handled by JacksonHandle, and the thing you would pass to exportAs.

**Comment by georgeajit** [comment]
Using JsonNode works fine. Closing this issue due to incorrect class type usage. 

We already have a similar issue for the need of documenting usage of handles at #385 and your comment about Bug Track Issue 42218 for Java Guide/docs.
