### ISSUE TITLE
QueryBatcher ConcurrentModificationException when iterating over ArrayList

### ISSUE THREAD

**Issue by chiamarc** [marklogic/java-client-api#530]
Running Jmeter with a sampler that implements the code below.
The following exception occurs when using a QueryBatcher that should be iterating over a list of URIs:

```
com.marklogic.client.datamovement.QueryHostException: java.util.ConcurrentModificationException
     at com.marklogic.client.datamovement.impl.QueryBatcherImpl$1.run(QueryBatcherImpl.java:567)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
     at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
     at java.util.ArrayList$Itr.next(ArrayList.java:851)
     at com.marklogic.client.datamovement.impl.QueryBatcherImpl$1.run(QueryBatcherImpl.java:528)
     ... 3 more
```

Making `moveMgr`, `qTransformer`, and `ticket` into class variables by using static has no effect. 

```java
public class BulkTransformSamplerLarge extends AbstractJavaSamplerClient implements Serializable {
 
    private static final long serialVersionUID = 1L;
    private static Logger logger = LoggerFactory.getLogger(BulkTransformSamplerLarge.class);
    public static DatabaseClient initClient;
    
    private DataMovementManager moveMgr;
    private QueryBatcher qTransformer;
    private JobTicket ticket;
    
    private int batchSize;
    private int numThreads;
    private int numBatches;
    private String uripath;
 
    @Override
    public void setupTest(JavaSamplerContext context) {
    initClient = DatabaseClientFactory.newClient(
                context.getParameter("HOST"),
                context.getIntParameter("PORT"),
                      new DatabaseClientFactory.DigestAuthContext(
                                 context.getParameter("USER"),
                                 context.getParameter("PASSWORD")));
     
    File transformFile = new File(context.getParameter("TRANSFORM"));
         
         initClient.newServerConfigManager().newTransformExtensionsManager().writeXQueryTransform("add-element-xquery-transform", new FileHandle(transformFile));
    moveMgr = initClient.newDataMovementManager();
 
    batchSize = context.getIntParameter("BATCHSIZE");
    numThreads = context.getIntParameter("THREADS");
    uripath = context.getParameter("URIPATH");
    }
 
    // set up default arguments for the JMeter GUI
    @Override
     public Arguments getDefaultParameters() {
     
         Arguments defaultParams = new Arguments();
           defaultParams.addArgument("HOST", "localhost");
           defaultParams.addArgument("PORT", "8003");
           defaultParams.addArgument("USER", "admin");
           defaultParams.addArgument("PASSWORD", "admin");
           defaultParams.addArgument("BATCHSIZE", "10");
           defaultParams.addArgument("THREADS", "1");
           defaultParams.addArgument("URIPATH", "/space/datasets/medline.dmsdk/xml001.zip/");
           defaultParams.addArgument("TRANSFORM","add-elt-trans.xqy");
           return defaultParams;
    }
 
    
     @Override
     public SampleResult runTest(JavaSamplerContext context) {
 
           SampleResult result = new SampleResult();
 
         StructuredQueryBuilder sqb = new StructuredQueryBuilder();
           StructuredQueryDefinition query = sqb.directory(true, uripath);
 
           List<String> uris = Collections.synchronizedList(new ArrayList<String>());
           
           QueryBatcher getUris = moveMgr.newQueryBatcher(query)
                                                   .withBatchSize(5000)
                                                   .onUrisReady((client, batch) -> uris.addAll(Arrays.asList(batch.getItems())) );
           
           qTransformer = moveMgr.newQueryBatcher(uris.iterator())
                      .withThreadCount(numThreads)
                      .withBatchSize(batchSize)
                      .withConsistentSnapshot()
                      .onUrisReady(
                           new ApplyTransformListener()
                                .withApplyResult(ApplyResult.REPLACE)
                                 .withTransform(new ServerTransform("add-element-xquery-transform"))
                                 .onSuccess((client, batch) -> {
                                      logger.debug("Batch transformed {}, so far {}", batch.getJobBatchNumber(), batch.getJobResultsSoFar());
                                      numBatches++;
                                 })
                                 .onSkipped((client, batch) ->
                                      logger.warn("Files skipped: {}", Arrays.asList(batch.getItems()))
                                 )
                                 .onBatchFailure((client, batch, throwable) -> throwable.printStackTrace())
                              )
                     .onQueryFailure((client, throwable) -> throwable.printStackTrace());
 
    // Start stopwatch
    result.sampleStart(); 
 
           try {
                
                numBatches = 0;
                
                // Get URIs in a large batch
                moveMgr.startJob(getUris);
                getUris.awaitCompletion();
                
                ticket = moveMgr.startJob(qTransformer);
                qTransformer.awaitCompletion();
                moveMgr.stopJob(ticket);
     
                result.sampleEnd(); // stop stopwatch
                result.setSuccessful( true );
                result.setResponseMessage( numBatches + " batches successfully transformed!" );
     
                //result.setResponseCodeOK(); // 200 code
     
           } catch (Exception e) {
               result.sampleEnd(); // stop stopwatch
               result.setSuccessful( false );
               result.setResponseMessage( "Exception: " + e );
     
               // get stack trace as a String to return as document data
               java.io.StringWriter stringWriter = new java.io.StringWriter();
               e.printStackTrace( new java.io.PrintWriter( stringWriter ) );
               result.setResponseData( stringWriter.toString(), null );
               result.setDataType( org.apache.jmeter.samplers.SampleResult.TEXT );
               result.setResponseCode( "500" );
           }
     
           return result;
    }
 
    public void teardownTest(JavaSamplerContext context) {
    initClient.release();
    }
 
}
```

**Comment by sammefford** [comment]
Could we go the opposite of static?  Could you make them local variables?  The problem is that something is modifying the ArrayList while something else is traversing it.  I don't think that's what you are trying to do here.  I think you're trying to populate the ArrayList first, then once populated have the QueryBatcher traverse it.  Correct?

**Comment by sammefford** [comment]
Looks like the answer here is simple.  You can't call iterator() before add() or you'll get ConcurrentModificationException as soon as you call next() on that iterator().  You're simply not allowed to modify the underlying list while you're holding or traversing an iterator.  So move these lines to before you call iterator():

                // Get URIs in a large batch
                moveMgr.startJob(getUris);
                getUris.awaitCompletion();

**Comment by chiamarc** [comment]
Fixed.

Unfortunately, no improvement in performance :(
