### ISSUE TITLE
REGR: Unit test failure QueryBatcherTest.testRawValueQuery()

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#559]
The unit test com.marklogic.client.test.datamovement.QueryBatcherTest.testRawValueQuery() is failing. I see the following assert failure.

```
java.lang.AssertionError: expected:<4> but was:<5>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.marklogic.client.test.datamovement.QueryBatcherTest.runQueryBatcher(QueryBatcherTest.java:292)
	at com.marklogic.client.test.datamovement.QueryBatcherTest.runQueryBatcher(QueryBatcherTest.java:196)
	at com.marklogic.client.test.datamovement.QueryBatcherTest.testRawValueQuery(QueryBatcherTest.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

Iterating through 'searchResults', I see all the 5 uri's are returned by the search

**Comment by srinathgit** [comment]
The issue seems to be with RawStructuredQueryDefinition rather than with dmsdk . With the data used in QueryBatcherTest, the following test returns

fn:doc("/QueryBatcherTest/content_3.json")
fn:doc("/QueryBatcherTest/content_4.json")
fn:doc("/QueryBatcherTest/content_5.json")
fn:doc("/QueryBatcherTest/content_1.json")
fn:doc("/QueryBatcherTest/content_2.json")
```
@Test
public void testRawStructuredQuery(){
StringHandle structuredQuery = new StringHandle(
      "{ \"query\": " +
        "{ \"queries\": [" +
          "{ \"value-query\": " +
            "{  \"json-property\": \"department\"," +
            "  \"text\": [\"HR\"]" +
            "}" +
          "}" +
        "]}" +
      "}").withFormat(JSON);
    StructuredQueryDefinition query = client.newQueryManager().newRawStructuredQueryDefinition(structuredQuery);
    query.setCollections(qhbTestCollection);
SearchHandle searchResults = client.newQueryManager().search(query, new SearchHandle());
 for(MatchDocumentSummary m: searchResults.getMatchResults()){
    	System.out.println(m.getPath());
    }
}
```

**Comment by srinathgit** [comment]
The test runs fine after the fix
