### ISSUE TITLE
REGR: ApplyTransformListener's client object is null

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#568]
The following test runs in nightly regression(in ApplyTransformListenerTest.java) that queries all documents in collection "Replace Snapshot", applies transform on them and then finally deletes the document in a single QueryBatcher instance.
The batch.getClient() method in onSuccess callback of ApplyTransformListener is providing a null object . The test below fails at assertFalse(isClientNull.get());

```
@Test
	public void jsMasstransformReplaceDelete() throws Exception{

		//transform
		ServerTransform transform = new ServerTransform("jsTransform");
		transform.put("newValue", "Value");

		AtomicInteger count = new AtomicInteger();
		AtomicBoolean flag = new AtomicBoolean(true);
		AtomicBoolean isClientNull = new AtomicBoolean(false);
	 	
		ApplyTransformListener listener = new ApplyTransformListener()
				.withApplyResult(ApplyResult.REPLACE)
				.onSuccess(batch -> {
					System.out.println("Success: ");
					System.out.println("Forest : "+batch.getForest().getDatabaseName());
					System.out.println("Forest id : "+batch.getForest().getForestId());
					System.out.println("Alternate : "+batch.getForest().getAlternateHost());
					System.out.println("open replica host : "+batch.getForest().getOpenReplicaHost());
					System.out.println("Host : "+batch.getForest().getHost());
					System.out.println("Preferred : "+batch.getForest().getPreferredHost());
					System.out.println("JobBatchNumber : "+batch.getJobBatchNumber());
					System.out.println("ServerTimestamp : "+batch.getServerTimestamp());
					System.out.println("Timestamp : "+batch.getTimestamp());
					for (String successuri: batch.getItems()){
						System.out.println("Succeeded : "+successuri);
						
					}
					if(batch.getClient() == null){
						isClientNull.set(true);
					}
					DocumentPage page = batch.getClient().newDocumentManager().read(batch.getItems());
					JacksonHandle dh = new JacksonHandle();
					while(page.hasNext()){
						DocumentRecord rec = page.next();
						rec.getContent(dh);
						System.out.println(dh.get().get("c").asText().trim());
						if(! dh.get().get("c").asText().trim().equals("Value")){
							flag.set(false);
						}

						count.incrementAndGet();
					}

				})
				.onBatchFailure((batch, throwable)->{
					System.out.println("Failure: ");
					System.out.println("JobBatchNumber : "+batch.getJobBatchNumber());
					System.out.println("Timestamp : "+batch.getTimestamp());
					for (String faileduri: batch.getItems()){
						System.out.println("Failed : "+faileduri);
					}
					throwable.printStackTrace();
					System.out.println(throwable.getMessage());
				})
				.withTransform(transform);

		//Query collection "Replace Snapshot", a listener forTransform and another for Deletion are attached	    
		QueryBatcher batcher = dmManager.newQueryBatcher(new StructuredQueryBuilder().collection("Replace Snapshot"))
				.withBatchSize(1)
				.withConsistentSnapshot()
				.onUrisReady(listener)
				.onUrisReady(new DeleteListener())
				.onQueryFailure( throwable -> {
					throwable.printStackTrace();

				});
		batcher.setQueryFailureListeners(
		  new HostAvailabilityListener(dmManager)
		    .withSuspendTimeForHostUnavailable(Duration.ofSeconds(30))
		    .withMinHosts(2)
		);	
		JobTicket ticket = dmManager.startJob( batcher );
		batcher.awaitTermination(Long.MAX_VALUE, TimeUnit.DAYS);
		dmManager.stopJob(ticket);

		assertFalse(isClientNull.get());
		assertEquals("document count", 100,count.intValue());
		assertTrue(flag.get());

		List<String> urisList = new ArrayList<>();
		QueryBatcher queryBatcher = dmManager.newQueryBatcher(
				new StructuredQueryBuilder().collection("Replace Snapshot"))
				.withBatchSize(11)
				.onUrisReady(batch->{
					for(String s: batch.getItems()){
						urisList.add(s);
					}
				})
				.onQueryFailure( throwable -> {
					throwable.printStackTrace();

				});

		JobTicket ticket1 = dmManager.startJob( queryBatcher );
		queryBatcher.awaitTermination(Long.MAX_VALUE, TimeUnit.DAYS);
		dmManager.stopJob(ticket1);
		assertTrue(urisList.isEmpty());
	}
```

Assertion error:

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.marklogic.client.datamovement.functionaltests.ApplyTransformTest.jsMasstransformReplaceDelete(ApplyTransformTest.java:669)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

**Comment by srinathgit** [comment]
Client object is not null. Shipping the bug.
