### ISSUE TITLE
REGR: Writing documents to server throws exception

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#575]
The following code is from a test that runs in nightly regression and can be found in "com.marklogic.client.functionaltest.TestBulkReadWriteWithJacksonDataBind.java". When trying to write documents, it throws an exception at "docMgr.write(writeset);"

```java
@Test
	public void testJacksonDataBindHandleFromFactory() throws KeyManagementException, NoSuchAlgorithmException, Exception {
				
		String docId[] = { "/iphone.json", "/imac.json", "/ipad.json" };
				
		// Create three custom POJO instances
		
		Product newProduct1 = new Product();
		newProduct1.setName("iPhone 6");
		newProduct1.setIndustry("Mobile Phone");
		newProduct1.setDescription("New iPhone 6");
		
		Product newProduct2 = new Product();
		newProduct2.setName("iMac");
		newProduct2.setIndustry("Desktop");
		newProduct2.setDescription("Air Book OS X");
		
		Product newProduct3 = new Product();
		newProduct3.setName("iPad");
		newProduct3.setIndustry("Tablet");
		newProduct3.setDescription("iPad Mini");
		
		//Create a content Factory from JacksonDatabindHandle that will handle POJO class type.  
		ContentHandleFactory ch = JacksonDatabindHandle.newFactory(Product.class);
		
		//Instantiate a handle for each POJO instance.
		JacksonDatabindHandle<Product> handle1 = (JacksonDatabindHandle<Product>) ch.newHandle(Product.class); 
		JacksonDatabindHandle<Product> handle2 = (JacksonDatabindHandle<Product>) ch.newHandle(Product.class);
		JacksonDatabindHandle<Product> handle3 = (JacksonDatabindHandle<Product>) ch.newHandle(Product.class);
		
		//Assigns the custom POJO as the content.
		handle1.set(newProduct1);
		handle2.set(newProduct2);
		handle3.set(newProduct3);
		
		//Specifies the format of the content.
		handle1.withFormat(Format.JSON);
		handle2.withFormat(Format.JSON);
		handle3.withFormat(Format.JSON);
		
		DocumentMetadataHandle mhRead = new DocumentMetadataHandle();

		JSONDocumentManager docMgr = client.newJSONDocumentManager();
		docMgr.setMetadataCategories(Metadata.ALL);
		DocumentWriteSet writeset = docMgr.newWriteSet();
		// put meta-data
		DocumentMetadataHandle mh = setMetadata();
						
		writeset.addDefault(mh);
				
		writeset.add(docId[0], handle1);
		writeset.add(docId[1], handle2);
		writeset.add(docId[2], handle3);

		docMgr.write(writeset);
					
	}
```
```java
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Product 
{
	String name;
	String industry;
	String description;
		
	public Product() 
	{
		super();
	}
	
	public String getName() 
	{
		return name;
	}
		
	public void setName(String name) 
	{
		this.name = name;
	}
		
	public String getIndustry() 
	{
		return industry;
	}
		
	public void setIndustry(String industry) 
	{
		this.industry = industry;
	}
		
	public String getDescription() 
	{
		return description;
	}
		
	public void setDescription(String description) 
	{
		this.description = description;
	}
}
```

Exception:

```
com.marklogic.client.FailedRequestException: Local message: Content version required to apply resource at documents. Server Message: RESTAPI-CONTENTNOVERSION: (err:FOER0000) No content version supplied:  uri /iphone.json
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4272)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3293)
	at com.marklogic.client.impl.JerseyServices.postBulkDocuments(JerseyServices.java:3381)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:618)
	at com.marklogic.client.impl.JSONDocumentImpl.write(JSONDocumentImpl.java:1)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:611)
	at com.marklogic.client.impl.JSONDocumentImpl.write(JSONDocumentImpl.java:1)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:595)
	at com.marklogic.client.impl.JSONDocumentImpl.write(JSONDocumentImpl.java:1)
	at com.marklogic.client.functionaltest.TestBulkReadWriteWithJacksonDataBind.testJacksonDataBindHandleFromFactory(TestBulkReadWriteWithJacksonDataBind.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

**Comment by kkanthet** [comment]
@sammefford  can you please take a look at this asap, there are lot if tests failing due to this

**Comment by sammefford** [comment]
It looks like you're running against a REST server that has content versioning required.  Is that what you want?  If not, perhaps you can track down why content versioning is getting enabled to solve the issue.

**Comment by srinathgit** [comment]
A test had changed the update policy . The test had been fixed. Shipping the bug
