### ISSUE TITLE
REGR: Authentication failure on creating client connection using Kerberos

### ISSUE THREAD

**Issue by kkanthet** [marklogic/java-client-api#583]
We are seeing 401  Unathorized  on client connection using kerberos , klist does show the principal user and setup does seem right.

```log 
klist
Ticket cache: FILE:/tmp/krb5cc_3539
Default principal: user2@MLTEST1.LOCAL

Valid starting       Expires              Service principal
12/06/2016 15:44:41  12/07/2016 01:44:41  krbtgt/MLTEST1.LOCAL@MLTEST1.LOCAL
       	renew until 12/13/2016 15:44:41
```

```log
 <testcase name="testWriteTextDoc" classname="com.marklogic.client.functionaltest.TestDatabaseClientWithKerberos" time="0.595">
failure message="com.marklogic.client.FailedRequestException: Local message: write failed: Unauthorized. Server Message: Unauthorized" type="com.marklogic.client.FailedRequestException">com.marklogic.client.FailedRequestException: Local message: write failed: Unauthorized. Server Message: Unauthorized
        at com.marklogic.client.impl.JerseyServices.putPostDocumentImpl(JerseyServices.java:1413)
        at com.marklogic.client.impl.JerseyServices.putDocument(JerseyServices.java:1206)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:924)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:762)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:692)
        at com.marklogic.client.functionaltest.TestDatabaseClientWithKerberos.testWriteTextDoc(TestDatabaseClientWithKerberos.java:556)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

**Comment by sammefford** [comment]
Can you describe your server settings wrt auth?  Including info about the user...

**Comment by sammefford** [comment]
Kiran is going to run a test to verify that the same request with the same user against the same MarkLogic instance succeeds in Node and fails in Java.  If so, he'll provide the HTTP wire trace from each request so we can compare.

**Comment by kkanthet** [comment]
As both Node and Java tests are failing, Sam sent email to engineering for any insight into changes happened on server side, awaiting response from team.

**Comment by sammefford** [comment]
Handing this back to Kiran since we saw the tests pass once we set "SSL Require Client Certificate" to false.  Kiran will track down how that is getting set to true and causing this issue.

**Comment by naliniprakash** [comment]
Adding notes from the meeting to debug this issue - Theoretically, setting 'SSL Require Client Certificate' to true should have worked. 
Srinath to add server side tests to confirm that true configuration does work on the server.

**Comment by srinathgit** [comment]
Bug 43695 has been opened for this issue and server tests have been added

**Comment by kkanthet** [comment]
fixed the tests to make ssl cert required to false, will come back and update the test to work when 43695 is fixed.
