### ISSUE TITLE
Test QueryBatcher with a RawCombinedQueryDefinition

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#590]
It looks like we only have one test that tries RawCombinedQueryDefinition with QueryBatcher: StringQueryHostBatcherTest.testQueryBatcherQueryFailures.  But that test is marked with the annotation @Ingore.  Can we add a fleshed-out test of RawCombinedQueryDefinition with QueryBatcher?

**Comment by georgeajit** [comment]
A test with RawCombinedQueryDefinition object passed to QueryBatcher job produces exceptions.
```
com.marklogic.client.datamovement.QueryBatchException: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at internal/uris: Bad Request. Server Message: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Unsuported content-type: "application/octet-stream"
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:567)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at internal/uris: Bad Request. Server Message: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Unsuported content-type: "application/octet-stream"
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4277)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3195)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3148)
	at com.marklogic.client.impl.JerseyServices.uris(JerseyServices.java:2905)
	at com.marklogic.client.impl.QueryManagerImpl.uris(QueryManagerImpl.java:177)
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:517)
	... 3 more
com.marklogic.client.datamovement.QueryBatchException: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at internal/uris: Bad Request. Server Message: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Unsuported content-type: "application/octet-stream"
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:567)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at internal/uris: Bad Request. Server Message: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Unsuported content-type: "application/octet-stream"
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4277)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3195)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3148)
	at com.marklogic.client.impl.JerseyServices.uris(JerseyServices.java:2905)
	at com.marklogic.client.impl.QueryManagerImpl.uris(QueryManagerImpl.java:177)
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:517)
	... 3 more
```

The following options are stored on the server, with name ```valueConstraintWithoutIndexSettingsAndNSOpt``` and are read from a file named ```valueConstraintWithoutIndexSettingsAndNSOpt.xml```.

```
<options xmlns="http://marklogic.com/appservices/search">
  <return-metrics>false</return-metrics>
  <return-qtext>false</return-qtext>
  <debug>true</debug>
  <transform-results apply="raw"/>
  <constraint name="id">
    <value>
      <element ns="" name="id"/>
    </value>
  </constraint>
</options>
```
The query is read from file '''combinedQueryNoOption.xml''' and this is its content:
```
<search xmlns="http://marklogic.com/appservices/search">
  <query>
    <value-constraint-query>
      <constraint-name>id</constraint-name>
      <text>0026</text>
    </value-constraint-query>
  </query>  
</search>
```

Here is the test method:
```
public void testRawCombinedQueryJSONWithWriteOptions() throws Exception
	{
		String testMultipleDB = "RawCombinedQueryJSONDB";
		String[] testMultipleForest = {"RawCombinedQueryJSONDB-1", "RawCombinedQueryJSONDB-2", "RawCombinedQueryJSONDB-3"};
		DatabaseClient clientTmp = null;
		DataMovementManager dmManagerTmp = null;

		try {
			System.out.println("Running testRawCombinedQueryJSONWithWriteOptions");

			//Setup a separate database/
			createDB(testMultipleDB);
			createForest(testMultipleForest[0], testMultipleDB);
			createForest(testMultipleForest[1], testMultipleDB);			
			associateRESTServerWithDB(restServerName, testMultipleDB);

			setupAppServicesConstraint(testMultipleDB);
			Thread.sleep(10000);

			String[] filenames = {"constraint1.xml", "constraint2.xml", "constraint3.xml", "constraint4.xml", "constraint5.xml"};
			String queryOptionFileName = "valueConstraintWithoutIndexSettingsAndNSOpt.xml";
			String queryOptionName = "valueConstraintWithoutIndexSettingsAndNSOpt";
			String queryName = "combinedQueryNoOption.xml";
			
			clientTmp = DatabaseClientFactory.newClient(restServerHost, restServerPort, "eval-user", "x", Authentication.DIGEST);
			dmManagerTmp = clientTmp.newDataMovementManager();

			QueryManager queryMgr = clientTmp.newQueryManager();
			String dataFileDir = dataConfigDirPath + "/data/";
			String combQueryFileDir = dataConfigDirPath + "/combined/";

			//Use WriteBatcher to write the same files.				
			WriteBatcher wbatcher = dmManagerTmp.newWriteBatcher();

			wbatcher.withBatchSize(2);
			InputStreamHandle contentHandle1 = new InputStreamHandle();
			contentHandle1.set(new FileInputStream(dataFileDir + filenames[0]));
			InputStreamHandle contentHandle2 = new InputStreamHandle();
			contentHandle2.set(new FileInputStream(dataFileDir + filenames[1]));
			InputStreamHandle contentHandle3 = new InputStreamHandle();
			contentHandle3.set(new FileInputStream(dataFileDir + filenames[2]));
			InputStreamHandle contentHandle4 = new InputStreamHandle();
			contentHandle4.set(new FileInputStream(dataFileDir + filenames[3]));
			InputStreamHandle contentHandle5 = new InputStreamHandle();
			contentHandle5.set(new FileInputStream(dataFileDir + filenames[4]));

			wbatcher.add(filenames[0], contentHandle1);
			wbatcher.add(filenames[1], contentHandle2);
			wbatcher.add(filenames[2], contentHandle3);
			wbatcher.add(filenames[3], contentHandle4);
			wbatcher.add(filenames[4], contentHandle5);
			
			// Verify if the batch flushes when batch size is reached.
			// Flush
			
			wbatcher.flushAndWait();
			wbatcher.awaitCompletion();
			
			setQueryOptionFromFile(clientTmp, queryOptionFileName, queryOptionName);
			// get the combined query
			File file = new File(combQueryFileDir+queryName);

			// create a handle for the search criteria
			FileHandle rawHandle = new FileHandle(file);
			// create a search definition based on the handle
			RawCombinedQueryDefinition querydef = queryMgr.newRawCombinedQueryDefinition(rawHandle, queryOptionName);
			
			StringBuilder batchResults = new StringBuilder();
			StringBuilder batchFailResults = new StringBuilder();

			// Run a QueryBatcher on the new URIs.
			QueryBatcher queryBatcher1 = dmManagerTmp.newQueryBatcher(querydef);

			queryBatcher1.onUrisReady(batch-> {
				for (String str : batch.getItems()) {
					batchResults.append(str)
					.append('|');
				}     
			});
			queryBatcher1.onQueryFailure(throwable-> {        	
				System.out.println("Exceptions thrown from callback onQueryFailure");        	
				throwable.printStackTrace();
				batchFailResults.append("Test has Exceptions");          	
			} );

			JobTicket jobTicket = dmManagerTmp.startJob(queryBatcher1);
			boolean bJobFinished = queryBatcher1.awaitCompletion(3, TimeUnit.MINUTES);		

			if (queryBatcher1.isStopped()) {

				if (!batchFailResults.toString().isEmpty() && batchFailResults.toString().contains("Exceptions")) {
					fail("Test failed due to exceptions");
				}

				// Verify the batch results now.
				String[] res = batchResults.toString().split("\\|");
				assertEquals("Number of reults returned is incorrect", 1, res.length);
				assertTrue("URI returned not correct", res[0].contains("/abs-range-constraint/batcher-contraints2.xml"));
			}
		}
		catch (Exception e) {
			System.out.println("Exceptions thrown from Test testAndWordQueryWithMultipleForests");
			System.out.println(e.getMessage());
		}
		finally {
			// Associate back the original DB.
			associateRESTServerWithDB(restServerName, dbName);
			detachForest(testMultipleDB, testMultipleForest[0]);
			detachForest(testMultipleDB, testMultipleForest[1]);
			deleteDB(testMultipleDB);

			deleteForest(testMultipleForest[0]);
			deleteForest(testMultipleForest[1]);
			Thread.sleep(10000);
			clientTmp.release();
		}
	}

// Write options to server
public void setQueryOptionFromFile(DatabaseClient client, String queryFile, String queryOptionName) throws FileNotFoundException
	{
		// create a manager for writing query options
		QueryOptionsManager optionsMgr = client.newServerConfigManager().newQueryOptionsManager();

		// create handle
		ReaderHandle handle = new ReaderHandle();
		
		// write the files
		BufferedReader docStream = new BufferedReader(new FileReader("src/test/java/com/marklogic/client/functionaltest/queryoptions/" + queryFile));
		handle.set(docStream);
		
		// write the query options to the database
		optionsMgr.writeOptions(queryOptionName, handle);		    

		System.out.println("Write " + queryOptionName + " to database");
	}

```
Logs
8011_AccessLog.txt
```
127.0.0.1 - eval-user [04/Feb/2017:12:54:37 -0800] "HEAD /v1/ping HTTP/1.1" 204 0 - -
127.0.0.1 - eval-user [04/Feb/2017:12:54:37 -0800] "HEAD /v1/ping HTTP/1.1" 204 0 - -
127.0.0.1 - eval-user [04/Feb/2017:12:54:41 -0800] "POST /v1/documents HTTP/1.1" 200 461 - -
127.0.0.1 - eval-user [04/Feb/2017:12:54:41 -0800] "POST /v1/documents HTTP/1.1" 200 269 - -
127.0.0.1 - eval-user [04/Feb/2017:12:54:41 -0800] "POST /v1/documents HTTP/1.1" 200 461 - -
127.0.0.1 - eval-user [04/Feb/2017:12:54:42 -0800] "PUT /v1/config/query/valueConstraintWithoutIndexSettingsAndNSOpt HTTP/1.1" 204 0 - -
127.0.0.1 - - [04/Feb/2017:12:54:42 -0800] "POST /v1/internal/uris?pageLength=1000&forest-name=RawCombinedQueryJSONDB-1&options=valueConstraintWithoutIndexSettingsAndNSOpt HTTP/1.1" 401 104 - -
127.0.0.1 - - [04/Feb/2017:12:54:42 -0800] "POST /v1/internal/uris?pageLength=1000&forest-name=RawCombinedQueryJSONDB-2&options=valueConstraintWithoutIndexSettingsAndNSOpt HTTP/1.1" 401 104 - -
127.0.0.1 - eval-user [04/Feb/2017:12:54:43 -0800] "POST /v1/internal/uris?pageLength=1000&forest-name=RawCombinedQueryJSONDB-1&options=valueConstraintWithoutIndexSettingsAndNSOpt HTTP/1.1" 400 223 - -
127.0.0.1 - eval-user [04/Feb/2017:12:54:43 -0800] "POST /v1/internal/uris?pageLength=1000&forest-name=RawCombinedQueryJSONDB-2&options=valueConstraintWithoutIndexSettingsAndNSOpt HTTP/1.1" 400 223 - -
127.0.0.1 - - [04/Feb/2017:12:55:01 -0800] "DELETE /v1/search/ HTTP/1.1" 401 104 - "Apache-HttpClient/4.1.1 (java 1.5)"
127.0.0.1 - admin [04/Feb/2017:12:55:03 -0800] "DELETE /v1/search/ HTTP/1.1" 204 0 - "Apache-HttpClient/4.1.1 (java 1.5)"
```

8011_ErrorLog.txt
```
2017-02-04 12:54:43.060 Info: Status 500: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Unsuported content-type: "application/octet-stream"
2017-02-04 12:54:43.061 Info: Status 500: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Unsuported content-type: "application/octet-stream"
```

**Comment by sammefford** [comment]
All generic handles like FileHandle must have their format or mime-type set using `setFormat` or `withFormat` or `setMimetype` or `withMimetype` methods.  Otherwise, they'll resort to the default format / mimetype for that handle.  In this case, FileHandle is defaulting to BINARY format which becomes application/octet-stream mimetype, which is not an acceptable format or mimetype to send over a combined query.  Since your query is in XML, change the one line of code to this:

			FileHandle rawHandle = new FileHandle(file).withFormat(Format.XML);
