### ISSUE TITLE
Cannot parse JSON Error when processing a long response

### ISSUE THREAD

**Issue by laquereric** [marklogic/java-client-api#592]
Cannot parse JSON Error when processing a long response

```
com.marklogic.client.MarkLogicIOException: Cannot parse JSON '[{"ICS_codeData":{"midbData":{"co' for fn:doc("/content/GUIDE://1972/4442a1b1-2107-4796-b2da-7bf722d05fc1/ndl-w/u/|||/a2a6f9a4-3261-421b-a309-00631c482ebc.json")
        at com.marklogic.client.io.SearchHandle$MatchDocumentSummaryImpl.populateExtractedResult(SearchHandle.java:607) ~[java-client-api-3.0.3.jar:na]
        at com.marklogic.client.io.SearchHandle$MatchDocumentSummaryImpl.getExtracted(SearchHandle.java:567) ~[java-client-api-3.0.3.jar:na]
        at MarkLogicDatabaseClientTestCase.queryForCodePage(MarkLogicDatabaseClientTestCase.java:127) [TestCase/:na]
        at MarkLogicDatabaseClientTestCase.main(MarkLogicDatabaseClientTestCase.java:162) [TestCase/:na]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input: was expecting closing '"' for name
 at [Source: [{"ICS_codeData":{"midbData":{"co; line: 1, column: 67]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581) ~[jackson-core-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533) ~[jackson-core-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:470) ~[jackson-core-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName2(ReaderBasedJsonParser.java:1447) ~[jackson-core-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName(ReaderBasedJsonParser.java:1431) ~[jackson-core-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:778) ~[jackson-core-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:208) ~[jackson-databind-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224) ~[jackson-databind-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224) ~[jackson-databind-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:270) ~[jackson-databind-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:71) ~[jackson-databind-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15) ~[jackson-databind-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736) ~[jackson-databind-2.6.5.jar:2.6.5]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2271) ~[jackson-databind-2.6.5.jar:2.6.5]
        at com.marklogic.client.io.SearchHandle$MatchDocumentSummaryImpl.populateExtractedResult(SearchHandle.java:600) ~[java-client-api-3.0.3.jar:na]
        ... 3 common frames omitted
```

**Comment by jmakeig** [comment]
@laquereric, can you provide the data that caused the problem? Which API were you calling? Which version of the Java Client? Which version of MarkLogic?

**Comment by jmakeig** [comment]
@laquereric Ah, I see you’ve already proposed a fix in #594. (That's mighty proactive of you.) I'll have the team take a look. Thanks for your contribution.

**Comment by laquereric** [comment]
Thanks for your efforts on this.

Could this possibly be included in a release on the 3 branch as well? User is at 3.0.3 and is sensitive to change.

**Comment by georgeajit** [comment]
Shipping this issue. I did not see chunking of character response back to client when SearchHandle was used in a query search result. Had enabled Http Wire tracing on a test (```testBug20979```).
