### ISSUE TITLE
awaitCompletion() throwing java.util.concurrent.CancellationException when thread Count is high

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#595]
1. The test (ran on branch 'issue579') attempts to stop the job when success event count exceeds 10 (batch size=11). From the logs, we can see that awaitCompletion() (and in turn flushAndWait() )throwing java.util.concurrent.CancellationException
2.   It looks like when the number of threads is set to high value, we can see this issue due to race condition in the snippet 
if ( ! future.isCancelled() ) {
            future.get(duration, TimeUnit.MILLISECONDS);
 }

```
@Test
	public void testAddMultiThreadedStopJob() throws Exception{
		log =LoggerFactory.getLogger(this.getClass());
		final String query1 = "fn:count(fn:doc())";
		WriteJobReportListener jrl = new WriteJobReportListener();
		AtomicBoolean isStopped = new AtomicBoolean(false);
		ihbMT =  dmManager.newWriteBatcher();
		ihbMT.withBatchSize(11).withThreadCount(25);
		
		ihbMT.setBatchSuccessListeners(jrl);		
		ihbMT.setBatchFailureListeners(jrl);
		
       	ihbMT.onBatchSuccess(
		        batch -> {
		        		       	
		        	if(jrl.getSuccessEventsCount() > 10 && ! isStopped.get()){
		    			dmManager.stopJob(writeTicket);
		    			isStopped.set(true);
	    				System.out.println("Job stopped");
		    		} 
		        	log.debug("batch: " + batch.getJobBatchNumber() +
		                    ", items: " + batch.getItems().length +
		                    ", results so far: " + batch.getJobWritesSoFar() +
		                    ", host: " + batch.getClient().getHost());
		        })
		        .onBatchFailure(
		          (batch, throwable) -> {
		        	  throwable.printStackTrace();
		        	  log.debug("Failed Batch: batch: " + batch.getJobBatchNumber() +
		                         ", results so far: " + batch.getJobWritesSoFar() +
		                         ", host: " + batch.getClient().getHost() +
		                         ", uris: " +
		                         Stream.of(batch.getItems()).map(event->event.getTargetUri()).collect(Collectors.toList()));		       
		});
		writeTicket = dmManager.startJob(ihbMT);
				
		class MyRunnable implements Runnable {
       	  
       	  @Override
       	  public void run() {
         		for (int j =0 ;j < 400; j++){
    				String uri ="/local/multi-"+ j+"-"+Thread.currentThread().getId();
    				ihbMT.add(uri, fileHandle);
    			}        

       	  }  
           		
       	} 
       	Thread t1,t2;
       	t1 = new Thread(new MyRunnable());
       	t2 = new Thread(new MyRunnable());
       	t1.setName("First Thread");
       	t2.setName("Second Thread");
      
       	t1.start();
       	t2.start();
       
    	t1.join();
       	t2.join();
       	
       	ihbMT.flushAndWait();
       	      	  	
       	int count = dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue();
       	System.out.println("Count "+count);
     
	}
```
Log;
```
20:16:12.543 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to rh7v-intel64-90-test-4.marklogic.com at 8000 as admin


20:16:20.787 [main] DEBUG c.m.client.impl.JerseyServices - Getting forestinfo as application/json
20:16:22.647 [main] DEBUG c.m.client.impl.JerseyServices - Getting forestinfo as application/json
20:16:22.836 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [rh7v-intel64-90-test-4.marklogic.com] hosts with forests for "JobReport"
20:16:22.851 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - Adding DatabaseClient on port 8000 for host "rh7v-intel64-90-test-4.marklogic.com" to the rotation
20:16:22.882 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - threadCount=40
20:16:22.882 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - batchSize=11
20:16:22.960 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:22.976 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:22.976 [pool-1-thread-3] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:22.976 [pool-1-thread-3] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:22.976 [pool-1-thread-20] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:22.976 [pool-1-thread-20] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:22.992 [pool-1-thread-27] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:22.992 [pool-1-thread-27] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:22.992 [pool-1-thread-4] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:22.992 [pool-1-thread-4] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:22.992 [pool-1-thread-28] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:22.992 [pool-1-thread-28] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:22.992 [pool-1-thread-31] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:22.992 [pool-1-thread-31] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.007 [pool-1-thread-32] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.007 [pool-1-thread-32] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.007 [pool-1-thread-35] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.007 [pool-1-thread-35] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.007 [pool-1-thread-36] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.007 [pool-1-thread-36] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.007 [pool-1-thread-39] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.007 [pool-1-thread-39] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.007 [pool-1-thread-40] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.007 [pool-1-thread-40] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.038 [pool-1-thread-10] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.038 [pool-1-thread-10] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.038 [pool-1-thread-25] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.038 [pool-1-thread-25] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.038 [pool-1-thread-8] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.038 [pool-1-thread-8] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.038 [pool-1-thread-5] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.038 [pool-1-thread-5] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.054 [pool-1-thread-11] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.054 [pool-1-thread-11] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.054 [pool-1-thread-24] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.054 [pool-1-thread-24] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.054 [pool-1-thread-13] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.054 [pool-1-thread-13] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.070 [pool-1-thread-7] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.070 [pool-1-thread-7] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.070 [pool-1-thread-6] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.070 [pool-1-thread-6] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.085 [pool-1-thread-9] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-17] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-2] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-14] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-18] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-22] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-19] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-9] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.085 [pool-1-thread-17] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.085 [pool-1-thread-26] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-2] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.085 [pool-1-thread-12] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-15] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-21] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.085 [pool-1-thread-16] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.101 [pool-1-thread-23] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.101 [pool-1-thread-38] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.101 [pool-1-thread-37] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.101 [pool-1-thread-34] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.101 [pool-1-thread-33] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.101 [pool-1-thread-30] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.101 [pool-1-thread-29] DEBUG c.m.client.impl.JerseyServices - Posting documents
20:16:23.116 [pool-1-thread-14] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.148 [pool-1-thread-18] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.148 [pool-1-thread-22] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.210 [pool-1-thread-19] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.226 [pool-1-thread-26] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.304 [pool-1-thread-12] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.304 [pool-1-thread-15] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.304 [pool-1-thread-21] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.304 [pool-1-thread-16] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.304 [pool-1-thread-23] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.304 [pool-1-thread-38] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.304 [pool-1-thread-37] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.319 [pool-1-thread-34] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.319 [pool-1-thread-33] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.319 [pool-1-thread-30] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.319 [pool-1-thread-29] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
20:16:23.491 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - flushing 8 queued docs
Success count: 22
Success count: 22
Job stopped
Job stopped
20:16:32.232 [main] ERROR c.m.c.d.impl.WriteBatcherImpl - 
java.util.concurrent.CancellationException: null
	at java.util.concurrent.FutureTask.report(FutureTask.java:121) ~[na:1.8.0_74]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206) ~[na:1.8.0_74]
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl$WriteThreadPoolExecutor.awaitCompletion(WriteBatcherImpl.java:1099) ~[classes/:na]
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.awaitCompletion(WriteBatcherImpl.java:639) [classes/:na]
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.awaitCompletion(WriteBatcherImpl.java:645) [classes/:na]
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.flush(WriteBatcherImpl.java:526) [classes/:na]
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.flushAndWait(WriteBatcherImpl.java:493) [classes/:na]
	at com.marklogic.client.datamovement.functionaltests.JobReportTest.testAddMultiThreadedStopJob(JobReportTest.java:477) [bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:na]
20:16:32.247 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
Success count: 33
Success count: 44
Success count: 55
Success count: 66
Success count: 77
Success count: 88
Success count: 99
Success count: 110
Success count: 121
Success count: 132
Success count: 143
Success count: 154
Success count: 165
Success count: 176
Success count: 187
Success count: 198
Success count: 209
Success count: 220
Success count: 231
Success count: 242
Success count: 253
Success count: 264
Success count: 275
Success count: 286
Success count: 297
Success count: 308
Success count: 319
Success count: 330
Success count: 341
Success count: 352
Success count: 363
Success count: 374
Success count: 385
Success count: 396
Success count: 407
Success count: 418
Success count: 429
Success count: 440
Count 440
JobReport-1
```

**Comment by sammefford** [comment]
Nice catch.  You're right that is a race condition.  Rather than incur overhead by synchronizing, I now squelch those exceptions but only in the case where we know the job has been told to stop.

Please test on branch issue595

**Comment by srinathgit** [comment]
Sam,

I still see issues related with this scenario. I have slightly modified the test and the issue I am seeing is :

1. If success event count > 6, job is stopped 
13:39:16.649 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - flushing 2 queued docs
Job stopped
13:39:23.797 [pool-1-thread-23] DEBUG c.m.c.d.f.JobReportTest - batch: 23, items: 7, results so far: 161, host: rh7v-intel64-90-test-4.marklogic.com

2. After that, when  the next thread execution hits awaitCompletion() , java.util.concurrent.CancellationException is thrown
13:39:23.797 [pool-1-thread-59] DEBUG c.m.c.d.f.JobReportTest - batch: 59, items: 7, results so far: 413, host: rh7v-intel64-90-test-4.marklogic.com
java.util.concurrent.CancellationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl$WriteThreadPoolExecutor.awaitCompletion(WriteBatcherImpl.java:1090)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.awaitCompletion(WriteBatcherImpl.java:634)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.awaitCompletion(WriteBatcherImpl.java:640)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.flush(WriteBatcherImpl.java:521)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.flushAndWait(WriteBatcherImpl.java:493)
	at com.marklogic.client.datamovement.functionaltests.JobReportTest.testAddMultiThreadedStopJob(JobReportTest.java:353)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
3. After that, a bunch of threads write to the db and don't wait until completion (as awaitCompletion() returns true immediately from then on)
4. In the logs , we can see that the value of Success event count-1 is 14 (which is printed after flushAndWait()
5. I add a sleep for 25 seconds and print Success event count-2 which is 420.
6. Client log is attached
[Client log](https://github.com/marklogic/java-client-api/files/643292/exception.txt)

Test:

```
	@Test
		@Test
	public void testAddMultiThreadedStopJob() throws Exception{
		
		log =LoggerFactory.getLogger(this.getClass());
		final String query1 = "fn:count(fn:doc())";
		WriteJobReportListener jrl = new WriteJobReportListener();
		AtomicBoolean isStopped = new AtomicBoolean(false);
		ihbMT =  dmManager.newWriteBatcher();
		ihbMT.withBatchSize(7).withThreadCount(60);
		
		ihbMT.setBatchSuccessListeners(jrl);		
		ihbMT.setBatchFailureListeners(jrl);
		
       	ihbMT.onBatchSuccess(
		        batch -> {
		        		       	
		        	if(jrl.getSuccessEventsCount() > 6 && ! isStopped.get()){
		    			dmManager.stopJob(writeTicket);
		    			isStopped.set(true);
	    				System.out.println("Job stopped");
		    		} 
		        	log.debug("batch: " + batch.getJobBatchNumber() +
		                    ", items: " + batch.getItems().length +
		                    ", results so far: " + batch.getJobWritesSoFar() +
		                    ", host: " + batch.getClient().getHost());
		        })
		        .onBatchFailure(
		          (batch, throwable) -> {
		        	  throwable.printStackTrace();
		        	  log.debug("Failed Batch: batch: " + batch.getJobBatchNumber() +
		                         ", results so far: " + batch.getJobWritesSoFar() +
		                         ", host: " + batch.getClient().getHost() +
		                         ", uris: " +
		                         Stream.of(batch.getItems()).map(event->event.getTargetUri()).collect(Collectors.toList()));		       
		});
		writeTicket = dmManager.startJob(ihbMT);
				
		class MyRunnable implements Runnable {
       	  
       	  @Override
       	  public void run() {
         		for (int j =0 ;j < 400; j++){
    				String uri ="/local/multi-"+ j+"-"+Thread.currentThread().getId();
    				ihbMT.add(uri, fileHandle);
    			}        
         		System.out.println("Finished executing thread: "+Thread.currentThread().getName());
       	  }  
           		
       	} 
       	Thread t1,t2;
       	t1 = new Thread(new MyRunnable());
       	t2 = new Thread(new MyRunnable());
       	t1.setName("First Thread");
       	t2.setName("Second Thread");
      
       	t1.start();
       	t2.start();
       
    	t1.join();
       	t2.join();
       	
       	ihbMT.flushAndWait(); 
       	System.out.println("Success event count-1: "+jrl.getSuccessEventsCount());
       	Thread.currentThread().sleep(25000L);
       	System.out.println("Success event count-2: "+jrl.getSuccessEventsCount());
  	}
```

**Comment by sammefford** [comment]
I'm realizing this isn't urgent because it's strange to stop the job before calling flushAndWait.  We can still fix this, but it doesn't need to be a fire drill.

**Comment by sammefford** [comment]
Ok, thanks for finding this one.  It exposed some corner case issues with awaitCompletion which was called by stopJob (I changed stopJob to no longer call awaitCompletion) and flushAndWait.  The current behavior seems to resolve the issues I saw with running this test.

**Comment by srinathgit** [comment]
The behavior is correct now
