### ISSUE TITLE
EvalTest fails in develop branch.

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#611]
The following test fails in the nightly regression run in the EA4 server build. I don't see this test failing on Jenkins environment, where the server build used is 9.0 trunk.

```
<testsuite tests="6" failures="1" name="com.marklogic.client.test.EvalTest" time="4.448" errors="0" skipped="0">
...
...

<testcase classname="com.marklogic.client.test.EvalTest" name="test_582_need_privilege" time="0.006">
    <failure message="a FailedRequestException should have been thrown since rest_admin doesn't have eval privileges" type="java.lang.AssertionError">java.lang.AssertionError: a FailedRequestException should have been thrown since rest_admin doesn't have eval privileges
	at org.junit.Assert.fail(Assert.java:88)
	at com.marklogic.client.test.EvalTest.test_582_need_privilege(EvalTest.java:463)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</failure>
```

**Comment by sammefford** [comment]
Is the develop branch used for both regression and the Jenkins environment where the server build used is 9.0 trunk?

Can you get the wire trace from each env?  I'm guessing that we're getting HTTP status 403 from EA4 and 428 from 9.0 trunk.  If that's true, then we should back out my changes to support the 428 status for EA4.

**Comment by sammefford** [comment]
Does the rest_admin role have the eval permission?  It should not . . .

**Comment by georgeajit** [comment]
On checking on a EA4 nightly regression server, I don't see rest-admin role having eval permission.

**Comment by georgeajit** [comment]
<<Is the develop branch used for both regression and the Jenkins environment where the server build used is 9.0 trunk?>>
Yes, "develop" branch is used for both regression and Jenkins environment where the server build used is 9.0 trunk.
Could like to wait a day to see EA4 nightly regression test results. We were having some EA4 related environment issues, since EA4 branched out.

**Comment by sammefford** [comment]
Ajit, is this issue still occurring?

**Comment by georgeajit** [comment]
Yes.

**Comment by georgeajit** [comment]
I did a clean install of MarkLogic Server on nightly regression server and ran the entire Dev. JUnit tests. This test does not fail. This tells me that some other test suite (other than Java Client API suite) is setting the rest_admin role's eval permission even before Java suite is run.

Here is the result:
```
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="6" failures="0" name="com.marklogic.client.test.EvalTest" time="5.935" errors="0" skipped="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/home/builder/java/jdk1.8.0_72/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.72-b15"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/space/builder/builds/linux64/b9_0/java-client-api-dev"/>
    <property name="java.runtime.version" value="1.8.0_72-b15"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/home/builder/java/jdk1.8.0_72/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/home/builder/mvn/apache-maven-3.2.5/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value=".:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="maven.repo.local" value="/tmp/java-client"/>
    <property name="os.version" value="3.10.0-514.16.1.el7.x86_64"/>
    <property name="user.home" value="/home/builder"/>
    <property name="user.timezone" value="America/Los_Angeles"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="user.name" value="builder"/>
    <property name="java.class.path" value="/home/builder/mvn/apache-maven-3.2.5/boot/plexus-classworlds-2.5.2.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/home/builder/java/jdk1.8.0_72/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher test -Dmaven.repo.local=/tmp/java-client"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_72"/>
    <property name="java.ext.dirs" value="/home/builder/java/jdk1.8.0_72/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/home/builder/java/jdk1.8.0_72/jre/lib/resources.jar:/home/builder/java/jdk1.8.0_72/jre/lib/rt.jar:/home/builder/java/jdk1.8.0_72/jre/lib/sunrsasign.jar:/home/builder/java/jdk1.8.0_72/jre/lib/jsse.jar:/home/builder/java/jdk1.8.0_72/jre/lib/jce.jar:/home/builder/java/jdk1.8.0_72/jre/lib/charsets.jar:/home/builder/java/jdk1.8.0_72/jre/lib/jfr.jar:/home/builder/java/jdk1.8.0_72/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/home/builder/mvn/apache-maven-3.2.5"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase classname="com.marklogic.client.test.EvalTest" name="test_171" time="1.721"/>
  <testcase classname="com.marklogic.client.test.EvalTest" name="evalHelloWorld" time="0.012"/>
  <testcase classname="com.marklogic.client.test.EvalTest" name="evalAndInvokeJavascript" time="1.395"/>
  <testcase classname="com.marklogic.client.test.EvalTest" name="test_582_need_privilege" time="0.008"/>
  <testcase classname="com.marklogic.client.test.EvalTest" name="getNullTests" time="0.011"/>
  <testcase classname="com.marklogic.client.test.EvalTest" name="evalAndInvokeXQuery" time="2.788"/>
</testsuite>
```

From stdout.log

```
Running com.marklogic.client.test.EvalTest
17:28:32.296 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8012 as rest-evaluator
17:28:32.323 [main] DEBUG c.m.client.impl.JerseyServices - Opening transaction
17:28:33.415 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:28:33.415 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:28:34.004 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:34.009 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:34.012 [main] DEBUG c.m.client.impl.JerseyServices - Completing transaction 14831378145684717293 with rollback
17:28:34.018 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:34.027 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:34.033 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:34.038 [main] DEBUG c.m.client.impl.JerseyServices - Putting /ext/test/evaltest.sjs
17:28:34.047 [main] DEBUG c.m.client.impl.JerseyServices - Posting invoke
17:28:34.056 [main] DEBUG c.m.client.impl.JerseyServices - Deleting /ext/test/evaltest.sjs
17:28:35.426 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:35.434 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:35.436 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:35.439 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:35.441 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:35.443 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:35.448 [main] DEBUG com.marklogic.client.io.DOMHandle - Serializing DOM document to output stream
17:28:35.449 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:28:35.473 [main] DEBUG c.m.client.impl.JerseyServices - Putting /ext/test/evaltest.xqy
17:28:36.887 [main] DEBUG com.marklogic.client.io.DOMHandle - Serializing DOM document to output stream
17:28:36.887 [main] DEBUG c.m.client.impl.JerseyServices - Posting invoke
17:28:36.914 [main] DEBUG c.m.client.impl.JerseyServices - Deleting /ext/test/evaltest.xqy
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.938 sec

...
...
Results :

Tests in error: 
  test_issue_623(com.marklogic.client.test.BulkReadWriteTest): Local message: write failed: Bad Request. Server Message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: invalid uri: BulkReadWriteTest_5751/test\with\backslash.txt

Tests run: 672, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:04 min
[INFO] Finished at: 2017-06-14T17:31:16-07:00
[INFO] Final Memory: 24M/477M

```

**Comment by georgeajit** [comment]
This test does not fail when run locally on the Linux box using ```mvn test``` command.  Shipping this issue for the time being because this is now an test order issue.
