### ISSUE TITLE
OptimisticLockingTest fails with "DOMHandle supports the XML format only"

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#651]
java.lang.IllegalArgumentException: DOMHandle supports the XML format only
	at com.marklogic.client.io.DOMHandle.setFormat(DOMHandle.java:162)
	at com.marklogic.client.impl.JerseyServices.copyDescriptor(JerseyServices.java:1834)
	at com.marklogic.client.impl.JerseyServices.getDocumentImpl(JerseyServices.java:798)
	at com.marklogic.client.impl.JerseyServices.getDocument(JerseyServices.java:661)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:389)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:345)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:290)
	at com.marklogic.client.example.cookbook.OptimisticLocking.modifyDatabase(OptimisticLocking.java:121)
	at com.marklogic.client.example.cookbook.OptimisticLocking.run(OptimisticLocking.java:57)
	at com.marklogic.client.example.cookbook.OptimisticLocking.main(OptimisticLocking.java:46)
	at com.marklogic.client.test.example.cookbook.OptimisticLockingTest.testMain(OptimisticLockingTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Standard Output

example: com.marklogic.client.example.cookbook.OptimisticLocking
12:10:09.075 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8000 as rest-admin
12:10:09.105 [main] INFO  c.m.c.i.ServerConfigurationManagerImpl - Reading server configuration
12:10:09.105 [main] DEBUG c.m.client.impl.JerseyServices - Getting config/properties
12:10:09.793 [main] INFO  c.m.c.i.ServerConfigurationManagerImpl - Writing server configuration
12:10:09.793 [main] DEBUG c.m.client.impl.JerseyServices - Putting config/properties/null
enabled optimistic locking
12:10:09.813 [main] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.813 [main] DEBUG c.m.client.impl.JerseyServices - Releasing connection
12:10:09.813 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8000 as rest-writer
12:10:09.833 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.834 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.839 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.839 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.839 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.839 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.840 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.840 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.840 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.840 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.840 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
12:10:09.852 [main] INFO  c.m.client.impl.DocumentManagerImpl - Writing content for /example/flipper.xml
12:10:09.852 [main] DEBUG c.m.client.impl.JerseyServices - Sending /example/flipper.xml document in transaction null
12:10:10.283 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for /example/flipper.xml
12:10:10.283 [main] DEBUG c.m.client.impl.JerseyServices - Getting /example/flipper.xml in transaction null

**Comment by grechaw** [comment]
I would not be surprised if this is exposed because of server bug 43944.
I found that some tests failed due to this regression.  You can fix around it, but it's not something that should require this.

**Comment by georgeajit** [comment]
Ran the test on MarkLogic Server Build 02212017 on the local Linux box. The test passed.
