### ISSUE TITLE
Unhandled exception when whitelisting a non-existent host

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#663]
The following test throws ArithmeticException when using a white list with an unknown host. 

```
	@Test
	public void testNullConfig() throws Exception{
		Assume.assumeTrue(hostNames.length > 1);
		
		final String query1 = "fn:count(fn:doc())";
			
		try{
			DocumentMetadataHandle meta6 = new DocumentMetadataHandle().withCollections("NoHost").withQuality(0);
			
			Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 0);
			
			WriteBatcher ihb2 =  dmManager.newWriteBatcher();
			
			FilteredForestConfiguration forestConfig = new FilteredForestConfiguration(dmManager.readForestConfig())
					    .withRenamedHost("rh7v-intel64-90-test-8.marklogic.com", "rh7v-intel64-90-test-9.marklogic.com")
					    .withRenamedHost("rh7v-intel64-90-test-9.marklogic.com","rh7v-intel64-90-test-8.marklogic.com")
					    .withWhiteList("asdf");
					    
								
			ihb2.withBatchSize(50).withForestConfig(forestConfig);
				
			ihb2.onBatchSuccess(
			        batch -> {
			        	}
			        )
			        .onBatchFailure(
			          (batch, throwable) -> {
			        	  throwable.printStackTrace();
			          
			          }
			);
			for (int j =0 ;j < 1000; j++){
				String uri ="/local/string-"+ j;
				ihb2.addAs(uri, meta6 , jsonNode);
			}
			
		
			ihb2.flushAndWait();
		
			Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 1000);
}
```

Exception:

```
java.lang.ArithmeticException: / by zero
	at com.marklogic.client.datamovement.FilteredForestConfiguration.replaceHost(FilteredForestConfiguration.java:158)
	at com.marklogic.client.datamovement.FilteredForestConfiguration.lambda$5(FilteredForestConfiguration.java:141)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at com.marklogic.client.datamovement.FilteredForestConfiguration.listForests(FilteredForestConfiguration.java:150)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.withForestConfig(WriteBatcherImpl.java:776)
	at com.marklogic.client.datamovement.functionaltests.WriteHostBatcherTest.testNullConfig(WriteHostBatcherTest.java:2562)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by srinathgit** [comment]
The same exception is thrown with this test as well were a host is blacklisted

```
@Test
	public void testBlackList() throws Exception{
		Assume.assumeTrue(hostNames.length > 1);
		
		final String query1 = "fn:count(fn:doc())";
			
		try{
			DocumentMetadataHandle meta6 = new DocumentMetadataHandle().withCollections("NoHost").withQuality(0);
			
			Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 0);
			
			WriteBatcher ihb2 =  dmManager.newWriteBatcher();
			
			FilteredForestConfiguration forestConfig = new FilteredForestConfiguration(dmManager.readForestConfig())
					    //.withRenamedHost("rh7v-intel64-90-test-8.marklogic.com", "rh7v-intel64-90-test-9.marklogic.com")
					    .withRenamedHost("rh7v-intel64-90-test-9.marklogic.com","rh7v-intel64-90-test-8.marklogic.com")
					    .withBlackList("rh7v-intel64-90-test-8.marklogic.com");
								
			ihb2.withBatchSize(50).withForestConfig(forestConfig);
				
			ihb2.onBatchSuccess(
			        batch -> {
			        	}
			        )
			        .onBatchFailure(
			          (batch, throwable) -> {
			        	  throwable.printStackTrace();
			          
			          }
			);
			for (int j =0 ;j < 1000; j++){
				String uri ="/local/string-"+ j;
				ihb2.addAs(uri, meta6 , jsonNode);
			}
			
		
			ihb2.flushAndWait();
		

}			
```

**Comment by srinathgit** [comment]
It happens essentially when length of 'vaildHosts' array is 0 . The same exception is thrown in this case as well

example: (Considering a 2 node cluster "rh7v-intel64-90-test-9.marklogic.com","rh7v-intel64-90-test-8.marklogic.com")

		FilteredForestConfiguration forestConfig = new FilteredForestConfiguration(dmManager.readForestConfig())
				 	    .withRenamedHost("rh7v-intel64-90-test-9.marklogic.com","rh7v-intel64-90-test-8.marklogic.com")
				    .withWhiteList("rh7v-intel64-90-test-9.marklogic.com");

**Comment by srinathgit** [comment]
Verified that ArithmeticException is no longer thrown and IllegalStateException is thrown when there are no valid hosts
