### ISSUE TITLE
Handle NPE when FilteredForestConfig is null

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#664]
Handle NPE when FilteredForestConfig is null

```
@Test
	public void testNullConfig() throws Exception{
		final String query1 = "fn:count(fn:doc())";
			
		try{
			DocumentMetadataHandle meta6 = new DocumentMetadataHandle().withCollections("NoHost").withQuality(0);
			
			Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 0);
			
			WriteBatcher ihb2 =  dmManager.newWriteBatcher();
			
			FilteredForestConfiguration forestConfig = null;
								
			ihb2.withBatchSize(50).withForestConfig(forestConfig);
				
			ihb2.onBatchSuccess(
			        batch -> {
			        	}
			        )
			        .onBatchFailure(
			          (batch, throwable) -> {
			        	  throwable.printStackTrace();
			          
			          }
			);
			for (int j =0 ;j < 1000; j++){
				String uri ="/local/string-"+ j;
				ihb2.addAs(uri, meta6 , jsonNode);
			}
			
		
			ihb2.flushAndWait();
		
			Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 1000);
			
			
		}
		catch(Exception e){
			e.printStackTrace();
		}
				
	}
```

Exception:

```
java.lang.NullPointerException
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.withForestConfig(WriteBatcherImpl.java:776)
	at com.marklogic.client.datamovement.functionaltests.WriteHostBatcherTest.testNullConfig(WriteHostBatcherTest.java:2559)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by srinathgit** [comment]
Verified NPE is handled and added test testNullConfig()
