### ISSUE TITLE
Unit test failure: RowManagerTest.testResultRowDocs line 390

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#681]
org.w3c.dom.ls.LSException: The prefix "prop" for element "prop:properties" is not bound.
	at org.apache.xerces.parsers.DOMParserImpl.parse(Unknown Source)
	at com.marklogic.client.io.DOMHandle.receiveContent(DOMHandle.java:403)
	at com.marklogic.client.io.DOMHandle.receiveContent(DOMHandle.java:60)
	at com.marklogic.client.impl.JerseyServices$JerseyResult.getContent(JerseyServices.java:4454)
	at com.marklogic.client.impl.RowManagerImpl$RowSetHandleBase.next(RowManagerImpl.java:860)
	at com.marklogic.client.test.RowManagerTest.checkXMLDocRows(RowManagerTest.java:970)
	at com.marklogic.client.test.RowManagerTest.testResultRowDocs(RowManagerTest.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: ::::4:52:259:The prefix "prop" for element "prop:properties" is not bound.
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	... 38 more
Standard Output

06:13:19.633 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
06:13:19.633 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
06:13:20.575 [main] DEBUG c.m.client.impl.JerseyServices - Posting rows
06:13:20.687 [main] INFO  c.m.client.io.XMLStreamReaderHandle - Parsing StAX stream from input stream
06:13:20.688 [main] DEBUG com.marklogic.client.io.DOMHandle - Parsing DOM document from input stream
Standard Error

[Fatal Error] :4:52: The prefix "prop" for element "prop:properties" is not bound.

**Comment by ehennum** [comment]
Something turned on the automatic maintain last modified property for the Java unit test database, which is creating properties documents now.  That's not the default and not recommended, so the unit test database shouldn't have that enabled.

However, this bug exposes two other issues:

1.  Should document joins be restricted to content documents and not properties?  I need to think about the implications for joining document property fragments.

2.  Why isn't the namespace declaration serialized?  Possibly a row serialization bug.

**Comment by ehennum** [comment]
Now that I'm off the train, I can see that the setup for the Java unit test database has had last-modified for a long time.

Created server bug 44875 for the two issues mentioned in the previous comment.

**Comment by ehennum** [comment]
With the workaround, the regression should be gone now.

**Comment by georgeajit** [comment]
Verified with MarkLogic Server build 20170303 on Linux server. This test passed.
