### ISSUE TITLE
To fix unit test BulkReadWriteTest.test_issue_623 we need to escape backslashes in uris

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#689]
Currently documentManager.write(documentWriteSet) doesn't escape any uris it sends through.  This leads to an error when a uri contains a backslash.  Right now BulkReadWriteTest.test_issue_623 is able to insert a doc with a uri like BulkReadWriteTest_5255/test\with\backslash.txt but is unable to find the same document because it goes into the database as BulkReadWriteTest_5255/testwithbackslash.txt

**Comment by sammefford** [comment]
Error Message

You should have one and only one doc with uri=[BulkReadWriteTest_5255/test\with\backslash.txt] expected:<1> but was:<0>
Stacktrace

java.lang.AssertionError: You should have one and only one doc with uri=[BulkReadWriteTest_5255/test\with\backslash.txt] expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at com.marklogic.client.test.BulkReadWriteTest.test_issue_623_body(BulkReadWriteTest.java:789)
	at com.marklogic.client.test.BulkReadWriteTest.test_issue_623(BulkReadWriteTest.java:754)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Standard Output

06:10:05.203 [main] INFO  c.m.client.impl.DocumentManagerImpl - Writing content for BulkReadWriteTest_5255/test_with_ampersand.txt?a=b&c=d
06:10:05.203 [main] DEBUG c.m.client.impl.JerseyServices - Sending BulkReadWriteTest_5255/test_with_ampersand.txt?a=b&c=d document in transaction null
06:10:06.603 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for multiple uris beginning with BulkReadWriteTest_5255/test_with_ampersand.txt?a=b&c=d
06:10:06.603 [main] DEBUG c.m.client.impl.JerseyServices - Getting documents as null
06:10:07.251 [main] INFO  c.m.client.impl.DocumentManagerImpl - Deleting BulkReadWriteTest_5255/test_with_ampersand.txt?a=b&c=d
06:10:07.251 [main] DEBUG c.m.client.impl.JerseyServices - Deleting BulkReadWriteTest_5255/test_with_ampersand.txt?a=b&c=d in transaction null
06:10:07.834 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for BulkReadWriteTest_5255/test_with_ampersand.txt?a=b&c=d
06:10:07.834 [main] DEBUG c.m.client.impl.JerseyServices - Getting BulkReadWriteTest_5255/test_with_ampersand.txt?a=b&c=d in transaction null
06:10:08.924 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
06:10:08.925 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
06:10:09.482 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for multiple uris beginning with BulkReadWriteTest_5255/test_with_ampersand.txt?a=b&c=d
06:10:09.483 [main] DEBUG c.m.client.impl.JerseyServices - Getting documents as null
06:10:09.488 [main] DEBUG c.m.client.impl.JerseyServices - Deleting documents
06:10:09.491 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for BulkReadWriteTest_5255/test_with_ampersand.txt?a=b&c=d
06:10:09.491 [main] DEBUG c.m.client.impl.JerseyServices - Getting BulkReadWriteTest_5255/test_with_ampersand.txt?a=b&c=d in transaction null
06:10:09.498 [main] INFO  c.m.client.impl.DocumentManagerImpl - Writing content for BulkReadWriteTest_5255/test+with+plus.txt
06:10:09.498 [main] DEBUG c.m.client.impl.JerseyServices - Sending BulkReadWriteTest_5255/test+with+plus.txt document in transaction null
06:10:09.503 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for multiple uris beginning with BulkReadWriteTest_5255/test+with+plus.txt
06:10:09.503 [main] DEBUG c.m.client.impl.JerseyServices - Getting documents as null
06:10:09.506 [main] INFO  c.m.client.impl.DocumentManagerImpl - Deleting BulkReadWriteTest_5255/test+with+plus.txt
06:10:09.506 [main] DEBUG c.m.client.impl.JerseyServices - Deleting BulkReadWriteTest_5255/test+with+plus.txt in transaction null
06:10:09.509 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for BulkReadWriteTest_5255/test+with+plus.txt
06:10:09.509 [main] DEBUG c.m.client.impl.JerseyServices - Getting BulkReadWriteTest_5255/test+with+plus.txt in transaction null
06:10:09.514 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
06:10:09.514 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
06:10:09.517 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for multiple uris beginning with BulkReadWriteTest_5255/test+with+plus.txt
06:10:09.517 [main] DEBUG c.m.client.impl.JerseyServices - Getting documents as null
06:10:09.521 [main] DEBUG c.m.client.impl.JerseyServices - Deleting documents
06:10:09.525 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for BulkReadWriteTest_5255/test+with+plus.txt
06:10:09.525 [main] DEBUG c.m.client.impl.JerseyServices - Getting BulkReadWriteTest_5255/test+with+plus.txt in transaction null
06:10:09.531 [main] INFO  c.m.client.impl.DocumentManagerImpl - Writing content for BulkReadWriteTest_5255/test/with/forwardslash.txt
06:10:09.531 [main] DEBUG c.m.client.impl.JerseyServices - Sending BulkReadWriteTest_5255/test/with/forwardslash.txt document in transaction null
06:10:09.535 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for multiple uris beginning with BulkReadWriteTest_5255/test/with/forwardslash.txt
06:10:09.535 [main] DEBUG c.m.client.impl.JerseyServices - Getting documents as null
06:10:09.539 [main] INFO  c.m.client.impl.DocumentManagerImpl - Deleting BulkReadWriteTest_5255/test/with/forwardslash.txt
06:10:09.539 [main] DEBUG c.m.client.impl.JerseyServices - Deleting BulkReadWriteTest_5255/test/with/forwardslash.txt in transaction null
06:10:09.541 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for BulkReadWriteTest_5255/test/with/forwardslash.txt
06:10:09.541 [main] DEBUG c.m.client.impl.JerseyServices - Getting BulkReadWriteTest_5255/test/with/forwardslash.txt in transaction null
06:10:09.546 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
06:10:09.546 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
06:10:09.550 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for multiple uris beginning with BulkReadWriteTest_5255/test/with/forwardslash.txt
06:10:09.550 [main] DEBUG c.m.client.impl.JerseyServices - Getting documents as null
06:10:09.553 [main] DEBUG c.m.client.impl.JerseyServices - Deleting documents
06:10:09.557 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for BulkReadWriteTest_5255/test/with/forwardslash.txt
06:10:09.557 [main] DEBUG c.m.client.impl.JerseyServices - Getting BulkReadWriteTest_5255/test/with/forwardslash.txt in transaction null
06:10:09.563 [main] INFO  c.m.client.impl.DocumentManagerImpl - Writing content for BulkReadWriteTest_5255/test\with\backslash.txt
06:10:09.563 [main] DEBUG c.m.client.impl.JerseyServices - Sending BulkReadWriteTest_5255/test\with\backslash.txt document in transaction null
06:10:09.567 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for multiple uris beginning with BulkReadWriteTest_5255/test\with\backslash.txt
06:10:09.567 [main] DEBUG c.m.client.impl.JerseyServices - Getting documents as null
06:10:09.571 [main] INFO  c.m.client.impl.DocumentManagerImpl - Deleting BulkReadWriteTest_5255/test\with\backslash.txt
06:10:09.571 [main] DEBUG c.m.client.impl.JerseyServices - Deleting BulkReadWriteTest_5255/test\with\backslash.txt in transaction null
06:10:09.574 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for BulkReadWriteTest_5255/test\with\backslash.txt
06:10:09.574 [main] DEBUG c.m.client.impl.JerseyServices - Getting BulkReadWriteTest_5255/test\with\backslash.txt in transaction null
06:10:09.579 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
06:10:09.579 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
06:10:09.583 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for multiple uris beginning with BulkReadWriteTest_5255/test\with\backslash.txt
06:10:09.583 [main] DEBUG c.m.client.impl.JerseyServices - Getting documents as null
 Help us localize this page Page generated: Mar 14, 2017 3:19:34 PMREST APIJenkins ver. 1.590

**Comment by georgeajit** [comment]
Ran the test with latest pull and on MarkLogic Server Build 20170315. The test ran fine. Used the local Linux box to run the tests.
