### ISSUE TITLE
QueryBatcherTest.testStructuredQuery failing intermittently

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#695]
It appears the test is too strict because for some reason forest assignment isn't always consistent.  So sometimes docs are in a different forest than expected.

```
java.lang.AssertionError: Missing uri=[/QueryBatcherTest/content_5.json] from forest=[java-unittest-2]
	at org.junit.Assert.fail(Assert.java:88)
	at com.marklogic.client.test.datamovement.QueryBatcherTest.runQueryBatcher(QueryBatcherTest.java:334)
	at com.marklogic.client.test.datamovement.QueryBatcherTest.testStructuredQuery(QueryBatcherTest.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Standard Output

06:02:27.738 [main] INFO  c.m.c.d.impl.QueryBatcherImpl - (withForestConfig) Using [localhost] hosts with forests for "java-unittest"
06:02:27.738 [main] INFO  c.m.c.d.impl.QueryBatcherImpl - Starting job batchSize=1, threadCount=2, onUrisReady listeners=2, failure listeners=3
06:02:27.739 [pool-47-thread-2] DEBUG c.m.client.impl.JerseyServices - Query uris with structured query <query xmlns="http://marklogic.com/appservices/search" xmlns:search="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><collection-query><uri>QueryBatcherTest_5570</uri></collection-query></query>
06:02:27.739 [pool-47-thread-1] DEBUG c.m.client.impl.JerseyServices - Query uris with structured query <query xmlns="http://marklogic.com/appservices/search" xmlns:search="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><collection-query><uri>QueryBatcherTest_5570</uri></collection-query></query>
06:02:27.739 [pool-47-thread-2] DEBUG c.m.client.impl.JerseyServices - Getting internal/uris as text/uri-list
06:02:27.739 [pool-47-thread-1] DEBUG c.m.client.impl.JerseyServices - Getting internal/uris as text/uri-list
06:02:27.748 [pool-47-thread-2] DEBUG c.m.client.impl.JerseyServices - Query uris with structured query <query xmlns="http://marklogic.com/appservices/search" xmlns:search="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><collection-query><uri>QueryBatcherTest_5570</uri></collection-query></query>
06:02:27.748 [pool-47-thread-1] DEBUG c.m.client.impl.JerseyServices - Query uris with structured query <query xmlns="http://marklogic.com/appservices/search" xmlns:search="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><collection-query><uri>QueryBatcherTest_5570</uri></collection-query></query>
06:02:27.748 [pool-47-thread-2] DEBUG c.m.client.impl.JerseyServices - Getting internal/uris as text/uri-list
06:02:27.748 [pool-47-thread-1] DEBUG c.m.client.impl.JerseyServices - Getting internal/uris as text/uri-list
06:02:27.754 [pool-47-thread-1] DEBUG c.m.client.impl.JerseyServices - Query uris with structured query <query xmlns="http://marklogic.com/appservices/search" xmlns:search="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><collection-query><uri>QueryBatcherTest_5570</uri></collection-query></query>
06:02:27.754 [pool-47-thread-1] DEBUG c.m.client.impl.JerseyServices - Getting internal/uris as text/uri-list
06:02:27.754 [pool-47-thread-2] DEBUG c.m.client.impl.JerseyServices - Query uris with structured query <query xmlns="http://marklogic.com/appservices/search" xmlns:search="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><collection-query><uri>QueryBatcherTest_5570</uri></collection-query></query>
06:02:27.754 [pool-47-thread-2] DEBUG c.m.client.impl.JerseyServices - Getting internal/uris as text/uri-list
06:02:27.760 [pool-47-thread-1] DEBUG c.m.client.impl.JerseyServices - Query uris with structured query <query xmlns="http://marklogic.com/appservices/search" xmlns:search="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><collection-query><uri>QueryBatcherTest_5570</uri></collection-query></query>
06:02:27.760 [pool-47-thread-1] DEBUG c.m.client.impl.JerseyServices - Getting internal/uris as text/uri-list
06:02:27.765 [pool-47-thread-1] DEBUG c.m.client.impl.JerseyServices - Query uris with structured query <query xmlns="http://marklogic.com/appservices/search" xmlns:search="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><collection-query><uri>QueryBatcherTest_5570</uri></collection-query></query>
06:02:27.765 [pool-47-thread-1] DEBUG c.m.client.impl.JerseyServices - Getting internal/uris as text/uri-list
06:02:27.771 [main] INFO  c.m.c.d.impl.QueryBatcherImpl - Job complete, jobBatchNumber=8, jobResultsSoFar=5
06:02:27.771 [main] DEBUG c.m.client.impl.JerseyServices - Searching for structure <query xmlns="http://marklogic.com/appservices/search" xmlns:search="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><collection-query><uri>QueryBatcherTest_5570</uri></collection-query></query>
06:02:27.783 [main] ERROR c.m.c.t.d.QueryBatcherTest - Results found for forest java-unittest-1: [/QueryBatcherTest/content_3.json, /QueryBatcherTest/content_4.json, /QueryBatcherTest/content_1.json]
06:02:27.783 [main] ERROR c.m.c.t.d.QueryBatcherTest - Results found for forest java-unittest-3: [/QueryBatcherTest/content_2.json]
```

**Comment by sammefford** [comment]
The good news is this had nothing to do with docs going to different forests.  This was once again my mistake of using a non-thread-safe collection in a listener.  I've set a good example by replacing it with a thread-safe collection: in this case, ConcurrentHashMap.

**Comment by sammefford** [comment]
@georgeajit : No new tests required, just watch for this test to not fail intermittently anymore.

**Comment by georgeajit** [comment]
Will watch the test for tomorrow (04/14/2017) and comment.

**Comment by georgeajit** [comment]
Fixed.
