### ISSUE TITLE
RawQueryDefinitionTest.testCombinedSearches line 195: AssertionError: Mime type of document

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#70]
java.lang.AssertionError: Mime type of document
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at com.marklogic.client.test.RawQueryDefinitionTest.checkResults(RawQueryDefinitionTest.java:168)
    at com.marklogic.client.test.RawQueryDefinitionTest.check(RawQueryDefinitionTest.java:156)
    at com.marklogic.client.test.RawQueryDefinitionTest.check(RawQueryDefinitionTest.java:183)
    at com.marklogic.client.test.RawQueryDefinitionTest.testCombinedSearches(RawQueryDefinitionTest.java:195)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by sammefford** [comment]
In most of the other unit tests, I address this by writing the documents to a collection unique for that run, then querying specific to that collection.  However, this test depends on documents loaded by the bootstrap.  Perhaps the answer is to make this test write its own documents to a unique collection the way other tests do.  On the other hand, I should reconsider the bootstrap approach or [ml-app-loader](https://github.com/rjrudin/ml-app-deployer) since it should speed unit tests, so we can be in the habit of running them more often.

I'm going to postpone working on this so I can consider it with those options, and perhaps as part of a bootstrap process change.  This isn't urgent since it doesn't happen on a freshly boot-strapped database.
