### ISSUE TITLE
Stress test client throws XDMP-DOCBADCHAR for nquad on content load.

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#735]
Running the Java/REST stress test with 9.0-2 throws exception at document write with nquad  type.
```
2017-04-28 10:16:33 (Thread=45) ERROR writing graph /BVQHLJIHXIQVOAAK/2017328101524236/15/05triples-utf16.nt with mimetype application/n-triples without transaction
2017-04-28 10:16:33 (Thread=45) com.marklogic.client.FailedRequestException: Local message: failed to apply resource at graphs: Internal Server Error. Server Message: XDMP-DOCBADCHAR: xdmp:nquad($body, $options) -- Unexpected character found: '�' (0xfffd) at :1:0 . See the MarkLogic server error log for further detail.
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at graphs: Internal Server Error. Server Message: XDMP-DOCBADCHAR: xdmp:nquad($body, $options) -- Unexpected character found: '�' (0xfffd) at :1:0 . See the MarkLogic server error log for further detail.
        at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4311)
        at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3218)
        at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3171)
        at com.marklogic.client.impl.JerseyServices.mergeGraph(JerseyServices.java:5053)
        at com.marklogic.client.impl.GraphManagerImpl.merge(GraphManagerImpl.java:203)
        at test.stress.JavaAPISession.mergeGraph(JavaAPISession.java:671)
        at test.stress.SemanticGraphLoadTester.putDocument(SemanticGraphLoadTester.java:22)
        at test.stress.RestLoadTester.loadContentFromDir(RestLoadTester.java:188)
        at test.stress.RestLoadTester.runTest(RestLoadTester.java:278)
        at test.stress.StressTest.run(StressTest.java:378)
2017-04-28 10:16:33 (Thread=45) Test took: 69298ms

```

**Comment by sammefford** [comment]
I had to add an option to parse utf-16 encoded files because the files names 0n3-utf16.n3, 0trig-utf16.trig, 5triples-utf16.nt, livesIn-utf16.ttl, rdfxml1-utf16.rdf, etc. indicate they're utf16  encoded.  The change (revision 268438) resolved the issue.

**Comment by georgeajit** [comment]
@sammefford , Could you please check in the fix into QA 9_0 branch in the SVN repository? I verified the Stress run using the Trunk branch (revision 268438). You may ship it or assign it back to me for recheck.

**Comment by sammefford** [comment]
@georgeajit I committed revision 269839 to qa/branches/b9_0.  I couldn't test because stress/widowmaker/run-rest.sh isn't running without errors, and it appears that branch is out of date.  Both lib/marklogic-client-api-4.0-SNAPSHOT.jar and lib/marklogic-client-api-5.0-SNAPSHOT.jar haven't been updated in 6 weeks, so they're not using Java Client API 4.0.2.  Reassigning to you as we discussed.

**Comment by georgeajit** [comment]
Verified on Stress test run dated 03/20/2018. The issue is fixed.
