### ISSUE TITLE
I got an IllegalStateException error using the Data Movement SDK

### ISSUE THREAD

**Issue by lcahlander** [marklogic/java-client-api#746]
This happened after running for over a day.

Here is the error:

```
27-May-2017 12:27:49.622 SEVERE [http-nio-8080-exec-39] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [HarvestJDBCDataServlet] in context with path [/easymetahub] threw exception [java.lang.IllegalStateException: This instance has been stopped] with root cause
 java.lang.IllegalStateException: This instance has been stopped
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.requireNotStopped(WriteBatcherImpl.java:347)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.add(WriteBatcherImpl.java:283)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.add(WriteBatcherImpl.java:267)
	at com.easymetahub.HarvestJDBCData.doRoot(HarvestJDBCData.java:485)
	at com.easymetahub.HarvestJDBCData.doSomething(HarvestJDBCData.java:224)
	at com.easymetahub.HarvestJDBCData.processBatchSegment(HarvestJDBCData.java:120)
	at com.easymetahub.HarvestJDBCDataServlet.doPost(HarvestJDBCDataServlet.java:33)
	at com.easymetahub.HarvestJDBCDataServlet.doGet(HarvestJDBCDataServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:232)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:105)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1078)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1524)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by georgeajit** [comment]
Can you please provide some more details such as MarkLogic server versions, platform, sample workflow steps etc. to help us reproduce this issue?

**Comment by lcahlander** [comment]
Mac Pro (Late 2013)
Mac OS Sierra 10.12.5
3.5 GHz 6-core Intel Xeon E5
128 GB Ram
MarkLogic 9.0-1
Apache Tomcat 9.0.0.M3
JDK 1.8.0_101

I will attach a summary of the workflow later tonight.

**Comment by lcahlander** [comment]
I have a singleton to setup the batcher:

```
/*
 * Copyright (c) 2017. EasyMetaHub, LLC - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 *
 */

package com.easymetahub;

import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.datamovement.DataMovementManager;
import com.marklogic.client.datamovement.JobTicket;
import com.marklogic.client.datamovement.WriteBatcher;

/**
 * Created by lcahlander on 5/25/17.
 */
public class EMHMarkLogicClientSingleton {
    private static EMHMarkLogicClientSingleton ourInstance;
    private DatabaseClient client = null;
    private DataMovementManager dmm = null;
    private WriteBatcher batcher = null;
    private  JobTicket ticket = null;

    public static EMHMarkLogicClientSingleton getInstance() {

        if (ourInstance == null) {
            synchronized (EMHMarkLogicClientSingleton.class) {
                if (ourInstance == null) {
                    ourInstance =new EMHMarkLogicClientSingleton();
                }
            }
        }
        return ourInstance;
    }

    private EMHMarkLogicClientSingleton() {
        client = DatabaseClientFactory.newClient("localhost", 8000, "emh-entity-manager-content", new DatabaseClientFactory.DigestAuthContext("admin", "mladmin"));
        dmm = client.newDataMovementManager();
        batcher = dmm.newWriteBatcher();
        batcher = dmm.newWriteBatcher();
        batcher.withBatchSize(100)
                .withThreadCount(100)
                .onBatchSuccess(batch-> {
                    System.out.println(
                            batch.getTimestamp().getTime() +
                                    " documents written: " +
                                    batch.getJobWritesSoFar());
                })
                .onBatchFailure((batch,throwable) -> {
                    System.out.println("Failure on");
                    throwable.printStackTrace();
                });
        ticket = dmm.startJob(batcher);


    }

    public DatabaseClient getClient() {
        return client;
    }

    public DataMovementManager getDmm() {
        return dmm;
    }

    public WriteBatcher getBatcher() {
        return batcher;
    }

    public  JobTicket getTicket() {
        return ticket;
    }
}
```

I then have a servlet that calls:

```
client = EMHMarkLogicClientSingleton.getInstance().getClient();
XMLDocumentManager docMgr = client.newXMLDocumentManager();
DataMovementManager dmm = EMHMarkLogicClientSingleton.getInstance().getDmm();
batcher = EMHMarkLogicClientSingleton.getInstance().getBatcher();
```

In each servlet, I loop through and create several XML files and use:

```
batcher.add(entityPath, getStringFromDocument(outDoc));
```

After it was running constantly for over a day, I got the error.

**Comment by sammefford** [comment]
Any idea how the batcher got stopped?

**Comment by lcahlander** [comment]
None.  That is why there is an error being reported.

**Comment by sammefford** [comment]
Can you see any other errors in your logs?

I'm not sure how to reproduce this.  Somehow your batcher is being stopped.  My suspicion is that you had connectivity issues which brought the number of available nodes below the minimum (1) so the HostAvailabilityListener shut down the job.  But if that happened, I would expect the logs to be full of information about it.  Hmm, do you have an [slf4j-compliant logging framework](https://docs.marklogic.com/javadoc/client/overview-summary.html#logging) installed?

**Comment by sammefford** [comment]
Also, could you share [enough code that I could isolate this](https://stackoverflow.com/help/mcve)?  Without an ability to reproduce this, it will be very hard to know what may need to be fixed.

**Comment by sammefford** [comment]
I wonder if this is related to #504.  @lcahlander have you continued to experience this?  If so, are you able to [share enough code that I could isolate](https://stackoverflow.com/help/mcve) this?  If I can reproduce this it will be easier to fix.

**Comment by sammefford** [comment]
Without enough information to reproduce, we cannot work on this report.
