### ISSUE TITLE
 Format of document not determined implicitly when no MIME type specified for binary files

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#758]
A test uses FileHandle to bulkload 100+ binary documents, and then test bulk read from database. After the write to database, when reading back the URIs, the format of the documents returns as ```UNKNOWN``` instead of ```BINARY```

Here is the documentation from pubs:
```
Unless the format is explicitly set when you load a document, the format of the document is determined based on the MIME type that corresponds to the URI extension of the new document. The URI extension MIME types, along with their default formats, are set in the Mimetypes section of the Admin Interface.
```
```
URI             Document Type
/path/doc.json  JSON
/path/doc.xml   XML
/path/doc.jpg   binary
/path/doc.txt   text
```
```
@Test 
	public void test3ReadMultipleBinaryDoc() throws Exception  
	  {
		 String docId[] = {"Sega-4MB.jpg"};
		 int count=1;
		 BinaryDocumentManager docMgr = client.newBinaryDocumentManager();
		 DocumentWriteSet writeset =docMgr.newWriteSet();
		 File file1= null;
		 file1 = new File("src/test/java/com/marklogic/client/functionaltest/data/" + docId[0]);
		 FileHandle h1 = new FileHandle(file1);
		 for(int i =0;i<102;i++){
			    writeset.add(DIRECTORY+"binary"+i+".jpg", h1);
			    if(count%BATCH_SIZE == 0){
			    	  docMgr.write(writeset);
			    	  writeset = docMgr.newWriteSet();
			    	}
			      count++;
		    }
		    if(count%BATCH_SIZE > 0){
		    	docMgr.write(writeset);
		 	 }
		    String uris[] = new String[102];
			 for(int i =0;i<102;i++){
			    uris[i]=DIRECTORY+"binary"+i+".jpg";
			  }
			  count=0;
			  FileHandle rh = new FileHandle();
			  DocumentPage page = docMgr.read(uris);
			  while(page.hasNext()){
			    	DocumentRecord rec = page.next();
			    	validateRecord(rec,Format.BINARY);
			    	rec.getContent(rh);
			    	assertEquals("Content length :",file1.length(),rh.get().length());
			    	count++;
			  }
			 assertEquals("document count", 102,count); 
			//Testing the multiple same uris will not read multiple records 
}

public void validateRecord(DocumentRecord record,Format type) {
	       
	        assertNotNull("DocumentRecord should never be null", record);
	        assertNotNull("Document uri should never be null", record.getUri());
	        assertTrue("Document uri should start with " + DIRECTORY, record.getUri().startsWith(DIRECTORY));
	        assertEquals("All records are expected to be in same format", type, record.getFormat());
}
```

Here is the exception seen:
```
java.lang.AssertionError: All records are expected to be in same format expected:<BINARY> but was:<UNKNOWN>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.marklogic.client.functionaltest.TestBulkReadSample1.validateRecord(TestBulkReadSample1.java:383)
	at com.marklogic.client.functionaltest.TestBulkReadSample1.test3ReadMultipleBinaryDoc(TestBulkReadSample1.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by georgeajit** [comment]
The Http wire trace does not offer much help. I do not see what is being passed on the wire, once OKHttp is in play.


AppServer already exist
and changing context database to TestBulkReadSampleDB
2017/07/05 11:43:55:885 PDT [DEBUG] BasicClientConnectionManager - Get connection for route {}->http://localhost:8002
2017/07/05 11:43:55:885 PDT [DEBUG] DefaultClientConnectionOperator - Connecting to localhost:8002
2017/07/05 11:43:55:886 PDT [DEBUG] RequestAddCookies - CookieSpec selected: default
2017/07/05 11:43:55:886 PDT [DEBUG] RequestAuthCache - Auth cache not set in the context
2017/07/05 11:43:55:886 PDT [DEBUG] RequestTargetAuthentication - Target auth state: UNCHALLENGED
2017/07/05 11:43:55:886 PDT [DEBUG] RequestProxyAuthentication - Proxy auth state: UNCHALLENGED
2017/07/05 11:43:55:886 PDT [DEBUG] DefaultHttpClient - Attempt 1 to execute request
2017/07/05 11:43:55:886 PDT [DEBUG] DefaultClientConnection - Sending request: PUT /manage/v2/servers/REST-Java-Client-API-Server/properties?server-type=http HTTP/1.1
2017/07/05 11:43:55:886 PDT [DEBUG] wire -  >> "PUT /manage/v2/servers/REST-Java-Client-API-Server/properties?server-type=http HTTP/1.1[\r][\n]"
2017/07/05 11:43:55:886 PDT [DEBUG] wire -  >> "Content-type: application/json[\r][\n]"
2017/07/05 11:43:55:886 PDT [DEBUG] wire -  >> "Content-Length: 68[\r][\n]"
2017/07/05 11:43:55:886 PDT [DEBUG] wire -  >> "Host: localhost:8002[\r][\n]"
2017/07/05 11:43:55:887 PDT [DEBUG] wire -  >> "Connection: Keep-Alive[\r][\n]"
2017/07/05 11:43:55:887 PDT [DEBUG] wire -  >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_131)[\r][\n]"
2017/07/05 11:43:55:887 PDT [DEBUG] wire -  >> "[\r][\n]"
2017/07/05 11:43:55:887 PDT [DEBUG] wire -  >> "{"content-database": "TestBulkReadSampleDB","group-name": "Default"}"
2017/07/05 11:43:55:887 PDT [DEBUG] wire -  << "HTTP/1.1 401 Unauthorized[\r][\n]"
2017/07/05 11:43:55:887 PDT [DEBUG] wire -  << "Server: MarkLogic[\r][\n]"
2017/07/05 11:43:55:888 PDT [DEBUG] wire -  << "WWW-Authenticate: Digest realm="public", qop="auth", nonce="03574e1dc57b2051121684e6e1baa0ae", opaque="f99ea5f92e8f34c4"[\r][\n]"
2017/07/05 11:43:55:888 PDT [DEBUG] wire -  << "Content-Type: text/html; charset=utf-8[\r][\n]"
2017/07/05 11:43:55:888 PDT [DEBUG] wire -  << "Content-Length: 209[\r][\n]"
2017/07/05 11:43:55:888 PDT [DEBUG] wire -  << "Connection: Keep-Alive[\r][\n]"
2017/07/05 11:43:55:888 PDT [DEBUG] wire -  << "Keep-Alive: timeout=5[\r][\n]"
2017/07/05 11:43:55:888 PDT [DEBUG] wire -  << "[\r][\n]"
2017/07/05 11:43:55:888 PDT [DEBUG] DefaultClientConnection - Receiving response: HTTP/1.1 401 Unauthorized
2017/07/05 11:43:55:888 PDT [DEBUG] DefaultHttpClient - Connection can be kept alive for 5000 MILLISECONDS
2017/07/05 11:43:55:888 PDT [DEBUG] DefaultHttpClient - Authentication required
2017/07/05 11:43:55:888 PDT [DEBUG] DefaultHttpClient - localhost:8002 requested authentication
2017/07/05 11:43:55:888 PDT [DEBUG] TargetAuthenticationStrategy - Authentication schemes in the order of preference: [Negotiate, Kerberos, NTLM, Digest, Basic]
2017/07/05 11:43:55:888 PDT [DEBUG] TargetAuthenticationStrategy - Challenge for Negotiate authentication scheme not available
2017/07/05 11:43:55:888 PDT [DEBUG] TargetAuthenticationStrategy - Challenge for Kerberos authentication scheme not available
2017/07/05 11:43:55:888 PDT [DEBUG] TargetAuthenticationStrategy - Challenge for NTLM authentication scheme not available
2017/07/05 11:43:55:889 PDT [DEBUG] TargetAuthenticationStrategy - Challenge for Basic authentication scheme not available
2017/07/05 11:43:55:889 PDT [DEBUG] DefaultHttpClient - Selected authentication options: [DIGEST [complete=true, nonce=null, nc=0]]
2017/07/05 11:43:55:889 PDT [DEBUG] wire -  << "<html xmlns="http://www.w3.org/1999/xhtml">[\n]"
2017/07/05 11:43:55:889 PDT [DEBUG] wire -  << "  <head>[\n]"
2017/07/05 11:43:55:889 PDT [DEBUG] wire -  << "    <title>401 Unauthorized</title>[\n]"
2017/07/05 11:43:55:889 PDT [DEBUG] wire -  << "    <meta name="robots" content="noindex,nofollow"/>[\n]"
2017/07/05 11:43:55:889 PDT [DEBUG] wire -  << "  </head>[\n]"
2017/07/05 11:43:55:889 PDT [DEBUG] wire -  << "  <body>[\n]"
2017/07/05 11:43:55:889 PDT [DEBUG] wire -  << "    <h1>401 Unauthorized</h1>[\n]"
2017/07/05 11:43:55:889 PDT [DEBUG] wire -  << "  </body>[\n]"
2017/07/05 11:43:55:889 PDT [DEBUG] wire -  << "</html>[\n]"
2017/07/05 11:43:55:889 PDT [DEBUG] RequestAddCookies - CookieSpec selected: default
2017/07/05 11:43:55:889 PDT [DEBUG] RequestAuthCache - Auth cache not set in the context
2017/07/05 11:43:55:889 PDT [DEBUG] RequestTargetAuthentication - Target auth state: CHALLENGED
2017/07/05 11:43:55:889 PDT [DEBUG] RequestTargetAuthentication - Generating response to an authentication challenge using digest scheme
2017/07/05 11:43:55:890 PDT [DEBUG] RequestProxyAuthentication - Proxy auth state: UNCHALLENGED
2017/07/05 11:43:55:890 PDT [DEBUG] DefaultHttpClient - Attempt 2 to execute request
2017/07/05 11:43:55:890 PDT [DEBUG] DefaultClientConnection - Sending request: PUT /manage/v2/servers/REST-Java-Client-API-Server/properties?server-type=http HTTP/1.1
2017/07/05 11:43:55:890 PDT [DEBUG] wire -  >> "PUT /manage/v2/servers/REST-Java-Client-API-Server/properties?server-type=http HTTP/1.1[\r][\n]"
2017/07/05 11:43:55:890 PDT [DEBUG] wire -  >> "Content-type: application/json[\r][\n]"
2017/07/05 11:43:55:890 PDT [DEBUG] wire -  >> "Content-Length: 68[\r][\n]"
2017/07/05 11:43:55:890 PDT [DEBUG] wire -  >> "Host: localhost:8002[\r][\n]"
2017/07/05 11:43:55:890 PDT [DEBUG] wire -  >> "Connection: Keep-Alive[\r][\n]"
2017/07/05 11:43:55:890 PDT [DEBUG] wire -  >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_131)[\r][\n]"
2017/07/05 11:43:55:890 PDT [DEBUG] wire -  >> "Authorization: Digest username="admin", realm="public", nonce="03574e1dc57b2051121684e6e1baa0ae", uri="/manage/v2/servers/REST-Java-Client-API-Server/properties?server-type=http", response="a38286f50d2a0f8cdacfb7781380ed0c", qop=auth, nc=00000001, cnonce="878b5011ce88bdb0", algorithm=MD5, opaque="f99ea5f92e8f34c4"[\r][\n]"
2017/07/05 11:43:55:890 PDT [DEBUG] wire -  >> "[\r][\n]"
2017/07/05 11:43:55:890 PDT [DEBUG] wire -  >> "{"content-database": "TestBulkReadSampleDB","group-name": "Default"}"
2017/07/05 11:43:57:203 PDT [DEBUG] wire -  << "HTTP/1.1 204 No Content[\r][\n]"
2017/07/05 11:43:57:203 PDT [DEBUG] wire -  << "Server: MarkLogic[\r][\n]"
2017/07/05 11:43:57:203 PDT [DEBUG] wire -  << "Content-Length: 0[\r][\n]"
2017/07/05 11:43:57:203 PDT [DEBUG] wire -  << "Connection: Keep-Alive[\r][\n]"
2017/07/05 11:43:57:203 PDT [DEBUG] wire -  << "Keep-Alive: timeout=5[\r][\n]"
2017/07/05 11:43:57:203 PDT [DEBUG] wire -  << "[\r][\n]"
2017/07/05 11:43:57:203 PDT [DEBUG] DefaultClientConnection - Receiving response: HTTP/1.1 204 No Content
2017/07/05 11:43:57:204 PDT [DEBUG] DefaultHttpClient - Connection can be kept alive for 5000 MILLISECONDS
2017/07/05 11:43:57:204 PDT [DEBUG] DefaultHttpClient - Authentication succeeded
2017/07/05 11:43:57:204 PDT [DEBUG] TargetAuthenticationStrategy - Caching 'digest' auth scheme for http://localhost:8002
2017/07/05 11:43:57:204 PDT [DEBUG] BasicClientConnectionManager - Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@4b20ca2b
2017/07/05 11:43:57:205 PDT [DEBUG] BasicClientConnectionManager - Connection can be kept alive for 5000 MILLISECONDS
2017/07/05 11:43:57:205 PDT [DEBUG] DefaultClientConnection - Connection 0.0.0.0:65454<->127.0.0.1:8002 closed
2017/07/05 11:43:57:205 PDT [DEBUG] DefaultClientConnection - Connection 0.0.0.0:65453<->127.0.0.1:8002 closed

....
....
11:44:16.626 [main] DEBUG c.m.client.DatabaseClientFactory - Creating new database client for server at localhost:8011
11:44:16.643 [main] DEBUG c.m.client.impl.OkHttpServices - Connecting to localhost at 8011 as rest-admin
Inside test3ReadMultipleBinaryDoc method
11:44:16.709 [main] DEBUG c.m.client.impl.OkHttpServices - Posting documents
11:44:16.710 [main] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
11:44:32.127 [main] DEBUG c.m.client.impl.OkHttpServices - Posting documents
11:44:32.127 [main] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
11:44:32.273 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for multiple uris beginning with /bulkread/binary0.jpg
11:44:32.275 [main] DEBUG c.m.client.impl.OkHttpServices - Getting documents as null
Running CleanUp script
11:44:39.738 [main] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection

**Comment by georgeajit** [comment]
REST Server Logs
```
127.0.0.1 - - [05/Jul/2017:11:44:21 -0700] "POST /v1/documents HTTP/1.1" 401 104 - "okhttp/3.6.0"
127.0.0.1 - rest-admin [05/Jul/2017:11:44:32 -0700] "POST /v1/documents HTTP/1.1" 200 20867 - "okhttp/3.6.0"
127.0.0.1 - rest-admin [05/Jul/2017:11:44:32 -0700] "POST /v1/documents HTTP/1.1" 200 495 - "okhttp/3.6.0"
127.0.0.1 - rest-admin [05/Jul/2017:11:44:39 -0700] "GET /v1/documents?category=content&uri=/bulkread/binary0.jpg&uri=/bulkread/binary1.jpg&uri=/bulkread/binary2.jpg&uri=/bulkread/binary3.jpg&uri=/bulkread/binary4.jpg&uri=/bulkread/binary5.jpg&uri=/bulkread/binary6.jpg&uri=/bulkread/binary7.jpg&uri=/bulkread/binary8.jpg&uri=/bulkread/binary9.jpg&uri=/bulkread/binary10.jpg&uri=/bulkread/binary11.jpg&uri=/bulkread/binary12.jpg&uri=/bulkread/binary13.jpg&uri=/bulkread/binary14.jpg&uri=/bulkread/binary15.jpg&uri=/bulkread/binary16.jpg&uri=/bulkread/binary17.jpg&uri=/bulkread/binary18.jpg&uri=/bulkread/binary19.jpg&uri=/bulkread/binary20.jpg&uri=/bulkread/binary21.jpg&uri=/bulkread/binary22.jpg&uri=/bulkread/binary23.jpg&uri=/bulkread/binary24.jpg&uri=/bulkread/binary25.jpg&uri=/bulkread/binary26.jpg&uri=/bulkread/binary27.jpg&uri=/bulkread/binary28.jpg&uri=/bulkread/binary29.jpg&uri=/bulkread/binary30.jpg&uri=/bulkread/binary31.jpg&uri=/bulkread/binary32.jpg&uri=/bulkread/binary33.jpg&uri=/bulkread/binary34.jpg&uri=/bulkread/binary35.jpg&uri=/bulkread/binary36.jpg&uri=/bulkread/binary37.jpg&uri=/bulkread/binary38.jpg&uri=/bulkread/binary39.jpg&uri=/bulkread/binary40.jpg&uri=/bulkread/binary41.jpg&uri=/bulkread/binary42.jpg&uri=/bulkread/binary43.jpg&uri=/bulkread/binary44.jpg&uri=/bulkread/binary45.jpg&uri=/bulkread/binary46.jpg&uri=/bulkread/binary47.jpg&uri=/bulkread/binary48.jpg&uri=/bulkread/binary49.jpg&uri=/bulkread/binary50.jpg&uri=/bulkread/binary51.jpg&uri=/bulkread/binary52.jpg&uri=/bulkread/binary53.jpg&uri=/bulkread/binary54.jpg&uri=/bulkread/binary55.jpg&uri=/bulkread/binary56.jpg&uri=/bulkread/binary57.jpg&uri=/bulkread/binary58.jpg&uri=/bulkread/binary59.jpg&uri=/bulkread/binary60.jpg&uri=/bulkread/binary61.jpg&uri=/bulkread/binary62.jpg&uri=/bulkread/binary63.jpg&uri=/bulkread/binary64.jpg&uri=/bulkread/binary65.jpg&uri=/bulkread/binary66.jpg&uri=/bulkread/binary67.jpg&uri=/bulkread/binary68.jpg&uri=/bulkread/binary69.jpg&uri=/bulkread/binary70.jpg&uri=/bulkread/binary71.jpg&uri=/bulkread/binary72.jpg&uri=/bulkread/binary73.jpg&uri=/bulkread/binary74.jpg&uri=/bulkread/binary75.jpg&uri=/bulkread/binary76.jpg&uri=/bulkread/binary77.jpg&uri=/bulkread/binary78.jpg&uri=/bulkread/binary79.jpg&uri=/bulkread/binary80.jpg&uri=/bulkread/binary81.jpg&uri=/bulkread/binary82.jpg&uri=/bulkread/binary83.jpg&uri=/bulkread/binary84.jpg&uri=/bulkread/binary85.jpg&uri=/bulkread/binary86.jpg&uri=/bulkread/binary87.jpg&uri=/bulkread/binary88.jpg&uri=/bulkread/binary89.jpg&uri=/bulkread/binary90.jpg&uri=/bulkread/binary91.jpg&uri=/bulkread/binary92.jpg&uri=/bulkread/binary93.jpg&uri=/bulkread/binary94.jpg&uri=/bulkread/binary95.jpg&uri=/bulkread/binary96.jpg&uri=/bulkread/binary97.jpg&uri=/bulkread/binary98.jpg&uri=/bulkread/binary99.jpg&uri=/bulkread/binary100.jpg&uri=/bulkread/binary101.jpg HTTP/1.1" 200 349288834 - "okhttp/3.6.0"

```

**Comment by georgeajit** [comment]
This issue is fixed. Tested on 07/13/2017 with latest pull and on MarkLogic 8.0 Server build 06302017.
