### ISSUE TITLE
Content Not Allowed in Prolog errors in unit tests

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#764]
The following tests are failing with the error "Content is not allowed in prolog":

* PlanGeneratedTest.testFnAnalyzeString2Exec
* PlanGeneratedTest.testFnAnalyzeString3Exec
* RowManagerTest.testResultRowDocs

I wonder if it's related to the double double quotes in the second-to-last line of the wire trace:

```
[DEBUG] wire -  >> "POST /v1/rows?output=object&column-types=rows&node-columns=reference&row-format=json HTTP/1.1[\r][\n]"
[DEBUG] wire -  >> "Content-Type: application/json[\r][\n]"
[DEBUG] wire -  >> "ML-Agent-ID: java[\r][\n]"
[DEBUG] wire -  >> "Accept: multipart/mixed; boundary=Boundary_689_2136918746_1499346414237[\r][\n]"
[DEBUG] wire -  >> "Authorization: Digest username="rest-writer",realm="public",nonce="34f937339b286e645b59de0e384e9d33",opaque="2c85f9763aa3fa65",qop=auth,uri="/v1/rows",cnonce="302a884a",nc=000003fd,response="4d28eec19e4a8578d9e2a2c144993a11"[\r][\n]"
[DEBUG] wire -  >> "Transfer-Encoding: chunked[\r][\n]"
[DEBUG] wire -  >> "Host: localhost:8012[\r][\n]"
[DEBUG] wire -  >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire -  >> "[\r][\n]"
[DEBUG] wire -  >> "31f[\r][\n]"
[DEBUG] wire -  >> "{"$optic":{"ns":"op", "fn":"operators", "args":[{"ns":"op", "fn":"from-literals", "args":[[{"rowId":1}]]}, {"ns":"op", "fn":"select", "args":[[{"ns":"op", "fn":"as", "args":[{"ns":"op", "fn":"col", "args":[{"ns":"xs", "fn":"string", "args":["1"]}]}, {"ns":"xs", "fn":"string", "args":["aXbyc"]}]}, {"ns":"op", "fn":"as", "args":[{"ns":"op", "fn":"col", "args":[{"ns":"xs", "fn":"string", "args":["2"]}]}, {"ns":"xs", "fn":"string", "args":["[xy]"]}]}]]}, {"ns":"op", "fn":"select", "args":[{"ns":"op", "fn":"as", "args":[{"ns":"op", "fn":"col", "args":[{"ns":"xs", "fn":"string", "args":["t"]}]}, {"ns":"fn", "fn":"analyze-string", "args":[{"ns":"op", "fn":"col", "args":[{"ns":"xs", "fn":"string", "args":["1"]}]}, {"ns":"op", "fn":"col", "args":[{"ns":"xs", "fn":"string", "args":["2"]}]}]}]}]}]}}"
[DEBUG] wire -  >> "[\r][\n]"
[DEBUG] wire -  >> "0[\r][\n]"
[DEBUG] wire -  >> "[\r][\n]"
[DEBUG] wire -  << "HTTP/1.1 200 OK[\r][\n]"
[DEBUG] wire -  << "ML-Effective-Timestamp: 14993464126026200[\r][\n]"
[DEBUG] wire -  << "Content-type: multipart/mixed; boundary=Boundary_689_2136918746_1499346414237[\r][\n]"
[DEBUG] wire -  << "Server: MarkLogic[\r][\n]"
[DEBUG] wire -  << "Content-Length: 717[\r][\n]"
[DEBUG] wire -  << "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire -  << "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire -  << "[\r][\n]"
[DEBUG] wire -  << "--Boundary_689_2136918746_1499346414237[\r][\n]"
[DEBUG] wire -  << "Content-Type: application/json; charset=utf-8[\r][\n]"
[DEBUG] wire -  << "Content-Disposition: inline; kind=columns[\r][\n]"
[DEBUG] wire -  << "[\r][\n]"
[DEBUG] wire -  << "{"columns":[{"name":"t"}]}[\r][\n]"
[DEBUG] wire -  << "--Boundary_689_2136918746_1499346414237[\r][\n]"
[DEBUG] wire -  << "Content-Type: application/json; charset=utf-8[\r][\n]"
[DEBUG] wire -  << "Content-Disposition: inline; kind=row[\r][\n]"
[DEBUG] wire -  << "[\r][\n]"
[DEBUG] wire -  << "{"t":{"type":"cid","value":"cid:t[0]"}}[\r][\n]"
[DEBUG] wire -  << "--Boundary_689_2136918746_1499346414237[\r][\n]"
[DEBUG] wire -  << "Content-Type: application/xml; charset=utf-8[\r][\n]"
[DEBUG] wire -  << "Content-ID: <t[0]>[\r][\n]"
[DEBUG] wire -  << "Content-Disposition: inline; kind=row-attachment[\r][\n]"
[DEBUG] wire -  << "[\r][\n]"
[DEBUG] wire -  << ""<s:analyze-string-result xmlns:s=\"http://www.w3.org/2005/xpath-functions\"><s:non-match>aXb</s:non-match><s:match>y</s:match><s:non-match>c</s:non-match></s:analyze-string-result>"[\r][\n]"
[DEBUG] wire -  << "--Boundary_689_2136918746_1499346414237--[\r][\n]"
```

Here's part of a stack trace:

```
org.w3c.dom.ls.LSException: Content is not allowed in prolog.
	at org.apache.xerces.parsers.DOMParserImpl.parse(Unknown Source)
	at com.marklogic.client.io.DOMHandle.receiveContent(DOMHandle.java:404)
	at com.marklogic.client.io.DOMHandle.receiveContent(DOMHandle.java:61)
	at com.marklogic.client.impl.JerseyServices$JerseyResult.getContent(JerseyServices.java:4482)
	at com.marklogic.client.impl.RowManagerImpl$RowRecordImpl.getContent(RowManagerImpl.java:1328)
	at com.marklogic.client.impl.RowManagerImpl$RowRecordImpl.getContentAs(RowManagerImpl.java:1345)
	at com.marklogic.client.test.PlanGeneratedBase.checkXML(PlanGeneratedBase.java:157)
	at com.marklogic.client.test.PlanGeneratedBase.executeTester(PlanGeneratedBase.java:110)
	at com.marklogic.client.test.PlanGeneratedTest.testFnAnalyzeString2Exec(PlanGeneratedTest.java:83)
```

**Comment by sammefford** [comment]
I'm wondering if the test failure in RowManagerTest.testNodes is related.  It says "wrong JSON XPathValue expected:<[New York]> but was:<["New York"]>" and I see this in the wire trace:

    [DEBUG] wire -  << ""New York"[\r][\n]"

**Comment by ehennum** [comment]
Do you happen to know when this regression started?  There were some recent changes to the serialization, which may have introduced a regression.

**Comment by ehennum** [comment]
The server-side serialization bug is believed to be fixed, so this client regression should not be gone.

**Comment by georgeajit** [comment]
These tests are running fine now. Verified on regression status page on 08/14/2017.
