### ISSUE TITLE
Spark : Jersey HTTP client: A message body writer for MultiPart  not found

### ISSUE THREAD

**Issue by xmlking** [marklogic/java-client-api#769]
I have following issue using java-client-api v3.0.7  with Apache Spark 1.6.1
is there any workaround ?

```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 4 in stage 10.0 failed 4 times, most recent failure: Lost task 4.3 in stage 10.0 (TID 290, dbslp1428.uhc.com): com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java class com.sun.jersey.multipart.MultiPart, and Java type class com.sun.jersey.multipart.MultiPart, and MIME media type multipart/mixed; boundary=Boundary_4_818906570_1499798623185 was not found
	at com.sun.jersey.api.client.RequestWriter$RequestEntityWriterImpl.<init>(RequestWriter.java:199)
	at com.sun.jersey.api.client.RequestWriter.getRequestEntityWriter(RequestWriter.java:248)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.getHttpEntity(ApacheHttpClient4Handler.java:241)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.getUriHttpRequest(ApacheHttpClient4Handler.java:197)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:153)
	at com.sun.jersey.api.client.filter.HTTPBasicAuthFilter.handle(HTTPBasicAuthFilter.java:81)
	at com.sun.jersey.api.client.Client.handle(Client.java:648)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:670)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:563)
	at com.marklogic.client.impl.JerseyServices.doPost(JerseyServices.java:4357)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3583)
	at com.marklogic.client.impl.JerseyServices.postBulkDocuments(JerseyServices.java:3696)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:564)
	at com.marklogic.client.impl.JSONDocumentImpl.write(JSONDocumentImpl.java:26)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:557)
	at com.marklogic.client.impl.JSONDocumentImpl.write(JSONDocumentImpl.java:26)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:541)
	at com.marklogic.client.impl.JSONDocumentImpl.write(JSONDocumentImpl.java:26)
	at com.optum.chwy.jobs.Claims2MLKt$main$1.call(Claims2ML.kt:116)
	at com.optum.chwy.jobs.Claims2MLKt$main$1.call(Claims2ML.kt)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:225)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:225)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sammefford** [comment]
According to this page, Spark 1.6.1 is using Jersey 1.9.  If that's on the classpath, it's likely to conflict with Jersey 1.17 which the Java Client API needs.    Are you able to remove Jersey 1.9 from the classpath and see if you can run with just Jersey 1.17 on the classpath?

**Comment by xmlking** [comment]
My Spark cluster is remote and I guess I cannot force  Jersey 1.17 even I my fatjar contain Jersey 1.17. 
I am making fatjar with shadowJar gradle plugin.
 
```
shadowJar {
    zip64 true
    dependencies {
        include(dependency("org.jetbrains.kotlin::.*"))
        include(dependency("com.databricks:spark-csv_2.10:.*"))
        include(dependency("org.apache.commons:commons-csv:.*"))
        include(dependency("com.marklogic:java-client-api:.*"))
        include(dependency("com.sun.jersey.contribs:jersey-multipart:.*"))
        include(dependency("com.sun.jersey.contribs:jersey-apache-client4:.*"))
        include(dependency("com.sun.jersey:jersey-client:.*"))
        include(dependency("com.sun.jersey:jersey-core:.*"))
    }
}
```  

I tried to force  1.9 in my client jar but it didn't help
```
configurations.all {
    resolutionStrategy {
        force("com.sun.jersey:jersey-core:1.9")
        force("com.sun.jersey:jersey-client:1.9")
        force("com.sun.jersey:jersey-json:1.9")
    }
}
```

**Comment by xmlking** [comment]
I got apache spark integration working with `3.0-develop` branch with `OkHttp`
hope to see this branch released soon on Maven repository.

**Comment by sammefford** [comment]
Great!  We'll let you know when it's released, and once you confirm that it works for you we'll close this.

**Comment by xmlking** [comment]
**Create**, **Delete** actions work but **Patch** is not working with `3.0-develop` lib.
no errors in the logs but document is not getting patches. 
Am I  doing anything wrong ? 

```kotlin
import com.fasterxml.jackson.databind.ObjectMapper
import com.marklogic.client.DatabaseClientFactory
import com.marklogic.client.DatabaseClientFactory.Authentication
import com.marklogic.client.document.DocumentPatchBuilder.Position
import com.marklogic.client.io.JacksonHandle


fun main(args: Array<String>) {
    val host = "localhost"
    val port = 8000
    val username = "admin"
    val password = "admin"
    val authentication = Authentication.DIGEST

    println("--------------")
    try {
        val mlClient = DatabaseClientFactory.newClient(host, port, username, password, authentication)
        val docMgr = mlClient.newJSONDocumentManager()
        val mapper = ObjectMapper()

        val patchBuilder = docMgr.newPatchBuilder()
        patchBuilder.insertFragment("/test", Position.LAST_CHILD, mapper.createObjectNode().put("test", "test").put("xxx", "xxx"))
//        patchBuilder.replaceFragment("/test", mapper.createObjectNode().put("test1", "test1").put("xxx1", "xxx1"))
//        patchBuilder.replaceValue("createdBy", "sumo");

        println ("patch " + patchBuilder.build().toString());

        docMgr.patch( "/abc/123.json", patchBuilder.build())

        val handle = JacksonHandle()
        docMgr.read("/abc/123.json", handle);
        println(handle)
        mlClient.release();
    } catch (e: Error) {
        println(e)
    }
    println("--------------")
}
```

output 
```
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
15:21:14.828 [main] DEBUG c.m.client.DatabaseClientFactory - Creating new database client for server at localhost:8000
15:21:14.857 [main] DEBUG c.m.client.impl.OkHttpServices - Connecting to localhost at 8000 as admin
patch {"pathlang":"xpath", "patch":[{"insert":{"context":"/test", "position":"last-child", "content":{"test":"test","xxx":"xxx"}}}]}
15:21:15.181 [main] INFO  c.m.client.impl.DocumentManagerImpl - Patching document
15:21:15.182 [main] DEBUG c.m.client.impl.OkHttpServices - Sending /abc/123.json document in transaction null
15:21:16.137 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for /abc/123.json
15:21:16.137 [main] DEBUG c.m.client.impl.OkHttpServices - Getting /abc/123.json in transaction null
----- rmoved {} ----
15:21:16.547 [main] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
15:21:16.547 [main] DEBUG c.m.client.impl.OkHttpServices - Releasing connection
--------------
```

**Comment by xmlking** [comment]
I am trying to add a new child node "abc" to a json document.  It is returning "HTTP/1.1 204 Unchanged"
I have success only if "abc" already exist in the target document. 
will it be possible to add new child node with patch method? 

```java
patchBuilder.replaceInsertFragment("/aaa", "/xxx", Position.LAST_CHILD,
    mapper.createObjectNode().set("abc", mapper.createObjectNode().put("test", "test2").put("xxx", "222")))

```

**Comment by sammefford** [comment]
@xmlking would you be able to create a new issue for this?  It's best to keep issues focused on one topic.  

Also, in the new issue, could you include the contents of /abc/123.json?  It's hard to troubleshoot a patch without knowing the document structure.

**Comment by xmlking** [comment]
Thanks. it was my misunderstanding on how   `replaceFragment` `InsertFragment` works. now my issue is solved.

**Comment by sammefford** [comment]
@xmlking can you try out 3.0.8 and confirm that it still works for you?

**Comment by xmlking** [comment]
Upgraded to 3.0.8 and all tests passed. Thanks 

Test Script:
```kotlin
import com.fasterxml.jackson.databind.JsonNode
import com.marklogic.client.DatabaseClientFactory
import com.marklogic.client.io.StringHandle
import org.apache.spark.sql.SparkSession
import java.nio.file.Files
import java.nio.file.Paths

fun main(args: Array<String>) {

    val spark = with(SparkSession.builder()) {
        master("local")
        appName("ML Testing")
        getOrCreate()
    }

    spark.sparkContext().setLogLevel("ERROR")

    val input = spark.sparkContext().conf["spark.myapp.input"]
    val output = spark.sparkContext().conf["spark.myapp.output"]

    // MarkLogic
    val host = spark.sparkContext().conf["spark.marklogic.host"]
    val port = spark.sparkContext().conf["spark.marklogic.port"].toInt()
    val username = spark.sparkContext().conf["spark.marklogic.username"]
    val password = spark.sparkContext().conf["spark.marklogic.password"]
    val authentication = DatabaseClientFactory.Authentication.BASIC

    val docId = "/data/test.json"

    val mlClient = DatabaseClientFactory.newClient(host, port, username, password, authentication)
    val docMgr = mlClient.newJSONDocumentManager()

    Files.newInputStream(Paths.get("data/in/test.json")).buffered().reader().use {
        val content = it.readText()

        // write the document content
        docMgr.write(docId, StringHandle().with(content))
    }

    val patchBuilder = docMgr.newPatchBuilder()
    patchBuilder.replaceFragment("timestamp", "{\"firstName\":\"Albert\", \"lastName\":\"Einstein\"}");

    docMgr.patch(docMgr.newDescriptor(docId), patchBuilder.build())

    val readDocument = docMgr.readAs(docId, JsonNode::class.java)
    println(readDocument)

    // access the document content
    val firstField = readDocument.fields().next()
    println("firstField ${firstField.key} : ${firstField.value}")


    // delete the document
    docMgr.delete(docId)

    mlClient.release();
}
```

**Comment by sammefford** [comment]
Thanks @xmlking !
