### ISSUE TITLE
OkHttpServices setting the format incorrectly for Optic API

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#777]
I'm getting the following test failures:

  PlanGeneratedTest.testFnAnalyzeString2Exec:83->PlanGeneratedBase.executeTester:110->PlanGeneratedBase.checkXML:157 ▒ IllegalArgument
  PlanGeneratedTest.testFnAnalyzeString3Exec:88->PlanGeneratedBase.executeTester:110->PlanGeneratedBase.checkXML:157 ▒ IllegalArgument
  RowManagerTest.testResultRowDocs:388 ▒ IllegalArgument XMLStreamReaderHandle s...
  RowManagerTest.testResultRows:303 ▒ IllegalArgument XMLStreamReaderHandle supp...
  RowManagerTest.testNodes:690 ▒ IllegalArgument DOMHandle supports the XML form...

```
testFnAnalyzeString2Exec(com.marklogic.client.test.PlanGeneratedTest)  Time elapsed: 0.184 sec  <<< ERROR!
java.lang.IllegalArgumentException: DOMHandle supports the XML format only
        at com.marklogic.client.io.DOMHandle.setFormat(DOMHandle.java:163)
        at com.marklogic.client.impl.OkHttpServices.updateFormat(OkHttpServices.java:1778)
        at com.marklogic.client.impl.OkHttpServices.access$2300(OkHttpServices.java:158)
        at com.marklogic.client.impl.OkHttpServices$OkHttpResult.getContent(OkHttpServices.java:4337)
        at com.marklogic.client.impl.RowManagerImpl$RowRecordImpl.getContent(RowManagerImpl.java:1328)
        at com.marklogic.client.impl.RowManagerImpl$RowRecordImpl.getContentAs(RowManagerImpl.java:1345)
        at com.marklogic.client.test.PlanGeneratedBase.checkXML(PlanGeneratedBase.java:157)
        at com.marklogic.client.test.PlanGeneratedBase.executeTester(PlanGeneratedBase.java:110)
        at com.marklogic.client.test.PlanGeneratedTest.testFnAnalyzeString2Exec(PlanGeneratedTest.java:83)

testFnAnalyzeString3Exec(com.marklogic.client.test.PlanGeneratedTest)  Time elapsed: 0.068 sec  <<< ERROR!
java.lang.IllegalArgumentException: DOMHandle supports the XML format only
        at com.marklogic.client.io.DOMHandle.setFormat(DOMHandle.java:163)
        at com.marklogic.client.impl.OkHttpServices.updateFormat(OkHttpServices.java:1778)
        at com.marklogic.client.impl.OkHttpServices.access$2300(OkHttpServices.java:158)
        at com.marklogic.client.impl.OkHttpServices$OkHttpResult.getContent(OkHttpServices.java:4337)
        at com.marklogic.client.impl.RowManagerImpl$RowRecordImpl.getContent(RowManagerImpl.java:1328)
        at com.marklogic.client.impl.RowManagerImpl$RowRecordImpl.getContentAs(RowManagerImpl.java:1345)
        at com.marklogic.client.test.PlanGeneratedBase.checkXML(PlanGeneratedBase.java:157)
        at com.marklogic.client.test.PlanGeneratedBase.executeTester(PlanGeneratedBase.java:110)
        at com.marklogic.client.test.PlanGeneratedTest.testFnAnalyzeString3Exec(PlanGeneratedTest.java:88)

testResultRowDocs(com.marklogic.client.test.RowManagerTest)  Time elapsed: 0.828 sec  <<< ERROR!
java.lang.IllegalArgumentException: XMLStreamReaderHandle supports the XML format only
        at com.marklogic.client.io.XMLStreamReaderHandle.setFormat(XMLStreamReaderHandle.java:166)
        at com.marklogic.client.impl.OkHttpServices.updateFormat(OkHttpServices.java:1778)
        at com.marklogic.client.impl.OkHttpServices.access$2300(OkHttpServices.java:158)
        at com.marklogic.client.impl.OkHttpServices$OkHttpResult.getContent(OkHttpServices.java:4340)
        at com.marklogic.client.impl.RowManagerImpl$RowSetBase.parseColumns(RowManagerImpl.java:452)
        at com.marklogic.client.impl.RowManagerImpl$RowSetBase.init(RowManagerImpl.java:390)
        at com.marklogic.client.impl.RowManagerImpl.resultRows(RowManagerImpl.java:199)
        at com.marklogic.client.impl.RowManagerImpl.resultRows(RowManagerImpl.java:183)
        at com.marklogic.client.test.RowManagerTest.testResultRowDocs(RowManagerTest.java:388)

testResultRows(com.marklogic.client.test.RowManagerTest)  Time elapsed: 0.077 sec  <<< ERROR!
java.lang.IllegalArgumentException: XMLStreamReaderHandle supports the XML format only
        at com.marklogic.client.io.XMLStreamReaderHandle.setFormat(XMLStreamReaderHandle.java:166)
        at com.marklogic.client.impl.OkHttpServices.updateFormat(OkHttpServices.java:1778)
        at com.marklogic.client.impl.OkHttpServices.access$2300(OkHttpServices.java:158)
        at com.marklogic.client.impl.OkHttpServices$OkHttpResult.getContent(OkHttpServices.java:4340)
        at com.marklogic.client.impl.RowManagerImpl$RowSetBase.parseColumns(RowManagerImpl.java:452)
        at com.marklogic.client.impl.RowManagerImpl$RowSetBase.init(RowManagerImpl.java:390)
        at com.marklogic.client.impl.RowManagerImpl.resultRows(RowManagerImpl.java:199)
        at com.marklogic.client.impl.RowManagerImpl.resultRows(RowManagerImpl.java:183)
        at com.marklogic.client.test.RowManagerTest.testResultRows(RowManagerTest.java:303)

testNodes(com.marklogic.client.test.RowManagerTest)  Time elapsed: 0.132 sec  <<< ERROR!
java.lang.IllegalArgumentException: DOMHandle supports the XML format only
        at com.marklogic.client.io.DOMHandle.setFormat(DOMHandle.java:163)
        at com.marklogic.client.impl.OkHttpServices.updateFormat(OkHttpServices.java:1778)
        at com.marklogic.client.impl.OkHttpServices.access$2300(OkHttpServices.java:158)
        at com.marklogic.client.impl.OkHttpServices$OkHttpResult.getContent(OkHttpServices.java:4340)
        at com.marklogic.client.impl.RowManagerImpl$RowRecordImpl.getContent(RowManagerImpl.java:1328)
        at com.marklogic.client.test.RowManagerTest.testNodes(RowManagerTest.java:690)
```

**Comment by sammefford** [comment]
Ajit, all we need for testing this is to see that these unit tests now pass.

**Comment by georgeajit** [comment]
Verified with MarkLogic Server build 20170821 with 5.0-SNAPSHOT (develop) branch. The test passes on local Linux box.
