### ISSUE TITLE
TransformTest failing with Invalid coercion error

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#800]
testXQueryRestTransformAdapter(com.marklogic.client.test.TransformTest)  Time elapsed: 2.715 sec  <<< ERROR!
com.marklogic.client.FailedRequestException: Local message: read failed: Internal Server Error. Server Message: XDMP-AS: (err:XPTY0004) $service($context, $service-params, $input) -- Invalid coercion: map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) as document-node() . See the MarkLogic server error log for further detail.
        at com.marklogic.client.impl.JerseyServices.getDocumentImpl(JerseyServices.java:784)
        at com.marklogic.client.impl.JerseyServices.getDocument(JerseyServices.java:661)
        at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:389)
        at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:273)
        at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:223)
        at com.marklogic.client.test.TransformTest.runTransform(TransformTest.java:195)
        at com.marklogic.client.test.TransformTest.testXQueryRestTransformAdapter(TransformTest.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testJavascriptRestTransformAdapter(com.marklogic.client.test.TransformTest)  Time elapsed: 1.031 sec  <<< ERROR!
com.marklogic.client.FailedRequestException: Local message: read failed: Internal Server Error. Server Message: XDMP-AS: (err:XPTY0004) $service($context, $service-params, $input) -- Invalid coercion: json:object(<json:object xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) as document-node() . See the MarkLogic server error log for further detail.
        at com.marklogic.client.impl.JerseyServices.getDocumentImpl(JerseyServices.java:784)
        at com.marklogic.client.impl.JerseyServices.getDocument(JerseyServices.java:661)
        at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:389)
        at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:273)
        at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:223)
        at com.marklogic.client.test.TransformTest.runTransform(TransformTest.java:195)
        at com.marklogic.client.test.TransformTest.testJavascriptRestTransformAdapter(TransformTest.java:184)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by sammefford** [comment]
It turns out the fix for REST bug #46692 changed Modules/MarkLogic/rest-api/lib/extensions-util.xqy function apply-transform to no longer return document-node() but to now return a map:map with a property "result" which is a sequence of document-node().  I updated RestTransformAdapter.xqy to expect this new return from apply-transform.

**Comment by sammefford** [comment]
Ajit, if the TransformTest now passes, then we're golden for this issue.

**Comment by georgeajit** [comment]
Ran the test on MarkLogic Server build 20170824 with develop (5.0-SNAPSHOT.jar). The test passes.
```

Name | Status | Type | Time(s)
-- | -- | -- | --
testJavascriptTransform | Success |   | 3.386
testJavascriptMlcpTransformAdapter | Success |   | 4.226
test118 | Success |   | 2.811
testXQueryRestTransformAdapter | Success |   | 2.227
testXQueryTransform | Success |   | 0.034
testJavascriptRestTransformAdapter | Success |   | 0.541
testXSLTransform | Success |   | 0.496
testXQueryMlcpTransformAdapter | Success |   | 4.008


```
