### ISSUE TITLE
Process hangs after WriteBatcher job is stopped (since the hosts were unreachable)

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#829]
We are finding scenarios where requests hang rather than throwing an exception when a host is unavailable.  All failed requests should either throw an exception immediately or retry for up to 2 mins if the server is throwing a retryable error such as status 503.

In the test a write batcher job is running from a client machine against a 3 node cluster with forest on 3 hosts . During the run, the network connection between the client and servers is turned off . We call the retry method again if an exception occurs during the first retry so retry is getting called continuously. I see in the log that when  number of available hosts < minHosts the job stops . Sometime after job is stopped, the retry is aborted but the process hangs and I see the heap size is slowly increasing with time. The thread dump after the retry is aborted and when the process hangs is attached 
[jstack](https://github.com/marklogic/java-client-api/files/1345927/jstack2.txt)

```
16:31:06.984 [pool-3-thread-6] ERROR c.m.c.d.HostAvailabilityListener - ERROR: host unavailable "rh7v-intel64-90-test-20.marklogic.com", black-listing it for PT10M
16:31:07.074 [pool-3-thread-3] ERROR c.m.c.d.HostAvailabilityListener - ERROR: host unavailable "rh7v-intel64-90-test-19.marklogic.com", black-listing it for PT10M
16:31:25.982 [pool-3-thread-11] ERROR c.m.c.d.HostAvailabilityListener - Encountered [com.marklogic.client.MarkLogicIOException: java.net.UnknownHostException: rh7v-intel64-90-test-21.marklogic.com] on host "rh7v-intel64-90-test-21.marklogic.com" but black-listing it would drop job below minHosts
16:31:26.032 [pool-3-thread-3] WARN  c.m.c.d.impl.WriteBatcherImpl - Job is now stopped, aborting the retry
```
 Also . The log is attached 
[ClientLog](https://github.com/marklogic/java-client-api/files/1345805/temp.txt)

```
 WriteBatcher ihb2 = dmManager.newWriteBatcher();
      ihb2.withBatchSize(200);
      // ihb2.withTransactionSize(2);
      ihb2.withThreadCount(20);
      dmManager.startJob(ihb2);

      ihb2.onBatchSuccess(
          batch -> {

            successCount.getAndAdd(batch.getItems().length);
          }
          )
          .onBatchFailure(
              (batch, throwable) -> {
                throwable.printStackTrace();
                System.out.println("Failure Batch size " + batch.getItems().length);
                for (WriteEvent w : batch.getItems()) {
                  System.out.println("Failure " + w.getTargetUri());
                }
                failState.set(true);
                failCount.getAndAdd(batch.getItems().length);
              });

      for (int j = 0; j < 25000; j++) {
        String uri = "/local/ABC-" + j;
        ihb2.add(uri, stringHandle);
      }
  ihb2.flushAndWait();
```

**Comment by srinathgit** [comment]
The stack trace of the same scenario when not using DMSDK. The process hangs forever and no relevant info is found in client log

```
..
..
14:41:24.849 [main] DEBUG c.m.client.impl.OkHttpServices - Posting documents
14:41:24.849 [main] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
Wrote a batch count = 7799
14:41:24.991 [main] DEBUG c.m.client.impl.OkHttpServices - Posting documents
14:41:24.991 [main] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
```


```
2017-10-03 14:43:35
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode):

"OkHttp ConnectionPool" #14 daemon prio=5 os_prio=0 tid=0x0000000028fb9000 nid=0x1a64 in Object.wait() [0x000000002947f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
               at java.lang.Object.wait(Native Method)
               at java.lang.Object.wait(Object.java:460)
               at okhttp3.ConnectionPool$1.run(ConnectionPool.java:67)
               - locked <0x00000005c26d3198> (a okhttp3.ConnectionPool)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
               at java.lang.Thread.run(Thread.java:748)

"ReaderThread" #11 prio=5 os_prio=0 tid=0x0000000028ccb800 nid=0x338c runnable [0x0000000028a4e000]
   java.lang.Thread.State: RUNNABLE
               at java.net.SocketInputStream.socketRead0(Native Method)
               at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
               at java.net.SocketInputStream.read(SocketInputStream.java:171)
               at java.net.SocketInputStream.read(SocketInputStream.java:141)
               at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
               at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
               at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
               - locked <0x00000005c241ab98> (a java.io.InputStreamReader)
               at java.io.InputStreamReader.read(InputStreamReader.java:184)
               at java.io.BufferedReader.fill(BufferedReader.java:161)
               at java.io.BufferedReader.readLine(BufferedReader.java:324)
               - locked <0x00000005c241ab98> (a java.io.InputStreamReader)
               at java.io.BufferedReader.readLine(BufferedReader.java:389)
               at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner$ReaderThread.run(RemoteTestRunner.java:135)

"Service Thread" #10 daemon prio=9 os_prio=0 tid=0x0000000026a2e000 nid=0x2478 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #9 daemon prio=9 os_prio=2 tid=0x00000000269ca800 nid=0x104c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x000000002699e800 nid=0x2f84 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x0000000026997800 nid=0xc04 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x0000000026990800 nid=0x24c4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x000000002698f800 nid=0x1fdc waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x000000002698a800 nid=0x2810 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x00000000258d4000 nid=0xb88 in Object.wait() [0x0000000027e0f000]
   java.lang.Thread.State: WAITING (on object monitor)
               at java.lang.Object.wait(Native Method)
               - waiting on <0x00000005c241d898> (a java.lang.ref.ReferenceQueue$Lock)
               at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
               - locked <0x00000005c241d898> (a java.lang.ref.ReferenceQueue$Lock)
               at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
               at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x00000000258cd000 nid=0x3180 in Object.wait() [0x0000000027c9f000]
   java.lang.Thread.State: WAITING (on object monitor)
               at java.lang.Object.wait(Native Method)
               - waiting on <0x00000005c24244c0> (a java.lang.ref.Reference$Lock)
               at java.lang.Object.wait(Object.java:502)
               at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
               - locked <0x00000005c24244c0> (a java.lang.ref.Reference$Lock)
               at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00000000021cf800 nid=0x1310 runnable [0x000000000252c000]
   java.lang.Thread.State: RUNNABLE
               at java.net.SocketInputStream.socketRead0(Native Method)
               at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
               at java.net.SocketInputStream.read(SocketInputStream.java:171)
               at java.net.SocketInputStream.read(SocketInputStream.java:141)
               at okio.Okio$2.read(Okio.java:139)
               at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
               at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
               at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
               at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
               at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
               at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
               at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
               at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
               at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
               at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
               at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
               at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
               at okhttp3.RealCall.execute(RealCall.java:77)
               at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:695)
               at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:690)
               at com.marklogic.client.impl.OkHttpServices.doPost(OkHttpServices.java:4052)
               at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3353)
               at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3461)
               at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
               at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
               at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:590)
               at com.marklogic.client.functionaltest.TestBulkSearchWithStringQueryDef.loadTxtDocuments(TestBulkSearchWithStringQueryDef.java:145)
               at com.marklogic.client.functionaltest.TestBulkSearchWithStringQueryDef.testBulkSearchSQDwithDifferentPageSizes(TestBulkSearchWithStringQueryDef.java:178)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.lang.reflect.Method.invoke(Method.java:498)
               at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
               at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
               at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
               at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
               at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
               at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
               at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
               at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
               at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
               at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
               at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
               at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
               at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
               at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
               at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
               at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
               at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
               at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
               at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
               at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
               at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
               at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
               at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

"VM Thread" os_prio=2 tid=0x0000000026932800 nid=0x478 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x0000000002060000 nid=0x22c0 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x0000000002061800 nid=0x690 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x0000000002063000 nid=0x25f0 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000002064800 nid=0x32b8 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x0000000002067800 nid=0x30b4 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x0000000002069000 nid=0x2f98 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x000000000206a000 nid=0x2a44 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x000000000206d000 nid=0x1c7c runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x0000000026a43000 nid=0x32ac waiting on condition 

JNI global references: 276

```

**Comment by sammefford** [comment]
I updated the summary with a couple highlights since I think we'll want this issue to be easier for managers to grok.  The current behavior of HostAvailabilityListener only asking one host for updated forest config is expected behavior.  However, it doesn't seem congruent with the general failover support provided by HostAvailabilityListener.  In hind-sight I think we should add the ability to ask any available host in the cluster for the updated forest config.

**Comment by sammefford** [comment]
Since this issue is coming in very late and not one that requires a stop-ship, I think we can push it to 4.0.4

**Comment by vivekmuniyandi** [comment]
I couldn't replicate this issue anymore. 
https://github.com/marklogic/java-client-api/issues/798 - This should have solved this issue. The process goes on in an infinite loop. Looking at the client log, there is an exception during the retry and it keeps calling process failure forever.
