### ISSUE TITLE
Incorrect behavior of QueryBatcher when server becomes unavailable during job

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#832]
I tested the same scenario as #829 with QueryBatcher (disconnect client from the server during job run) and I am seeing different behavior each time.

1. The process hangs with no exceptions/ no nodes getting blacklisted. The [clientLog](https://github.com/marklogic/java-client-api/files/1354263/exception.txt) and 
[thread dump](https://github.com/marklogic/java-client-api/files/1354264/jstack.txt) are attached.
2. The following exception is thrown, no nodes are blacklisted and job gets stopped. The 
[clientLog](https://github.com/marklogic/java-client-api/files/1354276/clientLog.txt) is attached

```
com.marklogic.client.MarkLogicIOException: java.net.SocketTimeoutException: Read timed out
	at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:697)
	at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:690)
	at com.marklogic.client.impl.OkHttpServices.doPost(OkHttpServices.java:4041)
	at com.marklogic.client.impl.OkHttpServices.access$10(OkHttpServices.java:4023)
	at com.marklogic.client.impl.OkHttpServices$23.apply(OkHttpServices.java:3285)
	at com.marklogic.client.impl.OkHttpServices$23.apply(OkHttpServices.java:1)
	at com.marklogic.client.impl.OkHttpServices.sendRequestWithRetry(OkHttpServices.java:719)
	at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3289)
	at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3237)
	at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3228)
	at com.marklogic.client.datamovement.ApplyTransformListener.processEvent(ApplyTransformListener.java:132)
```
3. [clientLog](https://github.com/marklogic/java-client-api/files/1354272/clientLog.txt) is attached. In this example, initially when disconnecting , I see com.marklogic.client.MarkLogicIOException: java.net.SocketTimeoutException: Read timed out getting thrown. After that , I see UnknownHostException being thrown and one of the node getting blacklisted as a result. Then retry is done continuously (it happened for >10 minutes with heap filling rapidly if I don't reconnect). In this case, after a few seconds , the connection to server is established again. The job continues and documents are transformed. After some time , I disconnect the client again. com.marklogic.client.MarkLogicIOException: java.net.SocketTimeoutException: Read timed out is thrown but UnknownHostException  is not. The job ends (similar to case 2)
15:20:54.555 [main] INFO  c.m.c.d.impl.QueryBatcherImpl - Job complete, jobBatchNumber=2114, jobResultsSoFar=21115

Test:

```
@Test
	public void xQueryMasstransformReplace() throws Exception {

		addDocs();
		ServerTransform transform = new ServerTransform("add-attr-xquery-transform");
		transform.put("name", "Lang");
		transform.put("value", "English");

		AtomicInteger skipped = new AtomicInteger(0);
		AtomicInteger success = new AtomicInteger(0);
		AtomicInteger failure = new AtomicInteger(0);
		AtomicBoolean isNode2Running = new AtomicBoolean(true);

		ApplyTransformListener listener = new ApplyTransformListener().withTransform(transform)
				.withApplyResult(ApplyResult.REPLACE).onSuccess(batch -> {
					success.addAndGet(batch.getItems().length);
				}).onSkipped(batch -> {
					skipped.addAndGet(batch.getItems().length);
				});

		QueryBatcher batcher = dmManager.newQueryBatcher(new StructuredQueryBuilder().collection("XmlTransform"))
				.onUrisReady(listener).withBatchSize(10).withThreadCount(5);
		HostAvailabilityListener.getInstance(batcher).withSuspendTimeForHostUnavailable(Duration.ofSeconds(10))
				.withMinHosts(2);
		NoResponseListener.getInstance(batcher).withSuspendTimeForHostUnavailable(Duration.ofSeconds(10))
				.withMinHosts(2);
		NoResponseListener noResponseListener = NoResponseListener.getInstance(batcher);
		BatchFailureListener<QueryBatch> retryListener = noResponseListener.initializeRetryListener(listener);
		listener.onFailure(retryListener).onFailure((batch, throwable) -> {
			failure.addAndGet(batch.getItems().length);
			throwable.printStackTrace();
		});

		JobTicket ticket = dmManager.startJob(batcher);
		batcher.awaitCompletion();
		dmManager.stopJob(ticket);
		String uris[] = new String[30000];
		for (int i = 0; i < 30000; i++) {
			uris[i] = "/local/string-" + i;
		}
		int count = 0;
		// serverStartStop(hostNames[hostNames.length - 2], "start");
		Thread.currentThread().sleep(10000L);
		System.out.println("Transformed docs: " + success.intValue());
		DocumentPage page = dbClient.newDocumentManager().read(uris);
		DOMHandle dh = new DOMHandle();
		while (page.hasNext()) {
			DocumentRecord rec = page.next();
			rec.getContent(dh);
			assertTrue("Element has attribure ? :", dh.get().getElementsByTagName("foo").item(0).hasAttributes());
			assertEquals("Attribute value should be English", "English",
					dh.get().getElementsByTagName("foo").item(0).getAttributes().item(0).getNodeValue());
			count++;
		}
```

**Comment by srinathgit** [comment]
com.marklogic.client.MarkLogicIOException: java.net.SocketTimeoutException: Read timed out occurs with QueryBatcher jobs (QueryBatcherImpl$QueryTask.run, it occured during ApplyTransformListener.processEvent in the previous comment ) as well when the client is disconnected from server during jobs 

```
com.marklogic.client.datamovement.QueryBatchException: com.marklogic.client.MarkLogicIOException: java.net.SocketTimeoutException: Read timed out
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:624)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.marklogic.client.MarkLogicIOException: java.net.SocketTimeoutException: Read timed out
	at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:697)
	at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:690)
	at com.marklogic.client.impl.OkHttpServices.doGet(OkHttpServices.java:3965)
	at com.marklogic.client.impl.OkHttpServices.access$11(OkHttpServices.java:3963)
	at com.marklogic.client.impl.OkHttpServices$19.apply(OkHttpServices.java:3034)
	at com.marklogic.client.impl.OkHttpServices$19.apply(OkHttpServices.java:1)
	at com.marklogic.client.impl.OkHttpServices.sendRequestWithRetry(OkHttpServices.java:719)
	at com.marklogic.client.impl.OkHttpServices.getResource(OkHttpServices.java:3037)
	at com.marklogic.client.impl.OkHttpServices.uris(OkHttpServices.java:3009)
	at com.marklogic.client.impl.QueryManagerImpl.uris(QueryManagerImpl.java:179)
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:573)
	... 3 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:695)
	... 13 more
```

**Comment by vivekmuniyandi** [comment]
Moving to 4.0.4 as there is no data loss here.

**Comment by vivekmuniyandi** [comment]
I tested this and I couldn't replicate this anymore. All I get is the job getting stopped and the process exits without any hangs.
