### ISSUE TITLE
Blacklist occurring with client 4.0.2 and ML 9.0-2

### ISSUE THREAD

**Issue by ryanjdew** [marklogic/java-client-api#842]
I get the issue below and it seems to be related to memory use getting too high. It has run fine against smaller datasets, but when we get into the GB size files it will run fine to a point and then will give the following error and slow to a crawl. Nothing in the MarkLogic Meters data indicates that there is a problem on the MarkLogic side. 

```
17:19:52.887 [pool-1-thread-2] ERROR c.m.c.d.HostAvailabilityListener - ERROR: host unavailable "ml-9", black-listing it for PT3M
com.marklogic.client.MarkLogicIOException: Failed to serialize metadata
                at com.marklogic.client.io.DocumentMetadataHandle.sendMetadataImpl(DocumentMetadataHandle.java:801)
                at com.marklogic.client.io.DocumentMetadataHandle.write(DocumentMetadataHandle.java:574)
                at com.marklogic.client.impl.StreamingOutputImpl.writeTo(StreamingOutputImpl.java:58)
                at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
                at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                at okhttp3.RealCall.execute(RealCall.java:69)
                at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:674)
                at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:669)
                at com.marklogic.client.impl.OkHttpServices.doPost(OkHttpServices.java:3992)
                at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3293)
                at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3401)
                at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:613)
                at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
                at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:605)
                at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
                at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:1020)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.stream.XMLStreamException: java.net.SocketException: Broken pipe (Write failed)
                at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.flush(XMLStreamWriterImpl.java:399)
                at com.marklogic.client.io.DocumentMetadataHandle.sendMetadataImpl(DocumentMetadataHandle.java:798)
                ... 39 common frames omitted
Caused by: java.net.SocketException: Broken pipe (Write failed)
                at java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
                at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
                at okio.Okio$1.write(Okio.java:79)
                at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
                at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
                at okhttp3.internal.http1.Http1Codec$ChunkedSink.flush(Http1Codec.java:331)
                at okio.RealBufferedSink.flush(RealBufferedSink.java:218)
                at okio.RealBufferedSink$1.flush(RealBufferedSink.java:199)
                at com.sun.xml.internal.stream.writers.UTF8OutputStreamWriter.flush(UTF8OutputStreamWriter.java:138)
                at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.flush(XMLStreamWriterImpl.java:397)
                ... 40 common frames omitted
```

This is with 4.0.2 Java client and ML 9.0-2. At the bottom is the code for creating the DMSDK and writer. We were running it with a batch size of 5, 16 threads, a data hub transform, and a blacklist timeout of 180 seconds.
 
```java
            this.dataMovementManager = client.newDataMovementManager();
            int batchSize = 5;
            if (properties.containsKey("marklogicBatchSize")) {
                  batchSize = Integer.parseInt(properties.getProperty("marklogicBatchSize"));
            }
            int threadCount = 16;
            if (properties.containsKey("marklogicThreadCount")) {
                  threadCount = Integer.parseInt(properties.getProperty("marklogicThreadCount"));
            }
            this.writer = dataMovementManager.newWriteBatcher().withBatchSize(batchSize).withThreadCount(threadCount);
            ServerTransform runFlow = null;
            if (properties.containsKey("dataHubFlow")) {
                  runFlow = new ServerTransform("run-flow");
                  String dataHubEntity = entityName;
                  if (properties.containsKey("dataHubEntity")) {
                        dataHubEntity = properties.getProperty("dataHubEntity");
                  }
                  runFlow.addParameter("entity", dataHubEntity);
                  runFlow.addParameter("flow", properties.getProperty("dataHubFlow"));
                  runFlow.addParameter("job-id", UUID.randomUUID().toString());
                  runFlow.addParameter("options", new JSONObject().put("targetEntity", entityName).toString());
            }
            writer.withTransform(runFlow);
            if (properties.containsKey("blacklistSuspendTimeSeconds")) {
                  Duration suspendDuration = Duration
                              .of(Long.parseLong(properties.getProperty("blacklistSuspendTimeSeconds")), ChronoUnit.SECONDS);
                  for (WriteFailureListener listener : writer.getBatchFailureListeners()) {
                        if (listener instanceof HostAvailabilityListener) {
                              ((HostAvailabilityListener) listener).withSuspendTimeForHostUnavailable(suspendDuration);
                        }
                  }
            }
            dataMovementManager.startJob(writer);
```

**Comment by sammefford** [comment]
Thanks, @ryanjdew .  Can you add an onBatchFailure listener that prints out the file names from the batches that fail? I'd like as much information as you can give us about those files so we can have the best chance to reproduce.  Also, I'd like to know if this is intermittent or consistent that certain files always fail.

For a temporary workaround you can try one of these options:

1) Remove HostAvailabilityListener from your write batcher using some code like this:

```
this.writer.setBatchFailureListeners(Stream.of(this.writer.getBatchFailureListeners())
  .filter(listener -> ! (listener instanceof HostAvailabilityListener))
  .toArray(WriteFailureListener[]::new)
);
```

2) Configure HostAvailabilityListener to only use more specific SocketException subclasses using 
 something like this:

```
    withHostUnavailableExceptions(BindException.class, ConnectException.class,
        NoRouteToHostException.class, PortUnreachableException.class, 
        SSLException.class, UnknownHostException.class)
```


3) Implement a subclass of HostAvailabilityListener and override the processFailure(WriteBatch, Throwable) method to handle this scenario differently.  Remove HostAvailabilityListener as in option 1 above and replace it with your subclass.

4) Remove HostAvailabilityListener as in option 1 above and replace it with a WriteFailureListener that does what you need.

**Comment by ryanjdew** [comment]
@sammefford Thanks for looking into this. I'm seeing the URIs being output with the HostAvailabilityListener, but I'm not seeing any consistency in the URIs between the ingest runs. I can't share the full logs due to the nature of the data.

**Comment by sammefford** [comment]
Another potential workaround is to use Java Client API 4.0.1.  That uses Jersey for HTTP layer, rather than OkHttp.  It's possible there is a bug in OkHttp when working with GB-size files.

**Comment by sammefford** [comment]
@ryanjdew Can you help us get an [mvce](https://stackoverflow.com/help/mcve) so we can dig into this?

**Comment by sammefford** [comment]
In the absence of a way to reproduce, we can't work on this
