### ISSUE TITLE
Tableau Extract requires PATH to be set to bin folder of the extracted client jars' folder

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#887]
Extracted the client Jars of Tableau 10.3.7 into a local folder on Windows laptop. Setup a project in Eclipse IDE with Tableau Jars externally linked to the project. Ran the attached test.

The test threw an exception message stating 
```
java.lang.UnsatisfiedLinkError: Unable to load library 'TableauExtract': The specified module could not be found.
```
The following help pages indicate that we need to add the path to ```bin``` of the Tableau client Jar extracted folder to the environment variable.
http://onlinehelp.tableau.com/current/api/sdk/en-us/help.htm#SDK/tableau_sdk_using_java_eclipse.htm%3FTocPath%3D_____5

In Eclipse environment we added the ```PATH``` set to the ```bin``` folder in the project's Run/Debug configuration window in the Environment tab pane.

* Version of MarkLogic Java Client API: Issue839
* Version of MarkLogic Server: ML Server 9.0 nightly build
* Java version: 1.8
* OS and version: Windows and on Eclipse IDE
* Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end

```
@Test
	  public void testJsonPropertyWordQuery() throws KeyManagementException, NoSuchAlgorithmException, IOException, SAXException, ParserConfigurationException
	  {
	    System.out.println("In testJsonPropertyWordQuery method");
	    DatabaseClient client = null;
	    DataMovementManager dmManager = null;
	    	    
	    client = getDatabaseClient("eval-user", "x", Authentication.DIGEST);
	    dmManager = client.newDataMovementManager();

	    QueryManager queryMgr = client.newQueryManager();
	    TableauDataExtractWriter tableauWriter = new TableauDataExtractWriter(datasource + "TableauOutput.tde")
	    	      .withColumn("IdCol", Type.INTEGER)
	    	      .withColumn("nameCol", Type.CHAR_STRING);
	    
	    ExtractViaTemplateListener extractor = new ExtractViaTemplateListener();
	    
	    extractor.withTemplate(datasource + "masterDetail.tdex")
	             .withTemplateDatabase(dbName);
	    
	    StructuredQueryBuilder qb = queryMgr.newStructuredQueryBuilder();
	    StructuredQueryDefinition querydef = qb.word(qb.element("id"), "100");
	    QueryBatcher queryBatcher = dmManager.newQueryBatcher(querydef)
	    	    		.onUrisReady(extractor
	    				.onTypedRowReady( row -> {
	    				            tableauWriter.accept((LinkedHashMap<String, XsAnyAtomicTypeVal>) row);
	    				})
	    				);
	    		
	    dmManager.startJob(queryBatcher);
	    queryBatcher.awaitCompletion();
	    dmManager.stopJob(queryBatcher);
	    
	    tableauWriter.close();
}
```

* Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
```
java.lang.UnsatisfiedLinkError: Unable to load library 'TableauExtract': The specified module could not be found.

	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:194)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:283)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:244)
	at com.sun.jna.Native.register(Native.java:1065)
	at com.tableausoftware.extract.Extract.<clinit>(Unknown Source)
	at com.marklogic.client.moveToCommunity.TableauDataExtractWriter.<init>(TableauDataExtractWriter.java:50)
	at com.marklogic.client.functionaltest.TestMLTableauDEWriter.testJsonPropertyWordQuery(TestMLTableauDEWriter.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by sammefford** [comment]
Thanks for logging this, @georgeajit .  Hopefully when people find this page in Google they'll see what you did to resolve it.  @vivekmuniyandi can you make sure that link is in our javadocs?  That is one of the steps to set up the tableau API.  I'm not sure it makes sense for us to be in charge of telling people how to do that, it seems best for us to link customers to tableau docs on that topic.
