### ISSUE TITLE
Streaming Multipart for OkHttp

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#911]
Needed to support streaming bulk read (used by DMSDK ExportListener), optic API, eval, resource extensions, bulk search, and large single document read with metadata. We could perhaps use a stand-alone library like nio-multipart, or the more battle-tested apache fileupload
the only concern about apache fileupload is it depends on apache commons-io which might create version conflicts if other frameworks used by our customers depend on a different version of commons-io.

**Comment by georgeajit** [comment]
As of Java 9, OpenJdk 10 and 11, we see ```java.lang.OutOfMemoryError: Java heap space```, with multi-part parsing of large binary files (~4MB) and a large count (> 100).

Here is a snippet for QA test. The test writes 102 binary files each of size 4 MB and then reads the "uris" .

```
  /*
   * This test uses FileHandle to bulkload 102 binary documents,test bulk read
   * from database.
   */
  @Test
  public void test3ReadMultipleBinaryDoc() throws KeyManagementException, NoSuchAlgorithmException, Exception
  {
	  System.out.println("Inside test3ReadMultipleBinaryDoc");
	  
    try {
		String docId[] = { "Sega-4MB.jpg" };
		int count = 1;
		client = getDatabaseClient("rest-admin", "x", getConnType());
		BinaryDocumentManager docMgr = client.newBinaryDocumentManager();
		DocumentWriteSet writeset = docMgr.newWriteSet();
		File file1 = null;
		file1 = new File("src/test/java/com/marklogic/client/functionaltest/data/" + docId[0]);
		FileHandle h1 = new FileHandle(file1);
		for (int i = 0; i < ndocCount; i++) {
		  writeset.add(DIRECTORY + "binary" + i + ".jpg", h1);
		  if (count % BATCH_SIZE == 0) {
		    docMgr.write(writeset);
		    writeset = docMgr.newWriteSet();
		  }
		  count++;
		}
		if (count % BATCH_SIZE > 0) {
		  docMgr.write(writeset);
		}
		
		String uris[] = new String[ndocCount];
		for (int i = 0; i < ndocCount; i++) {
		  uris[i] = DIRECTORY + "binary" + i + ".jpg";
		}
		count = 0;
		FileHandle rh = new FileHandle();
		DocumentPage page = docMgr.read(uris);
		while (page.hasNext()) {
		  DocumentRecord rec = page.next();
		  validateRecord(rec, Format.BINARY);
		  rec.getContent(rh);
		  assertEquals("Content length :", file1.length(), rh.get().length());
		  count++;
		}
		assertEquals("document count", ndocCount, count);
		// Testing the multiple same uris will not read multiple records
		
		for (int i = 0; i < ndocCount; i++) {
		  uris[i] = DIRECTORY + "binary" + 1 + ".jpg";
		}
		count = 0;
		page = docMgr.read(uris);
		while (page.hasNext()) {
		  DocumentRecord rec = page.next();
		  validateRecord(rec, Format.BINARY);
		  count++;
		}
		System.out.println("Document count test3ReadMultipleBinaryDoc " + count);
		assertEquals("document count", 1, count);
	} catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
    finally {
    	client.release();
    }
  }
```
Here is the stack trace:
```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3744)
	at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at javax.mail.util.ByteArrayDataSource.<init>(ByteArrayDataSource.java:88)
	at com.marklogic.client.impl.OkHttpServices.getEntity(OkHttpServices.java:5370)
	at com.marklogic.client.impl.OkHttpServices.makeResults(OkHttpServices.java:4422)
	at com.marklogic.client.impl.OkHttpServices.getIteratedResourceImpl(OkHttpServices.java:3170)
	at com.marklogic.client.impl.OkHttpServices.getBulkDocumentsImpl(OkHttpServices.java:1045)
	at com.marklogic.client.impl.OkHttpServices.getBulkDocuments(OkHttpServices.java:930)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:461)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:439)
	at com.marklogic.client.impl.DocumentManagerImpl.read(DocumentManagerImpl.java:404)
	at com.marklogic.client.functionaltest.TestBulkReadSample1.test3ReadMultipleBinaryDoc(TestBulkReadSample1.java:227)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
```
 Usage of  ByteArrayDataSource in com.marklogic.client.impl.OkHttpServices.getEntity method 
 of OkHttpServices.java class and changes to Java Garbage collection scheme in post Java 8 releases (Java 8 does not have this issue) seem to have caused this.

For reference, this SO article seem to be explaining a similar case.

https://stackoverflow.com/questions/11290758/how-to-send-email-with-large-attach-outofmemoryerror-java-heap-space

**Comment by ehennum** [comment]
The unit tests are now passing after refactoring to use the streaming nio-multipart-parser.

 When you get a chance, it would be good to run the functional tests on this branch to make sure that we don't have any regressions in functionality.

If that's clean, we can engage with Performance Engineering on an appropriate apples-to-apples performance test to compare the develop branch with the buffered multipart parser and this branch with the streaming multipart parser.

**Comment by georgeajit** [comment]
No regressions due to the changes. Ran a Jenkins job for branch ```issue911``` on MarkLogic Server 10.0-1 nightly build.

**Comment by ehennum** [comment]
Unfortunately, flamegraphs show that the existing in-memory multipart parser is about twice as fast as the nio-multipart-parser

We certainly don't want to trade better performance in the general case for tolerating bulk requests for many very large documents in the special case -- especially given that a workaround would be to request fewer very large documents.

**Comment by dev-nulled** [comment]
@ehennum not saying this should be close or not - but what is going on - everything looks like it got closed 2 hours ago

**Comment by ehennum** [comment]
@dev-nulled, we merely completed some long deferred housekeeping.
The Java API is still carrying 45 open issues.
If you feel any issue was closed prematurely, please feel free to comment on the issue.

**Comment by dev-nulled** [comment]
@ehennum more just making sure things were OK and it was just cleanup.  Saw 250 or so closes in a very short time window ... and the last week or so has been interesting days for many.   Had a situation years back where it was not and I can't just hit you up on hipchat.  Keep being awesome.
