### ISSUE TITLE
Some failed batches not retried during forest failover

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#937]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt
latest develop branch
### Version of MarkLogic Server
9.0-nightly
See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version
8
Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
During forest failover (local disk failover when rh7v-intel64-90-test-18.marklogic.com is stopped), I saw the following exceptions which is not one of the expected exceptions and hence we are not retrying. 
```
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Internal Server Error. Server Message: XDMP-XDQPNOSESSION: xdmp:invoke-function($f, <options xmlns="xdmp:eval"><modules>{ $modules }</modules><root>{ if ($modules eq 0) then "." else "/" }</root><database>{ $database }</database><transaction-mode>{ $mode }</transaction-mode><isolation>different-transaction</isolation><ignore-amps>false</ignore-amps></options>) -- No XDQP session on host rh7v-intel64-90-test-16.marklogic.com, client=rh7v-intel64-90-test-17.marklogic.com, request=moreLocators, session=13509509736594938658, target=16719149441562230128 . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4293)
	at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3380)
	at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3460)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
	at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
	at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:1060)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
The documentation reads "An XDQP message referenced an XDQP session that does not exist. This can happen if an XDQP session timed out (for example, if the network is really busy) or if an XDQP session was terminated (for example, if a node restarted)." If this exception is expected should we include this as part of expected exception for retry ? This causes in the number of docs inserted to be < expected.
### Expected output: What specifically did you expect to happen?
Expect a retry of failed batch
### Alternatives: What else have you tried, actual/expected?
Retried failed batch in failure callback  in my test code .
Log is attached [teststoponenode.txt](https://github.com/marklogic/java-client-api/files/2037768/teststoponenode.txt)

**Comment by ehennum** [comment]
Not a client issue.
