### ISSUE TITLE
Host sometimes doesn't get blacklisted

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#938]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt
develop
### Version of MarkLogic Server
9.0-nightly
See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version
8
Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
```
@Test(timeout = 350000)
	public void testStopOneNodeShortDuration() throws Exception {
		Assume.assumeTrue(hostNames.length > 1);
		
		System.out.println(Thread.currentThread().getStackTrace()[1].getMethodName());
		Assert.assertTrue(evalClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 0);
		final AtomicInteger successCount = new AtomicInteger(0);
		final AtomicBoolean failState = new AtomicBoolean(false);
		final AtomicInteger failCount = new AtomicInteger(0);
		try {
			WriteBatcher ihb2 = dmManager.newWriteBatcher();
			ihb2.withBatchSize(2);
			ihb2.withThreadCount(99);
			HostAvailabilityListener.getInstance(ihb2).withSuspendTimeForHostUnavailable(Duration.ofSeconds(1))
					.withMinHosts(2);
			NoResponseListener.getInstance(ihb2).withSuspendTimeForHostUnavailable(Duration.ofSeconds(1))
					.withMinHosts(2);
			ihb2.onBatchSuccess(batch -> {
				successCount.addAndGet(batch.getItems().length);
			}).onBatchFailure((batch, throwable) -> {
				throwable.printStackTrace();
				failState.set(true);
				failCount.addAndGet(batch.getItems().length);
				if(throwable.getMessage().contains("XDMP-XDQPNOSESSION")) {
					ihb2.retry(batch);
				}
			});

			writeTicket = dmManager.startJob(ihb2);
			AtomicBoolean isRunning = new AtomicBoolean(true);
			for (int j = 0; j < 50000; j++) {
				String uri = "/local/ABC-" + j;
				ihb2.add(uri, stringHandle);
				if (dmManager.getJobReport(writeTicket).getSuccessEventsCount() > 200 && isRunning.get()) {
					isRunning.set(false);
					serverStartStop(hostNames[hostNames.length - 1], "stop");
				}
			}
			ihb2.flushAndWait();

		} catch (Exception e) {
			e.printStackTrace();
		}
		
		System.out.println("Fail : " + failCount.intValue());
		System.out.println("Success : " + successCount.intValue());
		System.out.println("Count : " + evalClient.newServerEval().xquery(query1).eval().next().getNumber().intValue());
		Assert.assertTrue(evalClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 50000);
	}

```

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
The host that is stopped doesn't get blacklisted and the test ultimately times out.
### Expected output: What specifically did you expect to happen?
The test to execute successfully
### Alternatives: What else have you tried, actual/expected?
Log:
```
testStopOneNodeShortDuration
20:51:57.657 [Time-limited test] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [rh7v-intel64-90-test-17.marklogic.com, rh7v-intel64-90-test-16.marklogic.com] hosts with forests for "WBFailover"
20:51:57.657 [Time-limited test] INFO  c.m.c.d.impl.WriteBatcherImpl - Adding DatabaseClient on port 8013 for host "rh7v-intel64-90-test-17.marklogic.com" to the rotation
20:51:57.657 [Time-limited test] INFO  c.m.c.d.impl.WriteBatcherImpl - Adding DatabaseClient on port 8013 for host "rh7v-intel64-90-test-16.marklogic.com" to the rotation
20:51:57.667 [Time-limited test] INFO  c.m.c.d.impl.WriteBatcherImpl - threadCount=99
20:51:57.667 [Time-limited test] INFO  c.m.c.d.impl.WriteBatcherImpl - batchSize=2
Preparing to stop rh7v-intel64-90-test-18.marklogic.com
Stopping MarkLogic
Stopping MarkLogic: .[  OK  ]
Here is the standard error of the command (if any):

stop rh7v-intel64-90-test-18.marklogic.com completed
20:54:00.887 [pool-45-thread-15] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
80>^Acom.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
 at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3376)
 at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3460)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:1060)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
^A20:54:00.896 [pool-45-thread-92] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
80>^Acom.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
 at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3376)
 at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3460)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:1060)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
^A20:54:00.910 [pool-45-thread-11] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
80>^Acom.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
 at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3376)
 at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3460)
V at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:1060)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
^A20:54:00.917 [pool-45-thread-54] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
80>^Acom.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
 at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3376)
 at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3460)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:1060)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
^A20:54:00.924 [pool-45-thread-90] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
80>^Acom.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
 at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3376)
 at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3460)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:1060)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
^A20:54:00.962 [pool-45-thread-29] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
80>^Acom.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
 at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3376)
 at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3460)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
 at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
 at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:1060)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

```

**Comment by vivekmuniyandi** [comment]
Both this and #934 are related to the forest failovers and is not a bug on the client API. Sometimes when the failover happens, the database goes into an unavailable state and the forest is in wait replication and cannot take over as master. During this time, we get a 503 and for service unavailable responses we retry thinking it as a temporary failure -`com.marklogic.client.FailedRequestException: Service unavailable `

The server replication doesn't finish and hence the time out happens. The job is stopped but this retry is at the Okhttpservices level and not the QueryBatcher level and it would keep retrying.

**Comment by vivekmuniyandi** [comment]
I have explained the behaviour in this comment - https://github.com/marklogic/java-client-api/issues/938#issuecomment-405741794

**Comment by ehennum** [comment]
Per Vivek's comment, not a client issue.
