### ISSUE TITLE
Parse exception thrown when API module returns a value of incorrect datatype

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#949]
Version of MarkLogic Java Client API : develop
Version of MarkLogic Server : 9.0 nightly build
Java version : 1.8
OS and version : Windows
Input:
service.json file
```
{
  "endpointDirectory" : "/ext/TestE2EIntegerParaReturnDouble/",
  "$javaClass" : "com.marklogic.client.functionaltest.TestE2EInegerParaReturnDouble"
}

```
Module file name : TestE2EIntegerParamReturnDouble.sjs
```
function TestE2EItemPrice(inputIntegertVaue) {
console.debug("Inside CLIENT API inputIntegertVaue %s", inputIntegertVaue);

var inputInt = parseInt(inputIntegertVaue, 10);
var retDoubleValue;
if (inputInt == 10) {
// Return invalid datatype when input is 10
retDoubleValue = "String10";
}
else {
retDoubleValue = inputInt + 1.00;
}
console.debug("Return from CLIENT API new double value is : %s", retDoubleValue);
return encodeURI(retDoubleValue);
}

var t = TestE2EItemPrice(xdmp.getRequestField("itemId"));
t;
```

Function declaration file:
```
{
  "functionName" : "TestE2EItemPrice",
 "params" : [ {
    "name" : "itemId",
    "datatype" : "int",
    "multiple" : false,
    "nullable" : true
  } ],
  "return" : {
    "datatype" : "double",
    "multiple" : false,
    "nullable" : true
  }
}
```
JUnit test code:
```
package com.marklogic.client.functionaltest;

// IMPORTANT: Do not edit. This file is generated.


import java.util.stream.Stream;
import com.marklogic.client.io.Format;
import com.marklogic.client.io.marker.AbstractWriteHandle;





import com.marklogic.client.DatabaseClient;

import com.marklogic.client.impl.AbstractProxy;

public class TestE2EInegerParaReturnDouble extends AbstractProxy {

    public static TestE2EInegerParaReturnDouble on(DatabaseClient db) {
        return new TestE2EInegerParaReturnDouble(db);
    }

    public TestE2EInegerParaReturnDouble(DatabaseClient db) {
        super(db, "/ext/TestE2EIntegerParaReturnDouble/");
    }

    public Double TestE2EItemPrice(Integer itemId) {
      return DoubleType.toDouble(
        request("TestE2EIntegerParamReturnDouble.sjs", ParameterValuesKind.SINGLE_ATOMIC)
        .withSession()
        .withParams(
        atomicParam("itemId", true, IntegerType.fromInteger(itemId)))
        .withMethod("post")
        .responseSingle(true, null)
        );
    }

}
```
```
@Test
public void TestE2EItemPrice() throws Exception {		  
	  System.out.println("Running TestE2EItemPrice");
         // Invoke the function
// Expecting incorrect data type from module
		double responseBack8 = TestE2EInegerParaReturnDouble.on(dbclient).TestE2EItemPrice(new Integer(10));
		System.out.println("Response from the Client API call is " + responseBack8);
}
```

Actual output:  Parse exception seen (stack trace) 
```
java.lang.NumberFormatException: String10
	at javax.xml.bind.DatatypeConverterImpl._parseDouble(DatatypeConverterImpl.java:250)
	at javax.xml.bind.DatatypeConverterImpl.parseDouble(DatatypeConverterImpl.java:231)
	at javax.xml.bind.DatatypeConverter.parseDouble(DatatypeConverter.java:259)
	at com.marklogic.client.impl.ValueConverter.StringToDoublePrimitive(ValueConverter.java:372)
	at com.marklogic.client.impl.ValueConverter.StringToDouble(ValueConverter.java:369)
	at com.marklogic.client.impl.AbstractProxy$DoubleType.toDouble(AbstractProxy.java:193)
	at com.marklogic.client.functionaltest.TestE2EInegerParaReturnDouble.TestE2EItemPrice(TestE2EInegerParaReturnDouble.java:29)
	at com.marklogic.client.functionaltest.TestClientAPIE2EInegerParaReturnDouble.TestE2EItemPrice(TestClientAPIE2EInegerParaReturnDouble.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

Expected output: User friendly error message.

Alternatives: None

**Comment by georgeajit** [comment]
Also need to account for nulls
```
//Null input. Expect 55555.00 as the return from API module so that we know passing null works
Double responseBack9 = TestE2EInegerParaReturnDouble.on(dbclient).TestE2EItemPrice(null);
System.out.println("Response from the Client API call is " + responseBack9);
		
//Null return. Input 1000 and  return from API module is null 
Double responseBack10 = null;
try {
	responseBack10 = TestE2EInegerParaReturnDouble.on(dbclient).TestE2EItemPrice(1000);
}
catch(Exception ex) {
		System.out.println("Response from the Client API call with null return " + ex.toString());
}
```
SJS  module is:
```
function TestE2EItemPrice(inputIntegertVaue) {
var retDoubleValue;

if (inputIntegertVaue == null) {
// Return a valid datatype back to client so that we know null input parameter works
retDoubleValue = 55555.00;
return encodeURI(retDoubleValue);
}

console.debug("Inside CLIENT API inputIntegertVaue %s", inputIntegertVaue);
var inputInt = parseInt(inputIntegertVaue, 10);


if (inputInt == 10) {
// Return invalid datatype when input is 10
retDoubleValue = "String10";
}
else if (inputInt == 1000) {
// Return null when input is 1000
retDoubleValue = null;
}
else {
retDoubleValue = inputInt + 1.00;
}
console.debug("Return from CLIENT API new double value is : %s", retDoubleValue);
return encodeURI(retDoubleValue);
}

var t = TestE2EItemPrice(xdmp.getRequestField("itemId"));
t;
```
Output is ```java.lang.NumberFormatException: null```

**Comment by ehennum** [comment]
Errors converting one or more atomic response values should now follow the pattern:

    Could not convert to THE_DATA_TYPE: THE_VALUE

as in:

    Could not convert to double: String10

**Comment by georgeajit** [comment]
Receives ```java.lang.IllegalArgumentException:Could not convert to double: String10```  message.
