### ISSUE TITLE
Combined Query with JSON Search Options throws ParseError

### ISSUE THREAD

**Issue by nikos** [marklogic/java-client-api#95]
According to the ML Java Developer Guide ch. 3.7.1 it should be possible to use a RawCombinedQueryDefinition constructed from a JSON string to specify dynamic search options, unfortunately it throws a Parse Error.

My example code: [ProductRepositoryJSON.java](https://github.com/nikos/springboot-marklogic-sample/blob/ee5cfe465dc5fafb1c957fb5646d005ea492e2d5/src/main/java/de/nava/mlsample/service/ProductRepositoryJSON.java#L95) (line 95ff)

I am using ML Server 7.0.3 with Client API 2.0-3 (under JDK 1.7.0-67), the current workaround is to switch from JSON to XML option search query, this works fine.

Complete stack trace:

```
Request processing failed; nested exception is com.marklogic.client.MarkLogicIOException: Could not construct search results: parser error] with root cause

javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content ist nicht zul?ssig in Prolog.
    at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:598)
    at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
    at com.marklogic.client.io.SearchHandle$SearchResponseImpl.parse(SearchHandle.java:979)
    at com.marklogic.client.io.SearchHandle$SearchResponseImpl.access$100(SearchHandle.java:948)
    at com.marklogic.client.io.SearchHandle.receiveContent(SearchHandle.java:157)
    at com.marklogic.client.io.SearchHandle.receiveContent(SearchHandle.java:72)
    at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:199)
    at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:162)
    at de.nava.mlsample.service.ProductRepositoryJSON.findAll(ProductRepositoryJSON.java:125)
    ...
```

**Comment by sammefford** [comment]
We're no longer making enhancements to the 2.x branch.
