### ISSUE TITLE
Enable QueryBatcher to take in a RawCtsQueryDefinition 

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#965]
Right now QueryBatcher can't take in a Raw Cts Query and process results based on the Cts query passed. We need to enable QueryBatcher to take in a RawCtsQueryDefinition in order to accomplish this.

**Comment by vivekmuniyandi** [comment]
Trunk - Committed revision 291425.
b9 - Committed revision 291424.

**Comment by vivekmuniyandi** [comment]
This has a server dependency. Hence 4.1.1 should be aligned with 9.0.7 or it should be released later.

**Comment by georgeajit** [comment]
Running a test with ```RawCtsQueryDefinition```  on a QuerBatcher instance produces ```REST-UNSUPPORTEDPARAM```

The stack trace is:

```
com.marklogic.client.datamovement.QueryBatchException: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at internal/uris: Bad Request. Server Message: REST-UNSUPPORTEDPARAM: (err:FOER0000) Endpoint does not support query parameter: invalid parameters: <cts:word-query xmlns:cts
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:656)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at internal/uris: Bad Request. Server Message: REST-UNSUPPORTEDPARAM: (err:FOER0000) Endpoint does not support query parameter: invalid parameters: <cts:word-query xmlns:cts
	at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4280)
	at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3264)
	at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3210)
	at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3201)
	at com.marklogic.client.impl.OkHttpServices.uris(OkHttpServices.java:2954)
	at com.marklogic.client.impl.QueryManagerImpl.uris(QueryManagerImpl.java:179)
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:607)

```
...
...
// Verify with RawCtsQuery 
      String wordQuery = "<cts:word-query xmlns:cts=\"http://marklogic.com/cts\">" +
    		  "<cts:text>groundbreaking</cts:text></cts:word-query>";
      StringHandle handle = new StringHandle().with(wordQuery);
      RawCtsQueryDefinition querydefRawCts = queryMgr.newRawCtsQueryDefinition(handle);
      StringBuilder batchRawCtsResults = new StringBuilder();
      StringBuilder batchRawCtsFailures = new StringBuilder();
      
      QueryBatcher queryBatcher2 = dmManager.newQueryBatcher(querydefRawCts);
      queryBatcher2.onUrisReady(batch -> {
          for (String str : batch.getItems()) {
        	  batchRawCtsResults.append(str)
                .append('|');
          }
        })
        .onQueryFailure(throwable -> {
          System.out.println("Exceptions thrown from callback onQueryFailure for RawCtsQueryDefinition");
          throwable.printStackTrace();
          batchRawCtsFailures.append("Test has Exceptions");
        });

        JobTicket jobTicketRawCtsQ = dmManager.startJob(queryBatcher2);
...
...
```

**Comment by ehennum** [comment]
The issue is that the handle doesn't specify the format.

A POST without a specified format is being treated as an application/x-www-form-urlencoded, which tries to map the body to URI parameters.

The request succeeds after adding handle.withFormat(Format.XML)

Looking into whether QueryManager defaults the format....

**Comment by ehennum** [comment]
QueryManager defaults the format to XML.  So, the internal requester should do the same.

**Comment by ehennum** [comment]
I updated this test to execute both with and without an explicit format:

com.marklogic.client.test.datamovement.QueryBatcherTest#testRawCtsQuery
