### ISSUE TITLE
error for client with database 

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#970]
In the REST API, a client can specify a different content database with a parameter.  On the enode, that's implemented with a rewriter.

That's not available for Data Services First.  Thus, the base proxy should throw an error if the database client specifies a database explicitly instead of using the default database for the appserver.

**Comment by ehennum** [comment]
To prevent the issue you ran into, the proxy service class will now throw an exception if the client passed into the static instantiation factory specifies an explicit database instead of using the default database for the appserver.

I doubt this fix requires a functional test -- the fix just adds error checking on an input argument -- but you're better placed to make that determination.

**Comment by georgeajit** [comment]
Will run a manual test by changing one of the test to include a database on the DatabaseClient instance.

**Comment by kcoleman-marklogic** [comment]
Just a bit of unsolicited feedback... 

The message says "Client must use the default database instead of: ...". That is going to be confusing if the explicit database is the same as the default database. Would it make sense to say "Client must not explicitly specify a database" or something like that?

**Comment by ehennum** [comment]
Good catch.  How is:  "Client cannot specify a database - specified: "

**Comment by ehennum** [comment]
I also updated the work-in-progress Data Services First documentation to mention this issue and to highlight the disjunction between the REST API and proxy services more generally.

**Comment by kcoleman-marklogic** [comment]
Yeah, that whole situation is super weird and confusing in context because all the rest of the API requires you to connect to a REST instance, and just this one thing doesn't allow it.

**Comment by georgeajit** [comment]
Specifying the database on a DatabaseClient instance throws exceptions. 
```
dbclient = DatabaseClientFactory.newClient(host, port, "Documents", "apiUser", "ap1U53r", Authentication.DIGEST);
```

```
java.lang.IllegalArgumentException: Client cannot specify a database - specified: Documents
	at com.marklogic.client.impl.BaseProxy.<init>(BaseProxy.java:69)
	at com.marklogic.client.functionaltest.TestE2EIntegerParaReturnDouble$1TestE2EIntegerParaReturnDoubleImpl.<init>(ClientApiFunctionalTest.java:620)
	at com.marklogic.client.functionaltest.TestE2EIntegerParaReturnDouble.on(ClientApiFunctionalTest.java:668)
	at com.marklogic.client.functionaltest.ClientApiFunctionalTest.TestE2EItemPrice(ClientApiFunctionalTest.java:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```
